package com.hartwig.hmftools.vcuppa;

import static com.hartwig.hmftools.common.utils.config.CommonConfig.PURPLE_DIR_CFG;
import static com.hartwig.hmftools.common.utils.config.CommonConfig.PURPLE_DIR_DESC;
import static com.hartwig.hmftools.common.utils.config.CommonConfig.SAMPLE;
import static com.hartwig.hmftools.common.utils.config.CommonConfig.SAMPLE_DESC;
import static com.hartwig.hmftools.common.utils.config.ConfigUtils.addLoggingOptions;
import static com.hartwig.hmftools.common.utils.file.FileWriterUtils.addOutputDir;
import static com.hartwig.hmftools.common.utils.file.FileWriterUtils.checkAddDirSeparator;
import static com.hartwig.hmftools.common.utils.file.FileWriterUtils.checkCreateOutputDir;
import static com.hartwig.hmftools.common.utils.file.FileWriterUtils.parseOutputDir;

import com.hartwig.hmftools.common.utils.config.ConfigBuilder;

public class VCuppaConfig
{
    private static final String CUPPA_DATA_PATH_CFG = "cuppa_data";
    private static final String MODEL_PATH_CFG = "model";
    private static final String CUPPA_DATA_DEF_PATH_CFG = "cuppa_data_definitions";

    private final String mSampleId;
    private final String mPurpleDir;
    private final String mCuppaFeaturesPath;

    private final String mModelPath;
    private final String mCuppaDataDefinitionsPath;

    private final String mOutputDir;

    public String getSampleId()
    {
        return mSampleId;
    }

    public String getPurpleDir()
    {
        return mPurpleDir;
    }

    public String getCuppaFeaturesPath()
    {
        return mCuppaFeaturesPath;
    }

    public String getModelPath()
    {
        return mModelPath;
    }

    public String getCuppaFeatureDefinitionsPath()
    {
        return mCuppaDataDefinitionsPath;
    }

    public String getOutputDir()
    {
        return mOutputDir;
    }

    public VCuppaConfig(final ConfigBuilder configBuilder)
    {
        mSampleId = configBuilder.getValue(SAMPLE);
        mPurpleDir = checkAddDirSeparator(configBuilder.getValue(PURPLE_DIR_CFG));
        mCuppaFeaturesPath = configBuilder.getValue(CUPPA_DATA_PATH_CFG);
        mModelPath = configBuilder.getValue(MODEL_PATH_CFG);
        mCuppaDataDefinitionsPath = configBuilder.getValue(CUPPA_DATA_DEF_PATH_CFG);
        mOutputDir = parseOutputDir(configBuilder);
        checkCreateOutputDir(mOutputDir);
    }

    public static void registerConfig(final ConfigBuilder configBuilder)
    {
        configBuilder.addConfigItem(SAMPLE, true, SAMPLE_DESC);
        configBuilder.addConfigItem(PURPLE_DIR_CFG, true, PURPLE_DIR_DESC);
        configBuilder.addConfigItem(CUPPA_DATA_PATH_CFG, true,
                "path to the sample cuppa features tsv file generated by CuppaDataPrep");
        configBuilder.addPath(MODEL_PATH_CFG, true, "path to the torchscript model");
        configBuilder.addPath(CUPPA_DATA_DEF_PATH_CFG, true,
                "path to tsv file that contains the definitions for cuppa features.");
        addOutputDir(configBuilder, true);
        addLoggingOptions(configBuilder);
    }
}