/*
 * This file is generated by jOOQ.
*/
package org.ensembl.database.homo_sapiens_core.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.ensembl.database.homo_sapiens_core.HomoSapiensCore_89_37;
import org.ensembl.database.homo_sapiens_core.Keys;
import org.ensembl.database.homo_sapiens_core.tables.records.CoordSystemRecord;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CoordSystem extends TableImpl<CoordSystemRecord> {

    private static final long serialVersionUID = -593843245;

    /**
     * The reference instance of <code>homo_sapiens_core_89_37.coord_system</code>
     */
    public static final CoordSystem COORD_SYSTEM = new CoordSystem();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CoordSystemRecord> getRecordType() {
        return CoordSystemRecord.class;
    }

    /**
     * The column <code>homo_sapiens_core_89_37.coord_system.coord_system_id</code>.
     */
    public final TableField<CoordSystemRecord, UInteger> COORD_SYSTEM_ID = createField("coord_system_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.coord_system.species_id</code>.
     */
    public final TableField<CoordSystemRecord, UInteger> SPECIES_ID = createField("species_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false).defaultValue(org.jooq.impl.DSL.inline("1", org.jooq.impl.SQLDataType.INTEGERUNSIGNED)), this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.coord_system.name</code>.
     */
    public final TableField<CoordSystemRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(40).nullable(false), this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.coord_system.version</code>.
     */
    public final TableField<CoordSystemRecord, String> VERSION = createField("version", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.coord_system.rank</code>.
     */
    public final TableField<CoordSystemRecord, Integer> RANK = createField("rank", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.coord_system.attrib</code>.
     */
    public final TableField<CoordSystemRecord, String> ATTRIB = createField("attrib", org.jooq.impl.SQLDataType.VARCHAR.length(30), this, "");

    /**
     * Create a <code>homo_sapiens_core_89_37.coord_system</code> table reference
     */
    public CoordSystem() {
        this("coord_system", null);
    }

    /**
     * Create an aliased <code>homo_sapiens_core_89_37.coord_system</code> table reference
     */
    public CoordSystem(String alias) {
        this(alias, COORD_SYSTEM);
    }

    private CoordSystem(String alias, Table<CoordSystemRecord> aliased) {
        this(alias, aliased, null);
    }

    private CoordSystem(String alias, Table<CoordSystemRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return HomoSapiensCore_89_37.HOMO_SAPIENS_CORE_89_37;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<CoordSystemRecord, UInteger> getIdentity() {
        return Keys.IDENTITY_COORD_SYSTEM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<CoordSystemRecord> getPrimaryKey() {
        return Keys.KEY_COORD_SYSTEM_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<CoordSystemRecord>> getKeys() {
        return Arrays.<UniqueKey<CoordSystemRecord>>asList(Keys.KEY_COORD_SYSTEM_PRIMARY, Keys.KEY_COORD_SYSTEM_NAME_IDX, Keys.KEY_COORD_SYSTEM_RANK_IDX);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CoordSystem as(String alias) {
        return new CoordSystem(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public CoordSystem rename(String name) {
        return new CoordSystem(name, null);
    }
}
