/*
 * This file is generated by jOOQ.
*/
package org.ensembl.database.homo_sapiens_core.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.ensembl.database.homo_sapiens_core.HomoSapiensCore_89_37;
import org.ensembl.database.homo_sapiens_core.Keys;
import org.ensembl.database.homo_sapiens_core.enums.DataFileFileType;
import org.ensembl.database.homo_sapiens_core.tables.records.DataFileRecord;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;
import org.jooq.types.UShort;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DataFile extends TableImpl<DataFileRecord> {

    private static final long serialVersionUID = -1515516174;

    /**
     * The reference instance of <code>homo_sapiens_core_89_37.data_file</code>
     */
    public static final DataFile DATA_FILE = new DataFile();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DataFileRecord> getRecordType() {
        return DataFileRecord.class;
    }

    /**
     * The column <code>homo_sapiens_core_89_37.data_file.data_file_id</code>.
     */
    public final TableField<DataFileRecord, UInteger> DATA_FILE_ID = createField("data_file_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.data_file.coord_system_id</code>.
     */
    public final TableField<DataFileRecord, UInteger> COORD_SYSTEM_ID = createField("coord_system_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.data_file.analysis_id</code>.
     */
    public final TableField<DataFileRecord, UShort> ANALYSIS_ID = createField("analysis_id", org.jooq.impl.SQLDataType.SMALLINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.data_file.name</code>.
     */
    public final TableField<DataFileRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.data_file.version_lock</code>.
     */
    public final TableField<DataFileRecord, Byte> VERSION_LOCK = createField("version_lock", org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.data_file.absolute</code>.
     */
    public final TableField<DataFileRecord, Byte> ABSOLUTE = createField("absolute", org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.data_file.url</code>.
     */
    public final TableField<DataFileRecord, String> URL = createField("url", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.data_file.file_type</code>.
     */
    public final TableField<DataFileRecord, DataFileFileType> FILE_TYPE = createField("file_type", org.jooq.util.mysql.MySQLDataType.VARCHAR.asEnumDataType(org.ensembl.database.homo_sapiens_core.enums.DataFileFileType.class), this, "");

    /**
     * Create a <code>homo_sapiens_core_89_37.data_file</code> table reference
     */
    public DataFile() {
        this("data_file", null);
    }

    /**
     * Create an aliased <code>homo_sapiens_core_89_37.data_file</code> table reference
     */
    public DataFile(String alias) {
        this(alias, DATA_FILE);
    }

    private DataFile(String alias, Table<DataFileRecord> aliased) {
        this(alias, aliased, null);
    }

    private DataFile(String alias, Table<DataFileRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return HomoSapiensCore_89_37.HOMO_SAPIENS_CORE_89_37;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<DataFileRecord, UInteger> getIdentity() {
        return Keys.IDENTITY_DATA_FILE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<DataFileRecord> getPrimaryKey() {
        return Keys.KEY_DATA_FILE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<DataFileRecord>> getKeys() {
        return Arrays.<UniqueKey<DataFileRecord>>asList(Keys.KEY_DATA_FILE_PRIMARY, Keys.KEY_DATA_FILE_DF_UNQ_IDX);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DataFile as(String alias) {
        return new DataFile(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public DataFile rename(String name) {
        return new DataFile(name, null);
    }
}
