/*
 * This file is generated by jOOQ.
*/
package org.ensembl.database.homo_sapiens_core.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.ensembl.database.homo_sapiens_core.HomoSapiensCore_89_37;
import org.ensembl.database.homo_sapiens_core.Keys;
import org.ensembl.database.homo_sapiens_core.tables.records.DensityFeatureRecord;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DensityFeature extends TableImpl<DensityFeatureRecord> {

    private static final long serialVersionUID = 1604786822;

    /**
     * The reference instance of <code>homo_sapiens_core_89_37.density_feature</code>
     */
    public static final DensityFeature DENSITY_FEATURE = new DensityFeature();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DensityFeatureRecord> getRecordType() {
        return DensityFeatureRecord.class;
    }

    /**
     * The column <code>homo_sapiens_core_89_37.density_feature.density_feature_id</code>.
     */
    public final TableField<DensityFeatureRecord, UInteger> DENSITY_FEATURE_ID = createField("density_feature_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.density_feature.density_type_id</code>.
     */
    public final TableField<DensityFeatureRecord, UInteger> DENSITY_TYPE_ID = createField("density_type_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.density_feature.seq_region_id</code>.
     */
    public final TableField<DensityFeatureRecord, UInteger> SEQ_REGION_ID = createField("seq_region_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.density_feature.seq_region_start</code>.
     */
    public final TableField<DensityFeatureRecord, UInteger> SEQ_REGION_START = createField("seq_region_start", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.density_feature.seq_region_end</code>.
     */
    public final TableField<DensityFeatureRecord, UInteger> SEQ_REGION_END = createField("seq_region_end", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.density_feature.density_value</code>.
     */
    public final TableField<DensityFeatureRecord, Double> DENSITY_VALUE = createField("density_value", org.jooq.impl.SQLDataType.FLOAT.nullable(false), this, "");

    /**
     * Create a <code>homo_sapiens_core_89_37.density_feature</code> table reference
     */
    public DensityFeature() {
        this("density_feature", null);
    }

    /**
     * Create an aliased <code>homo_sapiens_core_89_37.density_feature</code> table reference
     */
    public DensityFeature(String alias) {
        this(alias, DENSITY_FEATURE);
    }

    private DensityFeature(String alias, Table<DensityFeatureRecord> aliased) {
        this(alias, aliased, null);
    }

    private DensityFeature(String alias, Table<DensityFeatureRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return HomoSapiensCore_89_37.HOMO_SAPIENS_CORE_89_37;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<DensityFeatureRecord, UInteger> getIdentity() {
        return Keys.IDENTITY_DENSITY_FEATURE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<DensityFeatureRecord> getPrimaryKey() {
        return Keys.KEY_DENSITY_FEATURE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<DensityFeatureRecord>> getKeys() {
        return Arrays.<UniqueKey<DensityFeatureRecord>>asList(Keys.KEY_DENSITY_FEATURE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DensityFeature as(String alias) {
        return new DensityFeature(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public DensityFeature rename(String name) {
        return new DensityFeature(name, null);
    }
}
