/*
 * This file is generated by jOOQ.
*/
package org.ensembl.database.homo_sapiens_core.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.ensembl.database.homo_sapiens_core.HomoSapiensCore_89_37;
import org.ensembl.database.homo_sapiens_core.Keys;
import org.ensembl.database.homo_sapiens_core.tables.records.DnaAlignFeatureAttribRecord;
import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;
import org.jooq.types.UShort;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DnaAlignFeatureAttrib extends TableImpl<DnaAlignFeatureAttribRecord> {

    private static final long serialVersionUID = 1132754750;

    /**
     * The reference instance of <code>homo_sapiens_core_89_37.dna_align_feature_attrib</code>
     */
    public static final DnaAlignFeatureAttrib DNA_ALIGN_FEATURE_ATTRIB = new DnaAlignFeatureAttrib();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DnaAlignFeatureAttribRecord> getRecordType() {
        return DnaAlignFeatureAttribRecord.class;
    }

    /**
     * The column <code>homo_sapiens_core_89_37.dna_align_feature_attrib.dna_align_feature_id</code>.
     */
    public final TableField<DnaAlignFeatureAttribRecord, UInteger> DNA_ALIGN_FEATURE_ID = createField("dna_align_feature_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.dna_align_feature_attrib.attrib_type_id</code>.
     */
    public final TableField<DnaAlignFeatureAttribRecord, UShort> ATTRIB_TYPE_ID = createField("attrib_type_id", org.jooq.impl.SQLDataType.SMALLINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.dna_align_feature_attrib.value</code>.
     */
    public final TableField<DnaAlignFeatureAttribRecord, String> VALUE = createField("value", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * Create a <code>homo_sapiens_core_89_37.dna_align_feature_attrib</code> table reference
     */
    public DnaAlignFeatureAttrib() {
        this("dna_align_feature_attrib", null);
    }

    /**
     * Create an aliased <code>homo_sapiens_core_89_37.dna_align_feature_attrib</code> table reference
     */
    public DnaAlignFeatureAttrib(String alias) {
        this(alias, DNA_ALIGN_FEATURE_ATTRIB);
    }

    private DnaAlignFeatureAttrib(String alias, Table<DnaAlignFeatureAttribRecord> aliased) {
        this(alias, aliased, null);
    }

    private DnaAlignFeatureAttrib(String alias, Table<DnaAlignFeatureAttribRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return HomoSapiensCore_89_37.HOMO_SAPIENS_CORE_89_37;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<DnaAlignFeatureAttribRecord>> getKeys() {
        return Arrays.<UniqueKey<DnaAlignFeatureAttribRecord>>asList(Keys.KEY_DNA_ALIGN_FEATURE_ATTRIB_DNA_ALIGN_FEATURE_ATTRIBX);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DnaAlignFeatureAttrib as(String alias) {
        return new DnaAlignFeatureAttrib(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public DnaAlignFeatureAttrib rename(String name) {
        return new DnaAlignFeatureAttrib(name, null);
    }
}
