/*
 * This file is generated by jOOQ.
*/
package org.ensembl.database.homo_sapiens_core.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.ensembl.database.homo_sapiens_core.HomoSapiensCore_89_37;
import org.ensembl.database.homo_sapiens_core.Keys;
import org.ensembl.database.homo_sapiens_core.tables.records.ExonRecord;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;
import org.jooq.types.UShort;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Exon extends TableImpl<ExonRecord> {

    private static final long serialVersionUID = -1628339573;

    /**
     * The reference instance of <code>homo_sapiens_core_89_37.exon</code>
     */
    public static final Exon EXON = new Exon();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ExonRecord> getRecordType() {
        return ExonRecord.class;
    }

    /**
     * The column <code>homo_sapiens_core_89_37.exon.exon_id</code>.
     */
    public final TableField<ExonRecord, UInteger> EXON_ID = createField("exon_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.exon.seq_region_id</code>.
     */
    public final TableField<ExonRecord, UInteger> SEQ_REGION_ID = createField("seq_region_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.exon.seq_region_start</code>.
     */
    public final TableField<ExonRecord, UInteger> SEQ_REGION_START = createField("seq_region_start", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.exon.seq_region_end</code>.
     */
    public final TableField<ExonRecord, UInteger> SEQ_REGION_END = createField("seq_region_end", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.exon.seq_region_strand</code>.
     */
    public final TableField<ExonRecord, Byte> SEQ_REGION_STRAND = createField("seq_region_strand", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.exon.phase</code>.
     */
    public final TableField<ExonRecord, Byte> PHASE = createField("phase", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.exon.end_phase</code>.
     */
    public final TableField<ExonRecord, Byte> END_PHASE = createField("end_phase", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.exon.is_current</code>.
     */
    public final TableField<ExonRecord, Byte> IS_CURRENT = createField("is_current", org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("1", org.jooq.impl.SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.exon.is_constitutive</code>.
     */
    public final TableField<ExonRecord, Byte> IS_CONSTITUTIVE = createField("is_constitutive", org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.exon.stable_id</code>.
     */
    public final TableField<ExonRecord, String> STABLE_ID = createField("stable_id", org.jooq.impl.SQLDataType.VARCHAR.length(128), this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.exon.version</code>.
     */
    public final TableField<ExonRecord, UShort> VERSION = createField("version", org.jooq.impl.SQLDataType.SMALLINTUNSIGNED, this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.exon.created_date</code>.
     */
    public final TableField<ExonRecord, Timestamp> CREATED_DATE = createField("created_date", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.exon.modified_date</code>.
     */
    public final TableField<ExonRecord, Timestamp> MODIFIED_DATE = createField("modified_date", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * Create a <code>homo_sapiens_core_89_37.exon</code> table reference
     */
    public Exon() {
        this("exon", null);
    }

    /**
     * Create an aliased <code>homo_sapiens_core_89_37.exon</code> table reference
     */
    public Exon(String alias) {
        this(alias, EXON);
    }

    private Exon(String alias, Table<ExonRecord> aliased) {
        this(alias, aliased, null);
    }

    private Exon(String alias, Table<ExonRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return HomoSapiensCore_89_37.HOMO_SAPIENS_CORE_89_37;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ExonRecord, UInteger> getIdentity() {
        return Keys.IDENTITY_EXON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ExonRecord> getPrimaryKey() {
        return Keys.KEY_EXON_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ExonRecord>> getKeys() {
        return Arrays.<UniqueKey<ExonRecord>>asList(Keys.KEY_EXON_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Exon as(String alias) {
        return new Exon(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Exon rename(String name) {
        return new Exon(name, null);
    }
}
