/*
 * This file is generated by jOOQ.
*/
package org.ensembl.database.homo_sapiens_core.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.ensembl.database.homo_sapiens_core.HomoSapiensCore_89_37;
import org.ensembl.database.homo_sapiens_core.Keys;
import org.ensembl.database.homo_sapiens_core.enums.GeneStatus;
import org.ensembl.database.homo_sapiens_core.tables.records.GeneRecord;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;
import org.jooq.types.UShort;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Gene extends TableImpl<GeneRecord> {

    private static final long serialVersionUID = 494623022;

    /**
     * The reference instance of <code>homo_sapiens_core_89_37.gene</code>
     */
    public static final Gene GENE = new Gene();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GeneRecord> getRecordType() {
        return GeneRecord.class;
    }

    /**
     * The column <code>homo_sapiens_core_89_37.gene.gene_id</code>.
     */
    public final TableField<GeneRecord, UInteger> GENE_ID = createField("gene_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.gene.biotype</code>.
     */
    public final TableField<GeneRecord, String> BIOTYPE = createField("biotype", org.jooq.impl.SQLDataType.VARCHAR.length(40).nullable(false), this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.gene.analysis_id</code>.
     */
    public final TableField<GeneRecord, UShort> ANALYSIS_ID = createField("analysis_id", org.jooq.impl.SQLDataType.SMALLINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.gene.seq_region_id</code>.
     */
    public final TableField<GeneRecord, UInteger> SEQ_REGION_ID = createField("seq_region_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.gene.seq_region_start</code>.
     */
    public final TableField<GeneRecord, UInteger> SEQ_REGION_START = createField("seq_region_start", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.gene.seq_region_end</code>.
     */
    public final TableField<GeneRecord, UInteger> SEQ_REGION_END = createField("seq_region_end", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.gene.seq_region_strand</code>.
     */
    public final TableField<GeneRecord, Byte> SEQ_REGION_STRAND = createField("seq_region_strand", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.gene.display_xref_id</code>.
     */
    public final TableField<GeneRecord, UInteger> DISPLAY_XREF_ID = createField("display_xref_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED, this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.gene.source</code>.
     */
    public final TableField<GeneRecord, String> SOURCE = createField("source", org.jooq.impl.SQLDataType.VARCHAR.length(40).nullable(false), this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.gene.status</code>.
     */
    public final TableField<GeneRecord, GeneStatus> STATUS = createField("status", org.jooq.util.mysql.MySQLDataType.VARCHAR.asEnumDataType(org.ensembl.database.homo_sapiens_core.enums.GeneStatus.class), this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.gene.description</code>.
     */
    public final TableField<GeneRecord, String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.gene.is_current</code>.
     */
    public final TableField<GeneRecord, Byte> IS_CURRENT = createField("is_current", org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("1", org.jooq.impl.SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.gene.canonical_transcript_id</code>.
     */
    public final TableField<GeneRecord, UInteger> CANONICAL_TRANSCRIPT_ID = createField("canonical_transcript_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.gene.stable_id</code>.
     */
    public final TableField<GeneRecord, String> STABLE_ID = createField("stable_id", org.jooq.impl.SQLDataType.VARCHAR.length(128), this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.gene.version</code>.
     */
    public final TableField<GeneRecord, UShort> VERSION = createField("version", org.jooq.impl.SQLDataType.SMALLINTUNSIGNED, this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.gene.created_date</code>.
     */
    public final TableField<GeneRecord, Timestamp> CREATED_DATE = createField("created_date", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.gene.modified_date</code>.
     */
    public final TableField<GeneRecord, Timestamp> MODIFIED_DATE = createField("modified_date", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * Create a <code>homo_sapiens_core_89_37.gene</code> table reference
     */
    public Gene() {
        this("gene", null);
    }

    /**
     * Create an aliased <code>homo_sapiens_core_89_37.gene</code> table reference
     */
    public Gene(String alias) {
        this(alias, GENE);
    }

    private Gene(String alias, Table<GeneRecord> aliased) {
        this(alias, aliased, null);
    }

    private Gene(String alias, Table<GeneRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return HomoSapiensCore_89_37.HOMO_SAPIENS_CORE_89_37;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<GeneRecord, UInteger> getIdentity() {
        return Keys.IDENTITY_GENE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<GeneRecord> getPrimaryKey() {
        return Keys.KEY_GENE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<GeneRecord>> getKeys() {
        return Arrays.<UniqueKey<GeneRecord>>asList(Keys.KEY_GENE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Gene as(String alias) {
        return new Gene(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Gene rename(String name) {
        return new Gene(name, null);
    }
}
