/*
 * This file is generated by jOOQ.
*/
package org.ensembl.database.homo_sapiens_core.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.ensembl.database.homo_sapiens_core.HomoSapiensCore_89_37;
import org.ensembl.database.homo_sapiens_core.Keys;
import org.ensembl.database.homo_sapiens_core.tables.records.GeneAttribRecord;
import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;
import org.jooq.types.UShort;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GeneAttrib extends TableImpl<GeneAttribRecord> {

    private static final long serialVersionUID = -977780380;

    /**
     * The reference instance of <code>homo_sapiens_core_89_37.gene_attrib</code>
     */
    public static final GeneAttrib GENE_ATTRIB = new GeneAttrib();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GeneAttribRecord> getRecordType() {
        return GeneAttribRecord.class;
    }

    /**
     * The column <code>homo_sapiens_core_89_37.gene_attrib.gene_id</code>.
     */
    public final TableField<GeneAttribRecord, UInteger> GENE_ID = createField("gene_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGERUNSIGNED)), this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.gene_attrib.attrib_type_id</code>.
     */
    public final TableField<GeneAttribRecord, UShort> ATTRIB_TYPE_ID = createField("attrib_type_id", org.jooq.impl.SQLDataType.SMALLINTUNSIGNED.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.SMALLINTUNSIGNED)), this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.gene_attrib.value</code>.
     */
    public final TableField<GeneAttribRecord, String> VALUE = createField("value", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * Create a <code>homo_sapiens_core_89_37.gene_attrib</code> table reference
     */
    public GeneAttrib() {
        this("gene_attrib", null);
    }

    /**
     * Create an aliased <code>homo_sapiens_core_89_37.gene_attrib</code> table reference
     */
    public GeneAttrib(String alias) {
        this(alias, GENE_ATTRIB);
    }

    private GeneAttrib(String alias, Table<GeneAttribRecord> aliased) {
        this(alias, aliased, null);
    }

    private GeneAttrib(String alias, Table<GeneAttribRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return HomoSapiensCore_89_37.HOMO_SAPIENS_CORE_89_37;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<GeneAttribRecord>> getKeys() {
        return Arrays.<UniqueKey<GeneAttribRecord>>asList(Keys.KEY_GENE_ATTRIB_GENE_ATTRIBX);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GeneAttrib as(String alias) {
        return new GeneAttrib(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public GeneAttrib rename(String name) {
        return new GeneAttrib(name, null);
    }
}
