/*
 * This file is generated by jOOQ.
*/
package org.ensembl.database.homo_sapiens_core.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.ensembl.database.homo_sapiens_core.HomoSapiensCore_89_37;
import org.ensembl.database.homo_sapiens_core.Keys;
import org.ensembl.database.homo_sapiens_core.tables.records.KaryotypeRecord;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Karyotype extends TableImpl<KaryotypeRecord> {

    private static final long serialVersionUID = 1813310806;

    /**
     * The reference instance of <code>homo_sapiens_core_89_37.karyotype</code>
     */
    public static final Karyotype KARYOTYPE = new Karyotype();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<KaryotypeRecord> getRecordType() {
        return KaryotypeRecord.class;
    }

    /**
     * The column <code>homo_sapiens_core_89_37.karyotype.karyotype_id</code>.
     */
    public final TableField<KaryotypeRecord, UInteger> KARYOTYPE_ID = createField("karyotype_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.karyotype.seq_region_id</code>.
     */
    public final TableField<KaryotypeRecord, UInteger> SEQ_REGION_ID = createField("seq_region_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.karyotype.seq_region_start</code>.
     */
    public final TableField<KaryotypeRecord, UInteger> SEQ_REGION_START = createField("seq_region_start", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.karyotype.seq_region_end</code>.
     */
    public final TableField<KaryotypeRecord, UInteger> SEQ_REGION_END = createField("seq_region_end", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.karyotype.band</code>.
     */
    public final TableField<KaryotypeRecord, String> BAND = createField("band", org.jooq.impl.SQLDataType.VARCHAR.length(40), this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.karyotype.stain</code>.
     */
    public final TableField<KaryotypeRecord, String> STAIN = createField("stain", org.jooq.impl.SQLDataType.VARCHAR.length(40), this, "");

    /**
     * Create a <code>homo_sapiens_core_89_37.karyotype</code> table reference
     */
    public Karyotype() {
        this("karyotype", null);
    }

    /**
     * Create an aliased <code>homo_sapiens_core_89_37.karyotype</code> table reference
     */
    public Karyotype(String alias) {
        this(alias, KARYOTYPE);
    }

    private Karyotype(String alias, Table<KaryotypeRecord> aliased) {
        this(alias, aliased, null);
    }

    private Karyotype(String alias, Table<KaryotypeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return HomoSapiensCore_89_37.HOMO_SAPIENS_CORE_89_37;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<KaryotypeRecord, UInteger> getIdentity() {
        return Keys.IDENTITY_KARYOTYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<KaryotypeRecord> getPrimaryKey() {
        return Keys.KEY_KARYOTYPE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<KaryotypeRecord>> getKeys() {
        return Arrays.<UniqueKey<KaryotypeRecord>>asList(Keys.KEY_KARYOTYPE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Karyotype as(String alias) {
        return new Karyotype(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Karyotype rename(String name) {
        return new Karyotype(name, null);
    }
}
