/*
 * This file is generated by jOOQ.
*/
package org.ensembl.database.homo_sapiens_core.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.ensembl.database.homo_sapiens_core.HomoSapiensCore_89_37;
import org.ensembl.database.homo_sapiens_core.Keys;
import org.ensembl.database.homo_sapiens_core.tables.records.MapRecord;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Map extends TableImpl<MapRecord> {

    private static final long serialVersionUID = 1526935845;

    /**
     * The reference instance of <code>homo_sapiens_core_89_37.map</code>
     */
    public static final Map MAP = new Map();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MapRecord> getRecordType() {
        return MapRecord.class;
    }

    /**
     * The column <code>homo_sapiens_core_89_37.map.map_id</code>.
     */
    public final TableField<MapRecord, UInteger> MAP_ID = createField("map_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.map.map_name</code>.
     */
    public final TableField<MapRecord, String> MAP_NAME = createField("map_name", org.jooq.impl.SQLDataType.VARCHAR.length(30).nullable(false), this, "");

    /**
     * Create a <code>homo_sapiens_core_89_37.map</code> table reference
     */
    public Map() {
        this("map", null);
    }

    /**
     * Create an aliased <code>homo_sapiens_core_89_37.map</code> table reference
     */
    public Map(String alias) {
        this(alias, MAP);
    }

    private Map(String alias, Table<MapRecord> aliased) {
        this(alias, aliased, null);
    }

    private Map(String alias, Table<MapRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return HomoSapiensCore_89_37.HOMO_SAPIENS_CORE_89_37;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<MapRecord, UInteger> getIdentity() {
        return Keys.IDENTITY_MAP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<MapRecord> getPrimaryKey() {
        return Keys.KEY_MAP_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<MapRecord>> getKeys() {
        return Arrays.<UniqueKey<MapRecord>>asList(Keys.KEY_MAP_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Map as(String alias) {
        return new Map(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Map rename(String name) {
        return new Map(name, null);
    }
}
