/*
 * This file is generated by jOOQ.
*/
package org.ensembl.database.homo_sapiens_core.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.ensembl.database.homo_sapiens_core.HomoSapiensCore_89_37;
import org.ensembl.database.homo_sapiens_core.Keys;
import org.ensembl.database.homo_sapiens_core.tables.records.MarkerFeatureRecord;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;
import org.jooq.types.UShort;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MarkerFeature extends TableImpl<MarkerFeatureRecord> {

    private static final long serialVersionUID = -1439300821;

    /**
     * The reference instance of <code>homo_sapiens_core_89_37.marker_feature</code>
     */
    public static final MarkerFeature MARKER_FEATURE = new MarkerFeature();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MarkerFeatureRecord> getRecordType() {
        return MarkerFeatureRecord.class;
    }

    /**
     * The column <code>homo_sapiens_core_89_37.marker_feature.marker_feature_id</code>.
     */
    public final TableField<MarkerFeatureRecord, UInteger> MARKER_FEATURE_ID = createField("marker_feature_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.marker_feature.marker_id</code>.
     */
    public final TableField<MarkerFeatureRecord, UInteger> MARKER_ID = createField("marker_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.marker_feature.seq_region_id</code>.
     */
    public final TableField<MarkerFeatureRecord, UInteger> SEQ_REGION_ID = createField("seq_region_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.marker_feature.seq_region_start</code>.
     */
    public final TableField<MarkerFeatureRecord, UInteger> SEQ_REGION_START = createField("seq_region_start", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.marker_feature.seq_region_end</code>.
     */
    public final TableField<MarkerFeatureRecord, UInteger> SEQ_REGION_END = createField("seq_region_end", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.marker_feature.analysis_id</code>.
     */
    public final TableField<MarkerFeatureRecord, UShort> ANALYSIS_ID = createField("analysis_id", org.jooq.impl.SQLDataType.SMALLINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.marker_feature.map_weight</code>.
     */
    public final TableField<MarkerFeatureRecord, UInteger> MAP_WEIGHT = createField("map_weight", org.jooq.impl.SQLDataType.INTEGERUNSIGNED, this, "");

    /**
     * Create a <code>homo_sapiens_core_89_37.marker_feature</code> table reference
     */
    public MarkerFeature() {
        this("marker_feature", null);
    }

    /**
     * Create an aliased <code>homo_sapiens_core_89_37.marker_feature</code> table reference
     */
    public MarkerFeature(String alias) {
        this(alias, MARKER_FEATURE);
    }

    private MarkerFeature(String alias, Table<MarkerFeatureRecord> aliased) {
        this(alias, aliased, null);
    }

    private MarkerFeature(String alias, Table<MarkerFeatureRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return HomoSapiensCore_89_37.HOMO_SAPIENS_CORE_89_37;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<MarkerFeatureRecord, UInteger> getIdentity() {
        return Keys.IDENTITY_MARKER_FEATURE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<MarkerFeatureRecord> getPrimaryKey() {
        return Keys.KEY_MARKER_FEATURE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<MarkerFeatureRecord>> getKeys() {
        return Arrays.<UniqueKey<MarkerFeatureRecord>>asList(Keys.KEY_MARKER_FEATURE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MarkerFeature as(String alias) {
        return new MarkerFeature(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public MarkerFeature rename(String name) {
        return new MarkerFeature(name, null);
    }
}
