/*
 * This file is generated by jOOQ.
*/
package org.ensembl.database.homo_sapiens_core.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.ensembl.database.homo_sapiens_core.HomoSapiensCore_89_37;
import org.ensembl.database.homo_sapiens_core.Keys;
import org.ensembl.database.homo_sapiens_core.tables.records.MarkerMapLocationRecord;
import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MarkerMapLocation extends TableImpl<MarkerMapLocationRecord> {

    private static final long serialVersionUID = -1064304457;

    /**
     * The reference instance of <code>homo_sapiens_core_89_37.marker_map_location</code>
     */
    public static final MarkerMapLocation MARKER_MAP_LOCATION = new MarkerMapLocation();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MarkerMapLocationRecord> getRecordType() {
        return MarkerMapLocationRecord.class;
    }

    /**
     * The column <code>homo_sapiens_core_89_37.marker_map_location.marker_id</code>.
     */
    public final TableField<MarkerMapLocationRecord, UInteger> MARKER_ID = createField("marker_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.marker_map_location.map_id</code>.
     */
    public final TableField<MarkerMapLocationRecord, UInteger> MAP_ID = createField("map_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.marker_map_location.chromosome_name</code>.
     */
    public final TableField<MarkerMapLocationRecord, String> CHROMOSOME_NAME = createField("chromosome_name", org.jooq.impl.SQLDataType.VARCHAR.length(15).nullable(false), this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.marker_map_location.marker_synonym_id</code>.
     */
    public final TableField<MarkerMapLocationRecord, UInteger> MARKER_SYNONYM_ID = createField("marker_synonym_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.marker_map_location.position</code>.
     */
    public final TableField<MarkerMapLocationRecord, String> POSITION = createField("position", org.jooq.impl.SQLDataType.VARCHAR.length(15).nullable(false), this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.marker_map_location.lod_score</code>.
     */
    public final TableField<MarkerMapLocationRecord, Double> LOD_SCORE = createField("lod_score", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * Create a <code>homo_sapiens_core_89_37.marker_map_location</code> table reference
     */
    public MarkerMapLocation() {
        this("marker_map_location", null);
    }

    /**
     * Create an aliased <code>homo_sapiens_core_89_37.marker_map_location</code> table reference
     */
    public MarkerMapLocation(String alias) {
        this(alias, MARKER_MAP_LOCATION);
    }

    private MarkerMapLocation(String alias, Table<MarkerMapLocationRecord> aliased) {
        this(alias, aliased, null);
    }

    private MarkerMapLocation(String alias, Table<MarkerMapLocationRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return HomoSapiensCore_89_37.HOMO_SAPIENS_CORE_89_37;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<MarkerMapLocationRecord> getPrimaryKey() {
        return Keys.KEY_MARKER_MAP_LOCATION_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<MarkerMapLocationRecord>> getKeys() {
        return Arrays.<UniqueKey<MarkerMapLocationRecord>>asList(Keys.KEY_MARKER_MAP_LOCATION_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MarkerMapLocation as(String alias) {
        return new MarkerMapLocation(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public MarkerMapLocation rename(String name) {
        return new MarkerMapLocation(name, null);
    }
}
