/*
 * This file is generated by jOOQ.
*/
package org.ensembl.database.homo_sapiens_core.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.ensembl.database.homo_sapiens_core.HomoSapiensCore_89_37;
import org.ensembl.database.homo_sapiens_core.Keys;
import org.ensembl.database.homo_sapiens_core.enums.MarkerType;
import org.ensembl.database.homo_sapiens_core.tables.records.MarkerRecord;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Marker extends TableImpl<MarkerRecord> {

    private static final long serialVersionUID = -1976522761;

    /**
     * The reference instance of <code>homo_sapiens_core_89_37.marker</code>
     */
    public static final Marker MARKER = new Marker();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MarkerRecord> getRecordType() {
        return MarkerRecord.class;
    }

    /**
     * The column <code>homo_sapiens_core_89_37.marker.marker_id</code>.
     */
    public final TableField<MarkerRecord, UInteger> MARKER_ID = createField("marker_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.marker.display_marker_synonym_id</code>.
     */
    public final TableField<MarkerRecord, UInteger> DISPLAY_MARKER_SYNONYM_ID = createField("display_marker_synonym_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED, this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.marker.left_primer</code>.
     */
    public final TableField<MarkerRecord, String> LEFT_PRIMER = createField("left_primer", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.marker.right_primer</code>.
     */
    public final TableField<MarkerRecord, String> RIGHT_PRIMER = createField("right_primer", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.marker.min_primer_dist</code>.
     */
    public final TableField<MarkerRecord, UInteger> MIN_PRIMER_DIST = createField("min_primer_dist", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.marker.max_primer_dist</code>.
     */
    public final TableField<MarkerRecord, UInteger> MAX_PRIMER_DIST = createField("max_primer_dist", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.marker.priority</code>.
     */
    public final TableField<MarkerRecord, Integer> PRIORITY = createField("priority", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.marker.type</code>.
     */
    public final TableField<MarkerRecord, MarkerType> TYPE = createField("type", org.jooq.util.mysql.MySQLDataType.VARCHAR.asEnumDataType(org.ensembl.database.homo_sapiens_core.enums.MarkerType.class), this, "");

    /**
     * Create a <code>homo_sapiens_core_89_37.marker</code> table reference
     */
    public Marker() {
        this("marker", null);
    }

    /**
     * Create an aliased <code>homo_sapiens_core_89_37.marker</code> table reference
     */
    public Marker(String alias) {
        this(alias, MARKER);
    }

    private Marker(String alias, Table<MarkerRecord> aliased) {
        this(alias, aliased, null);
    }

    private Marker(String alias, Table<MarkerRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return HomoSapiensCore_89_37.HOMO_SAPIENS_CORE_89_37;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<MarkerRecord, UInteger> getIdentity() {
        return Keys.IDENTITY_MARKER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<MarkerRecord> getPrimaryKey() {
        return Keys.KEY_MARKER_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<MarkerRecord>> getKeys() {
        return Arrays.<UniqueKey<MarkerRecord>>asList(Keys.KEY_MARKER_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Marker as(String alias) {
        return new Marker(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Marker rename(String name) {
        return new Marker(name, null);
    }
}
