/*
 * This file is generated by jOOQ.
*/
package org.ensembl.database.homo_sapiens_core.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.ensembl.database.homo_sapiens_core.HomoSapiensCore_89_37;
import org.ensembl.database.homo_sapiens_core.Keys;
import org.ensembl.database.homo_sapiens_core.tables.records.OntologyXrefRecord;
import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OntologyXref extends TableImpl<OntologyXrefRecord> {

    private static final long serialVersionUID = 1522146904;

    /**
     * The reference instance of <code>homo_sapiens_core_89_37.ontology_xref</code>
     */
    public static final OntologyXref ONTOLOGY_XREF = new OntologyXref();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OntologyXrefRecord> getRecordType() {
        return OntologyXrefRecord.class;
    }

    /**
     * The column <code>homo_sapiens_core_89_37.ontology_xref.object_xref_id</code>.
     */
    public final TableField<OntologyXrefRecord, UInteger> OBJECT_XREF_ID = createField("object_xref_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGERUNSIGNED)), this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.ontology_xref.source_xref_id</code>.
     */
    public final TableField<OntologyXrefRecord, UInteger> SOURCE_XREF_ID = createField("source_xref_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED, this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.ontology_xref.linkage_type</code>.
     */
    public final TableField<OntologyXrefRecord, String> LINKAGE_TYPE = createField("linkage_type", org.jooq.impl.SQLDataType.VARCHAR.length(3), this, "");

    /**
     * Create a <code>homo_sapiens_core_89_37.ontology_xref</code> table reference
     */
    public OntologyXref() {
        this("ontology_xref", null);
    }

    /**
     * Create an aliased <code>homo_sapiens_core_89_37.ontology_xref</code> table reference
     */
    public OntologyXref(String alias) {
        this(alias, ONTOLOGY_XREF);
    }

    private OntologyXref(String alias, Table<OntologyXrefRecord> aliased) {
        this(alias, aliased, null);
    }

    private OntologyXref(String alias, Table<OntologyXrefRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return HomoSapiensCore_89_37.HOMO_SAPIENS_CORE_89_37;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<OntologyXrefRecord>> getKeys() {
        return Arrays.<UniqueKey<OntologyXrefRecord>>asList(Keys.KEY_ONTOLOGY_XREF_OBJECT_SOURCE_TYPE_IDX);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OntologyXref as(String alias) {
        return new OntologyXref(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public OntologyXref rename(String name) {
        return new OntologyXref(name, null);
    }
}
