/*
 * This file is generated by jOOQ.
*/
package org.ensembl.database.homo_sapiens_core.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.ensembl.database.homo_sapiens_core.HomoSapiensCore_89_37;
import org.ensembl.database.homo_sapiens_core.Keys;
import org.ensembl.database.homo_sapiens_core.tables.records.PeptideArchiveRecord;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PeptideArchive extends TableImpl<PeptideArchiveRecord> {

    private static final long serialVersionUID = 584147613;

    /**
     * The reference instance of <code>homo_sapiens_core_89_37.peptide_archive</code>
     */
    public static final PeptideArchive PEPTIDE_ARCHIVE = new PeptideArchive();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PeptideArchiveRecord> getRecordType() {
        return PeptideArchiveRecord.class;
    }

    /**
     * The column <code>homo_sapiens_core_89_37.peptide_archive.peptide_archive_id</code>.
     */
    public final TableField<PeptideArchiveRecord, UInteger> PEPTIDE_ARCHIVE_ID = createField("peptide_archive_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.peptide_archive.md5_checksum</code>.
     */
    public final TableField<PeptideArchiveRecord, String> MD5_CHECKSUM = createField("md5_checksum", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.peptide_archive.peptide_seq</code>.
     */
    public final TableField<PeptideArchiveRecord, String> PEPTIDE_SEQ = createField("peptide_seq", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * Create a <code>homo_sapiens_core_89_37.peptide_archive</code> table reference
     */
    public PeptideArchive() {
        this("peptide_archive", null);
    }

    /**
     * Create an aliased <code>homo_sapiens_core_89_37.peptide_archive</code> table reference
     */
    public PeptideArchive(String alias) {
        this(alias, PEPTIDE_ARCHIVE);
    }

    private PeptideArchive(String alias, Table<PeptideArchiveRecord> aliased) {
        this(alias, aliased, null);
    }

    private PeptideArchive(String alias, Table<PeptideArchiveRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return HomoSapiensCore_89_37.HOMO_SAPIENS_CORE_89_37;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<PeptideArchiveRecord, UInteger> getIdentity() {
        return Keys.IDENTITY_PEPTIDE_ARCHIVE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<PeptideArchiveRecord> getPrimaryKey() {
        return Keys.KEY_PEPTIDE_ARCHIVE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<PeptideArchiveRecord>> getKeys() {
        return Arrays.<UniqueKey<PeptideArchiveRecord>>asList(Keys.KEY_PEPTIDE_ARCHIVE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PeptideArchive as(String alias) {
        return new PeptideArchive(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public PeptideArchive rename(String name) {
        return new PeptideArchive(name, null);
    }
}
