/*
 * This file is generated by jOOQ.
*/
package org.ensembl.database.homo_sapiens_core.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.ensembl.database.homo_sapiens_core.HomoSapiensCore_89_37;
import org.ensembl.database.homo_sapiens_core.Keys;
import org.ensembl.database.homo_sapiens_core.tables.records.RepeatFeatureRecord;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;
import org.jooq.types.UShort;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RepeatFeature extends TableImpl<RepeatFeatureRecord> {

    private static final long serialVersionUID = 1654552755;

    /**
     * The reference instance of <code>homo_sapiens_core_89_37.repeat_feature</code>
     */
    public static final RepeatFeature REPEAT_FEATURE = new RepeatFeature();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RepeatFeatureRecord> getRecordType() {
        return RepeatFeatureRecord.class;
    }

    /**
     * The column <code>homo_sapiens_core_89_37.repeat_feature.repeat_feature_id</code>.
     */
    public final TableField<RepeatFeatureRecord, UInteger> REPEAT_FEATURE_ID = createField("repeat_feature_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.repeat_feature.seq_region_id</code>.
     */
    public final TableField<RepeatFeatureRecord, UInteger> SEQ_REGION_ID = createField("seq_region_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.repeat_feature.seq_region_start</code>.
     */
    public final TableField<RepeatFeatureRecord, UInteger> SEQ_REGION_START = createField("seq_region_start", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.repeat_feature.seq_region_end</code>.
     */
    public final TableField<RepeatFeatureRecord, UInteger> SEQ_REGION_END = createField("seq_region_end", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.repeat_feature.seq_region_strand</code>.
     */
    public final TableField<RepeatFeatureRecord, Byte> SEQ_REGION_STRAND = createField("seq_region_strand", org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("1", org.jooq.impl.SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.repeat_feature.repeat_start</code>.
     */
    public final TableField<RepeatFeatureRecord, Integer> REPEAT_START = createField("repeat_start", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.repeat_feature.repeat_end</code>.
     */
    public final TableField<RepeatFeatureRecord, Integer> REPEAT_END = createField("repeat_end", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.repeat_feature.repeat_consensus_id</code>.
     */
    public final TableField<RepeatFeatureRecord, UInteger> REPEAT_CONSENSUS_ID = createField("repeat_consensus_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.repeat_feature.analysis_id</code>.
     */
    public final TableField<RepeatFeatureRecord, UShort> ANALYSIS_ID = createField("analysis_id", org.jooq.impl.SQLDataType.SMALLINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.repeat_feature.score</code>.
     */
    public final TableField<RepeatFeatureRecord, Double> SCORE = createField("score", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * Create a <code>homo_sapiens_core_89_37.repeat_feature</code> table reference
     */
    public RepeatFeature() {
        this("repeat_feature", null);
    }

    /**
     * Create an aliased <code>homo_sapiens_core_89_37.repeat_feature</code> table reference
     */
    public RepeatFeature(String alias) {
        this(alias, REPEAT_FEATURE);
    }

    private RepeatFeature(String alias, Table<RepeatFeatureRecord> aliased) {
        this(alias, aliased, null);
    }

    private RepeatFeature(String alias, Table<RepeatFeatureRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return HomoSapiensCore_89_37.HOMO_SAPIENS_CORE_89_37;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<RepeatFeatureRecord, UInteger> getIdentity() {
        return Keys.IDENTITY_REPEAT_FEATURE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<RepeatFeatureRecord> getPrimaryKey() {
        return Keys.KEY_REPEAT_FEATURE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<RepeatFeatureRecord>> getKeys() {
        return Arrays.<UniqueKey<RepeatFeatureRecord>>asList(Keys.KEY_REPEAT_FEATURE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RepeatFeature as(String alias) {
        return new RepeatFeature(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public RepeatFeature rename(String name) {
        return new RepeatFeature(name, null);
    }
}
