/*
 * This file is generated by jOOQ.
*/
package org.ensembl.database.homo_sapiens_core.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.ensembl.database.homo_sapiens_core.HomoSapiensCore_89_37;
import org.ensembl.database.homo_sapiens_core.Keys;
import org.ensembl.database.homo_sapiens_core.tables.records.SeqRegionAttribRecord;
import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;
import org.jooq.types.UShort;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SeqRegionAttrib extends TableImpl<SeqRegionAttribRecord> {

    private static final long serialVersionUID = 1090143362;

    /**
     * The reference instance of <code>homo_sapiens_core_89_37.seq_region_attrib</code>
     */
    public static final SeqRegionAttrib SEQ_REGION_ATTRIB = new SeqRegionAttrib();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SeqRegionAttribRecord> getRecordType() {
        return SeqRegionAttribRecord.class;
    }

    /**
     * The column <code>homo_sapiens_core_89_37.seq_region_attrib.seq_region_id</code>.
     */
    public final TableField<SeqRegionAttribRecord, UInteger> SEQ_REGION_ID = createField("seq_region_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGERUNSIGNED)), this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.seq_region_attrib.attrib_type_id</code>.
     */
    public final TableField<SeqRegionAttribRecord, UShort> ATTRIB_TYPE_ID = createField("attrib_type_id", org.jooq.impl.SQLDataType.SMALLINTUNSIGNED.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.SMALLINTUNSIGNED)), this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.seq_region_attrib.value</code>.
     */
    public final TableField<SeqRegionAttribRecord, String> VALUE = createField("value", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * Create a <code>homo_sapiens_core_89_37.seq_region_attrib</code> table reference
     */
    public SeqRegionAttrib() {
        this("seq_region_attrib", null);
    }

    /**
     * Create an aliased <code>homo_sapiens_core_89_37.seq_region_attrib</code> table reference
     */
    public SeqRegionAttrib(String alias) {
        this(alias, SEQ_REGION_ATTRIB);
    }

    private SeqRegionAttrib(String alias, Table<SeqRegionAttribRecord> aliased) {
        this(alias, aliased, null);
    }

    private SeqRegionAttrib(String alias, Table<SeqRegionAttribRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return HomoSapiensCore_89_37.HOMO_SAPIENS_CORE_89_37;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<SeqRegionAttribRecord>> getKeys() {
        return Arrays.<UniqueKey<SeqRegionAttribRecord>>asList(Keys.KEY_SEQ_REGION_ATTRIB_REGION_ATTRIBX);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SeqRegionAttrib as(String alias) {
        return new SeqRegionAttrib(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SeqRegionAttrib rename(String name) {
        return new SeqRegionAttrib(name, null);
    }
}
