/*
 * This file is generated by jOOQ.
*/
package org.ensembl.database.homo_sapiens_core.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.ensembl.database.homo_sapiens_core.HomoSapiensCore_89_37;
import org.ensembl.database.homo_sapiens_core.Keys;
import org.ensembl.database.homo_sapiens_core.enums.StableIdEventType;
import org.ensembl.database.homo_sapiens_core.tables.records.StableIdEventRecord;
import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StableIdEvent extends TableImpl<StableIdEventRecord> {

    private static final long serialVersionUID = -977823228;

    /**
     * The reference instance of <code>homo_sapiens_core_89_37.stable_id_event</code>
     */
    public static final StableIdEvent STABLE_ID_EVENT = new StableIdEvent();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<StableIdEventRecord> getRecordType() {
        return StableIdEventRecord.class;
    }

    /**
     * The column <code>homo_sapiens_core_89_37.stable_id_event.old_stable_id</code>.
     */
    public final TableField<StableIdEventRecord, String> OLD_STABLE_ID = createField("old_stable_id", org.jooq.impl.SQLDataType.VARCHAR.length(128), this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.stable_id_event.old_version</code>.
     */
    public final TableField<StableIdEventRecord, Short> OLD_VERSION = createField("old_version", org.jooq.impl.SQLDataType.SMALLINT, this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.stable_id_event.new_stable_id</code>.
     */
    public final TableField<StableIdEventRecord, String> NEW_STABLE_ID = createField("new_stable_id", org.jooq.impl.SQLDataType.VARCHAR.length(128), this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.stable_id_event.new_version</code>.
     */
    public final TableField<StableIdEventRecord, Short> NEW_VERSION = createField("new_version", org.jooq.impl.SQLDataType.SMALLINT, this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.stable_id_event.mapping_session_id</code>.
     */
    public final TableField<StableIdEventRecord, UInteger> MAPPING_SESSION_ID = createField("mapping_session_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGERUNSIGNED)), this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.stable_id_event.type</code>.
     */
    public final TableField<StableIdEventRecord, StableIdEventType> TYPE = createField("type", org.jooq.util.mysql.MySQLDataType.VARCHAR.asEnumDataType(org.ensembl.database.homo_sapiens_core.enums.StableIdEventType.class), this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.stable_id_event.score</code>.
     */
    public final TableField<StableIdEventRecord, Double> SCORE = createField("score", org.jooq.impl.SQLDataType.FLOAT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.FLOAT)), this, "");

    /**
     * Create a <code>homo_sapiens_core_89_37.stable_id_event</code> table reference
     */
    public StableIdEvent() {
        this("stable_id_event", null);
    }

    /**
     * Create an aliased <code>homo_sapiens_core_89_37.stable_id_event</code> table reference
     */
    public StableIdEvent(String alias) {
        this(alias, STABLE_ID_EVENT);
    }

    private StableIdEvent(String alias, Table<StableIdEventRecord> aliased) {
        this(alias, aliased, null);
    }

    private StableIdEvent(String alias, Table<StableIdEventRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return HomoSapiensCore_89_37.HOMO_SAPIENS_CORE_89_37;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<StableIdEventRecord>> getKeys() {
        return Arrays.<UniqueKey<StableIdEventRecord>>asList(Keys.KEY_STABLE_ID_EVENT_UNI_IDX);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StableIdEvent as(String alias) {
        return new StableIdEvent(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public StableIdEvent rename(String name) {
        return new StableIdEvent(name, null);
    }
}
