/*
 * This file is generated by jOOQ.
*/
package org.ensembl.database.homo_sapiens_core.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.ensembl.database.homo_sapiens_core.HomoSapiensCore_89_37;
import org.ensembl.database.homo_sapiens_core.Keys;
import org.ensembl.database.homo_sapiens_core.enums.TranscriptSupportingFeatureFeatureType;
import org.ensembl.database.homo_sapiens_core.tables.records.TranscriptSupportingFeatureRecord;
import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TranscriptSupportingFeature extends TableImpl<TranscriptSupportingFeatureRecord> {

    private static final long serialVersionUID = -473818652;

    /**
     * The reference instance of <code>homo_sapiens_core_89_37.transcript_supporting_feature</code>
     */
    public static final TranscriptSupportingFeature TRANSCRIPT_SUPPORTING_FEATURE = new TranscriptSupportingFeature();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TranscriptSupportingFeatureRecord> getRecordType() {
        return TranscriptSupportingFeatureRecord.class;
    }

    /**
     * The column <code>homo_sapiens_core_89_37.transcript_supporting_feature.transcript_id</code>.
     */
    public final TableField<TranscriptSupportingFeatureRecord, UInteger> TRANSCRIPT_ID = createField("transcript_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGERUNSIGNED)), this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.transcript_supporting_feature.feature_type</code>.
     */
    public final TableField<TranscriptSupportingFeatureRecord, TranscriptSupportingFeatureFeatureType> FEATURE_TYPE = createField("feature_type", org.jooq.util.mysql.MySQLDataType.VARCHAR.asEnumDataType(org.ensembl.database.homo_sapiens_core.enums.TranscriptSupportingFeatureFeatureType.class), this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.transcript_supporting_feature.feature_id</code>.
     */
    public final TableField<TranscriptSupportingFeatureRecord, UInteger> FEATURE_ID = createField("feature_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGERUNSIGNED)), this, "");

    /**
     * Create a <code>homo_sapiens_core_89_37.transcript_supporting_feature</code> table reference
     */
    public TranscriptSupportingFeature() {
        this("transcript_supporting_feature", null);
    }

    /**
     * Create an aliased <code>homo_sapiens_core_89_37.transcript_supporting_feature</code> table reference
     */
    public TranscriptSupportingFeature(String alias) {
        this(alias, TRANSCRIPT_SUPPORTING_FEATURE);
    }

    private TranscriptSupportingFeature(String alias, Table<TranscriptSupportingFeatureRecord> aliased) {
        this(alias, aliased, null);
    }

    private TranscriptSupportingFeature(String alias, Table<TranscriptSupportingFeatureRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return HomoSapiensCore_89_37.HOMO_SAPIENS_CORE_89_37;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TranscriptSupportingFeatureRecord>> getKeys() {
        return Arrays.<UniqueKey<TranscriptSupportingFeatureRecord>>asList(Keys.KEY_TRANSCRIPT_SUPPORTING_FEATURE_ALL_IDX);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TranscriptSupportingFeature as(String alias) {
        return new TranscriptSupportingFeature(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TranscriptSupportingFeature rename(String name) {
        return new TranscriptSupportingFeature(name, null);
    }
}
