/*
 * This file is generated by jOOQ.
*/
package org.ensembl.database.homo_sapiens_core.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.ensembl.database.homo_sapiens_core.HomoSapiensCore_89_37;
import org.ensembl.database.homo_sapiens_core.Keys;
import org.ensembl.database.homo_sapiens_core.tables.records.TranslationRecord;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;
import org.jooq.types.UShort;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Translation extends TableImpl<TranslationRecord> {

    private static final long serialVersionUID = -89279861;

    /**
     * The reference instance of <code>homo_sapiens_core_89_37.translation</code>
     */
    public static final Translation TRANSLATION = new Translation();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TranslationRecord> getRecordType() {
        return TranslationRecord.class;
    }

    /**
     * The column <code>homo_sapiens_core_89_37.translation.translation_id</code>.
     */
    public final TableField<TranslationRecord, UInteger> TRANSLATION_ID = createField("translation_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.translation.transcript_id</code>.
     */
    public final TableField<TranslationRecord, UInteger> TRANSCRIPT_ID = createField("transcript_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.translation.seq_start</code>.
     */
    public final TableField<TranslationRecord, Integer> SEQ_START = createField("seq_start", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.translation.start_exon_id</code>.
     */
    public final TableField<TranslationRecord, UInteger> START_EXON_ID = createField("start_exon_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.translation.seq_end</code>.
     */
    public final TableField<TranslationRecord, Integer> SEQ_END = createField("seq_end", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.translation.end_exon_id</code>.
     */
    public final TableField<TranslationRecord, UInteger> END_EXON_ID = createField("end_exon_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.translation.stable_id</code>.
     */
    public final TableField<TranslationRecord, String> STABLE_ID = createField("stable_id", org.jooq.impl.SQLDataType.VARCHAR.length(128), this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.translation.version</code>.
     */
    public final TableField<TranslationRecord, UShort> VERSION = createField("version", org.jooq.impl.SQLDataType.SMALLINTUNSIGNED, this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.translation.created_date</code>.
     */
    public final TableField<TranslationRecord, Timestamp> CREATED_DATE = createField("created_date", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.translation.modified_date</code>.
     */
    public final TableField<TranslationRecord, Timestamp> MODIFIED_DATE = createField("modified_date", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * Create a <code>homo_sapiens_core_89_37.translation</code> table reference
     */
    public Translation() {
        this("translation", null);
    }

    /**
     * Create an aliased <code>homo_sapiens_core_89_37.translation</code> table reference
     */
    public Translation(String alias) {
        this(alias, TRANSLATION);
    }

    private Translation(String alias, Table<TranslationRecord> aliased) {
        this(alias, aliased, null);
    }

    private Translation(String alias, Table<TranslationRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return HomoSapiensCore_89_37.HOMO_SAPIENS_CORE_89_37;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<TranslationRecord, UInteger> getIdentity() {
        return Keys.IDENTITY_TRANSLATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TranslationRecord> getPrimaryKey() {
        return Keys.KEY_TRANSLATION_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TranslationRecord>> getKeys() {
        return Arrays.<UniqueKey<TranslationRecord>>asList(Keys.KEY_TRANSLATION_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Translation as(String alias) {
        return new Translation(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Translation rename(String name) {
        return new Translation(name, null);
    }
}
