/*
 * This file is generated by jOOQ.
*/
package org.ensembl.database.homo_sapiens_core.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.ensembl.database.homo_sapiens_core.HomoSapiensCore_89_37;
import org.ensembl.database.homo_sapiens_core.Keys;
import org.ensembl.database.homo_sapiens_core.tables.records.TranscriptAttribRecord;
import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;
import org.jooq.types.UShort;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TranscriptAttrib extends TableImpl<TranscriptAttribRecord> {

    private static final long serialVersionUID = -774574876;

    /**
     * The reference instance of <code>homo_sapiens_core_89_37.transcript_attrib</code>
     */
    public static final TranscriptAttrib TRANSCRIPT_ATTRIB = new TranscriptAttrib();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TranscriptAttribRecord> getRecordType() {
        return TranscriptAttribRecord.class;
    }

    /**
     * The column <code>homo_sapiens_core_89_37.transcript_attrib.transcript_id</code>.
     */
    public final TableField<TranscriptAttribRecord, UInteger> TRANSCRIPT_ID = createField("transcript_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGERUNSIGNED)), this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.transcript_attrib.attrib_type_id</code>.
     */
    public final TableField<TranscriptAttribRecord, UShort> ATTRIB_TYPE_ID = createField("attrib_type_id", org.jooq.impl.SQLDataType.SMALLINTUNSIGNED.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.SMALLINTUNSIGNED)), this, "");

    /**
     * The column <code>homo_sapiens_core_89_37.transcript_attrib.value</code>.
     */
    public final TableField<TranscriptAttribRecord, String> VALUE = createField("value", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * Create a <code>homo_sapiens_core_89_37.transcript_attrib</code> table reference
     */
    public TranscriptAttrib() {
        this("transcript_attrib", null);
    }

    /**
     * Create an aliased <code>homo_sapiens_core_89_37.transcript_attrib</code> table reference
     */
    public TranscriptAttrib(String alias) {
        this(alias, TRANSCRIPT_ATTRIB);
    }

    private TranscriptAttrib(String alias, Table<TranscriptAttribRecord> aliased) {
        this(alias, aliased, null);
    }

    private TranscriptAttrib(String alias, Table<TranscriptAttribRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return HomoSapiensCore_89_37.HOMO_SAPIENS_CORE_89_37;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TranscriptAttribRecord>> getKeys() {
        return Arrays.<UniqueKey<TranscriptAttribRecord>>asList(Keys.KEY_TRANSCRIPT_ATTRIB_TRANSCRIPT_ATTRIBX);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TranscriptAttrib as(String alias) {
        return new TranscriptAttrib(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TranscriptAttrib rename(String name) {
        return new TranscriptAttrib(name, null);
    }
}
