package com.hartwig.hmftools.common.serve.datamodel.characteristic;

public enum TumorCharacteristicAnnotation {
    MICROSATELLITE_UNSTABLE,
    MICROSATELLITE_STABLE,
    HIGH_TUMOR_MUTATIONAL_LOAD,
    LOW_TUMOR_MUTATIONAL_LOAD,
    HIGH_TUMOR_MUTATIONAL_BURDEN,
    LOW_TUMOR_MUTATIONAL_BURDEN,
    HOMOLOGOUS_RECOMBINATION_DEFICIENT,
    HPV_POSITIVE,
    EBV_POSITIVE
}