ALTER TABLE structuralVariant
    MODIFY endChromosome varchar(255),
    MODIFY endPosition int,
    MODIFY endOrientation tinyint,
    MODIFY endHomologySequence varchar(255),
    ADD imprecise BOOLEAN NOT NULL,
    ADD qualScore DOUBLE PRECISION,
    ADD event varchar(255),
    ADD startTumourVariantFragmentCount int,
    ADD startTumourReferenceFragmentCount int,
    ADD startNormalVariantFragmentCount int,
    ADD startNormalReferenceFragmentCount int,
    ADD endTumourVariantFragmentCount int,
    ADD endTumourReferenceFragmentCount int,
    ADD endNormalVariantFragmentCount int,
    ADD endNormalReferenceFragmentCount int,
    ADD startIntervalOffsetStart int,
    ADD startIntervalOffsetEnd int,
    ADD endIntervalOffsetStart int,
    ADD endIntervalOffsetEnd int,
    ADD inexactHomologyOffsetStart int,
    ADD inexactHomologyOffsetEnd int,
    ADD startLinkedBy varchar(512),
    ADD endLinkedBy varchar(512),
    ADD vcfId varchar(255),
    ADD recovered BOOLEAN NOT NULL;

ALTER TABLE structuralVariant
    ADD startRefContext varchar(255),
    ADD endRefContext varchar(255);
