steps:
  - id: 'Fetch token for github'
    name: gcr.io/cloud-builders/gcloud
    entrypoint: 'bash'
    args: [ '-c', "gcloud secrets versions access latest --secret=hmftools-github-private-key --format='get(payload.data)' | tr '_-' '/+' | base64 -d > /workspace/github.key" ]
  - id: 'Fetch password for Dockerhub'
    name: gcr.io/cloud-builders/gcloud
    entrypoint: 'bash'
    args: [ '-c', "gcloud secrets versions access latest --secret=hmftools-dockerhub-password --format='get(payload.data)' | tr '_-' '/+' | base64 -d > /workspace/dockerhub.password" ]
  - id: 'Tag, release, build'
    name: 'europe-west4-docker.pkg.dev/hmf-build/hmf-docker/jdk-mvn-python'
    entrypoint: 'python3'
    args: ['hmftools-build.py', '$TAG_NAME', '/workspace/github.key', '${_GITHUB_CLIENT_ID}', '${_GITHUB_INSTALLATION_ID}']
  - id: 'Publish Docker image'
    name: 'europe-west4-docker.pkg.dev/hmf-build/docker-tag'
    entrypoint: sh
    args: ['/workspace/docker.sh']
logsBucket: 'gs://hmf-build-logs'
timeout: 1800s
images:
  - 'europe-west4-docker.pkg.dev/hmf-build/hmf-docker/jdk-mvn-python'
