/*
 * This file is generated by jOOQ.
*/
package org.ensembl.database.homo_sapiens_core;


import javax.annotation.Generated;

import org.ensembl.database.homo_sapiens_core.tables.AltAllele;
import org.ensembl.database.homo_sapiens_core.tables.AltAlleleAttrib;
import org.ensembl.database.homo_sapiens_core.tables.AltAlleleGroup;
import org.ensembl.database.homo_sapiens_core.tables.Analysis;
import org.ensembl.database.homo_sapiens_core.tables.AnalysisDescription;
import org.ensembl.database.homo_sapiens_core.tables.Assembly;
import org.ensembl.database.homo_sapiens_core.tables.AssemblyException;
import org.ensembl.database.homo_sapiens_core.tables.AssociatedGroup;
import org.ensembl.database.homo_sapiens_core.tables.AssociatedXref;
import org.ensembl.database.homo_sapiens_core.tables.AttribType;
import org.ensembl.database.homo_sapiens_core.tables.CoordSystem;
import org.ensembl.database.homo_sapiens_core.tables.DataFile;
import org.ensembl.database.homo_sapiens_core.tables.DensityFeature;
import org.ensembl.database.homo_sapiens_core.tables.DensityType;
import org.ensembl.database.homo_sapiens_core.tables.DependentXref;
import org.ensembl.database.homo_sapiens_core.tables.Ditag;
import org.ensembl.database.homo_sapiens_core.tables.DitagFeature;
import org.ensembl.database.homo_sapiens_core.tables.Dna;
import org.ensembl.database.homo_sapiens_core.tables.DnaAlignFeature;
import org.ensembl.database.homo_sapiens_core.tables.DnaAlignFeatureAttrib;
import org.ensembl.database.homo_sapiens_core.tables.Exon;
import org.ensembl.database.homo_sapiens_core.tables.ExonTranscript;
import org.ensembl.database.homo_sapiens_core.tables.ExternalDb;
import org.ensembl.database.homo_sapiens_core.tables.ExternalSynonym;
import org.ensembl.database.homo_sapiens_core.tables.Gene;
import org.ensembl.database.homo_sapiens_core.tables.GeneArchive;
import org.ensembl.database.homo_sapiens_core.tables.GeneAttrib;
import org.ensembl.database.homo_sapiens_core.tables.GenomeStatistics;
import org.ensembl.database.homo_sapiens_core.tables.IdentityXref;
import org.ensembl.database.homo_sapiens_core.tables.Interpro;
import org.ensembl.database.homo_sapiens_core.tables.IntronSupportingEvidence;
import org.ensembl.database.homo_sapiens_core.tables.Karyotype;
import org.ensembl.database.homo_sapiens_core.tables.Map;
import org.ensembl.database.homo_sapiens_core.tables.MappingSession;
import org.ensembl.database.homo_sapiens_core.tables.MappingSet;
import org.ensembl.database.homo_sapiens_core.tables.Marker;
import org.ensembl.database.homo_sapiens_core.tables.MarkerFeature;
import org.ensembl.database.homo_sapiens_core.tables.MarkerMapLocation;
import org.ensembl.database.homo_sapiens_core.tables.MarkerSynonym;
import org.ensembl.database.homo_sapiens_core.tables.Meta;
import org.ensembl.database.homo_sapiens_core.tables.MetaCoord;
import org.ensembl.database.homo_sapiens_core.tables.MiscAttrib;
import org.ensembl.database.homo_sapiens_core.tables.MiscFeature;
import org.ensembl.database.homo_sapiens_core.tables.MiscFeatureMiscSet;
import org.ensembl.database.homo_sapiens_core.tables.MiscSet;
import org.ensembl.database.homo_sapiens_core.tables.ObjectXref;
import org.ensembl.database.homo_sapiens_core.tables.OntologyXref;
import org.ensembl.database.homo_sapiens_core.tables.Operon;
import org.ensembl.database.homo_sapiens_core.tables.OperonTranscript;
import org.ensembl.database.homo_sapiens_core.tables.OperonTranscriptGene;
import org.ensembl.database.homo_sapiens_core.tables.PeptideArchive;
import org.ensembl.database.homo_sapiens_core.tables.PredictionExon;
import org.ensembl.database.homo_sapiens_core.tables.PredictionTranscript;
import org.ensembl.database.homo_sapiens_core.tables.ProteinAlignFeature;
import org.ensembl.database.homo_sapiens_core.tables.ProteinFeature;
import org.ensembl.database.homo_sapiens_core.tables.RepeatConsensus;
import org.ensembl.database.homo_sapiens_core.tables.RepeatFeature;
import org.ensembl.database.homo_sapiens_core.tables.SeqRegion;
import org.ensembl.database.homo_sapiens_core.tables.SeqRegionAttrib;
import org.ensembl.database.homo_sapiens_core.tables.SeqRegionMapping;
import org.ensembl.database.homo_sapiens_core.tables.SeqRegionSynonym;
import org.ensembl.database.homo_sapiens_core.tables.SimpleFeature;
import org.ensembl.database.homo_sapiens_core.tables.StableIdEvent;
import org.ensembl.database.homo_sapiens_core.tables.SupportingFeature;
import org.ensembl.database.homo_sapiens_core.tables.Transcript;
import org.ensembl.database.homo_sapiens_core.tables.TranscriptAttrib;
import org.ensembl.database.homo_sapiens_core.tables.TranscriptIntronSupportingEvidence;
import org.ensembl.database.homo_sapiens_core.tables.TranscriptSupportingFeature;
import org.ensembl.database.homo_sapiens_core.tables.Translation;
import org.ensembl.database.homo_sapiens_core.tables.TranslationAttrib;
import org.ensembl.database.homo_sapiens_core.tables.UnmappedObject;
import org.ensembl.database.homo_sapiens_core.tables.UnmappedReason;
import org.ensembl.database.homo_sapiens_core.tables.Xref;


/**
 * Convenience access to all tables in homo_sapiens_core_89_37
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>homo_sapiens_core_89_37.alt_allele</code>.
     */
    public static final AltAllele ALT_ALLELE = org.ensembl.database.homo_sapiens_core.tables.AltAllele.ALT_ALLELE;

    /**
     * The table <code>homo_sapiens_core_89_37.alt_allele_attrib</code>.
     */
    public static final AltAlleleAttrib ALT_ALLELE_ATTRIB = org.ensembl.database.homo_sapiens_core.tables.AltAlleleAttrib.ALT_ALLELE_ATTRIB;

    /**
     * The table <code>homo_sapiens_core_89_37.alt_allele_group</code>.
     */
    public static final AltAlleleGroup ALT_ALLELE_GROUP = org.ensembl.database.homo_sapiens_core.tables.AltAlleleGroup.ALT_ALLELE_GROUP;

    /**
     * The table <code>homo_sapiens_core_89_37.analysis</code>.
     */
    public static final Analysis ANALYSIS = org.ensembl.database.homo_sapiens_core.tables.Analysis.ANALYSIS;

    /**
     * The table <code>homo_sapiens_core_89_37.analysis_description</code>.
     */
    public static final AnalysisDescription ANALYSIS_DESCRIPTION = org.ensembl.database.homo_sapiens_core.tables.AnalysisDescription.ANALYSIS_DESCRIPTION;

    /**
     * The table <code>homo_sapiens_core_89_37.assembly</code>.
     */
    public static final Assembly ASSEMBLY = org.ensembl.database.homo_sapiens_core.tables.Assembly.ASSEMBLY;

    /**
     * The table <code>homo_sapiens_core_89_37.assembly_exception</code>.
     */
    public static final AssemblyException ASSEMBLY_EXCEPTION = org.ensembl.database.homo_sapiens_core.tables.AssemblyException.ASSEMBLY_EXCEPTION;

    /**
     * The table <code>homo_sapiens_core_89_37.associated_group</code>.
     */
    public static final AssociatedGroup ASSOCIATED_GROUP = org.ensembl.database.homo_sapiens_core.tables.AssociatedGroup.ASSOCIATED_GROUP;

    /**
     * The table <code>homo_sapiens_core_89_37.associated_xref</code>.
     */
    public static final AssociatedXref ASSOCIATED_XREF = org.ensembl.database.homo_sapiens_core.tables.AssociatedXref.ASSOCIATED_XREF;

    /**
     * The table <code>homo_sapiens_core_89_37.attrib_type</code>.
     */
    public static final AttribType ATTRIB_TYPE = org.ensembl.database.homo_sapiens_core.tables.AttribType.ATTRIB_TYPE;

    /**
     * The table <code>homo_sapiens_core_89_37.coord_system</code>.
     */
    public static final CoordSystem COORD_SYSTEM = org.ensembl.database.homo_sapiens_core.tables.CoordSystem.COORD_SYSTEM;

    /**
     * The table <code>homo_sapiens_core_89_37.data_file</code>.
     */
    public static final DataFile DATA_FILE = org.ensembl.database.homo_sapiens_core.tables.DataFile.DATA_FILE;

    /**
     * The table <code>homo_sapiens_core_89_37.density_feature</code>.
     */
    public static final DensityFeature DENSITY_FEATURE = org.ensembl.database.homo_sapiens_core.tables.DensityFeature.DENSITY_FEATURE;

    /**
     * The table <code>homo_sapiens_core_89_37.density_type</code>.
     */
    public static final DensityType DENSITY_TYPE = org.ensembl.database.homo_sapiens_core.tables.DensityType.DENSITY_TYPE;

    /**
     * The table <code>homo_sapiens_core_89_37.dependent_xref</code>.
     */
    public static final DependentXref DEPENDENT_XREF = org.ensembl.database.homo_sapiens_core.tables.DependentXref.DEPENDENT_XREF;

    /**
     * The table <code>homo_sapiens_core_89_37.ditag</code>.
     */
    public static final Ditag DITAG = org.ensembl.database.homo_sapiens_core.tables.Ditag.DITAG;

    /**
     * The table <code>homo_sapiens_core_89_37.ditag_feature</code>.
     */
    public static final DitagFeature DITAG_FEATURE = org.ensembl.database.homo_sapiens_core.tables.DitagFeature.DITAG_FEATURE;

    /**
     * The table <code>homo_sapiens_core_89_37.dna</code>.
     */
    public static final Dna DNA = org.ensembl.database.homo_sapiens_core.tables.Dna.DNA;

    /**
     * The table <code>homo_sapiens_core_89_37.dna_align_feature</code>.
     */
    public static final DnaAlignFeature DNA_ALIGN_FEATURE = org.ensembl.database.homo_sapiens_core.tables.DnaAlignFeature.DNA_ALIGN_FEATURE;

    /**
     * The table <code>homo_sapiens_core_89_37.dna_align_feature_attrib</code>.
     */
    public static final DnaAlignFeatureAttrib DNA_ALIGN_FEATURE_ATTRIB = org.ensembl.database.homo_sapiens_core.tables.DnaAlignFeatureAttrib.DNA_ALIGN_FEATURE_ATTRIB;

    /**
     * The table <code>homo_sapiens_core_89_37.exon</code>.
     */
    public static final Exon EXON = org.ensembl.database.homo_sapiens_core.tables.Exon.EXON;

    /**
     * The table <code>homo_sapiens_core_89_37.exon_transcript</code>.
     */
    public static final ExonTranscript EXON_TRANSCRIPT = org.ensembl.database.homo_sapiens_core.tables.ExonTranscript.EXON_TRANSCRIPT;

    /**
     * The table <code>homo_sapiens_core_89_37.external_db</code>.
     */
    public static final ExternalDb EXTERNAL_DB = org.ensembl.database.homo_sapiens_core.tables.ExternalDb.EXTERNAL_DB;

    /**
     * The table <code>homo_sapiens_core_89_37.external_synonym</code>.
     */
    public static final ExternalSynonym EXTERNAL_SYNONYM = org.ensembl.database.homo_sapiens_core.tables.ExternalSynonym.EXTERNAL_SYNONYM;

    /**
     * The table <code>homo_sapiens_core_89_37.gene</code>.
     */
    public static final Gene GENE = org.ensembl.database.homo_sapiens_core.tables.Gene.GENE;

    /**
     * The table <code>homo_sapiens_core_89_37.gene_archive</code>.
     */
    public static final GeneArchive GENE_ARCHIVE = org.ensembl.database.homo_sapiens_core.tables.GeneArchive.GENE_ARCHIVE;

    /**
     * The table <code>homo_sapiens_core_89_37.gene_attrib</code>.
     */
    public static final GeneAttrib GENE_ATTRIB = org.ensembl.database.homo_sapiens_core.tables.GeneAttrib.GENE_ATTRIB;

    /**
     * The table <code>homo_sapiens_core_89_37.genome_statistics</code>.
     */
    public static final GenomeStatistics GENOME_STATISTICS = org.ensembl.database.homo_sapiens_core.tables.GenomeStatistics.GENOME_STATISTICS;

    /**
     * The table <code>homo_sapiens_core_89_37.identity_xref</code>.
     */
    public static final IdentityXref IDENTITY_XREF = org.ensembl.database.homo_sapiens_core.tables.IdentityXref.IDENTITY_XREF;

    /**
     * The table <code>homo_sapiens_core_89_37.interpro</code>.
     */
    public static final Interpro INTERPRO = org.ensembl.database.homo_sapiens_core.tables.Interpro.INTERPRO;

    /**
     * The table <code>homo_sapiens_core_89_37.intron_supporting_evidence</code>.
     */
    public static final IntronSupportingEvidence INTRON_SUPPORTING_EVIDENCE = org.ensembl.database.homo_sapiens_core.tables.IntronSupportingEvidence.INTRON_SUPPORTING_EVIDENCE;

    /**
     * The table <code>homo_sapiens_core_89_37.karyotype</code>.
     */
    public static final Karyotype KARYOTYPE = org.ensembl.database.homo_sapiens_core.tables.Karyotype.KARYOTYPE;

    /**
     * The table <code>homo_sapiens_core_89_37.map</code>.
     */
    public static final Map MAP = org.ensembl.database.homo_sapiens_core.tables.Map.MAP;

    /**
     * The table <code>homo_sapiens_core_89_37.mapping_session</code>.
     */
    public static final MappingSession MAPPING_SESSION = org.ensembl.database.homo_sapiens_core.tables.MappingSession.MAPPING_SESSION;

    /**
     * The table <code>homo_sapiens_core_89_37.mapping_set</code>.
     */
    public static final MappingSet MAPPING_SET = org.ensembl.database.homo_sapiens_core.tables.MappingSet.MAPPING_SET;

    /**
     * The table <code>homo_sapiens_core_89_37.marker</code>.
     */
    public static final Marker MARKER = org.ensembl.database.homo_sapiens_core.tables.Marker.MARKER;

    /**
     * The table <code>homo_sapiens_core_89_37.marker_feature</code>.
     */
    public static final MarkerFeature MARKER_FEATURE = org.ensembl.database.homo_sapiens_core.tables.MarkerFeature.MARKER_FEATURE;

    /**
     * The table <code>homo_sapiens_core_89_37.marker_map_location</code>.
     */
    public static final MarkerMapLocation MARKER_MAP_LOCATION = org.ensembl.database.homo_sapiens_core.tables.MarkerMapLocation.MARKER_MAP_LOCATION;

    /**
     * The table <code>homo_sapiens_core_89_37.marker_synonym</code>.
     */
    public static final MarkerSynonym MARKER_SYNONYM = org.ensembl.database.homo_sapiens_core.tables.MarkerSynonym.MARKER_SYNONYM;

    /**
     * The table <code>homo_sapiens_core_89_37.meta</code>.
     */
    public static final Meta META = org.ensembl.database.homo_sapiens_core.tables.Meta.META;

    /**
     * The table <code>homo_sapiens_core_89_37.meta_coord</code>.
     */
    public static final MetaCoord META_COORD = org.ensembl.database.homo_sapiens_core.tables.MetaCoord.META_COORD;

    /**
     * The table <code>homo_sapiens_core_89_37.misc_attrib</code>.
     */
    public static final MiscAttrib MISC_ATTRIB = org.ensembl.database.homo_sapiens_core.tables.MiscAttrib.MISC_ATTRIB;

    /**
     * The table <code>homo_sapiens_core_89_37.misc_feature</code>.
     */
    public static final MiscFeature MISC_FEATURE = org.ensembl.database.homo_sapiens_core.tables.MiscFeature.MISC_FEATURE;

    /**
     * The table <code>homo_sapiens_core_89_37.misc_feature_misc_set</code>.
     */
    public static final MiscFeatureMiscSet MISC_FEATURE_MISC_SET = org.ensembl.database.homo_sapiens_core.tables.MiscFeatureMiscSet.MISC_FEATURE_MISC_SET;

    /**
     * The table <code>homo_sapiens_core_89_37.misc_set</code>.
     */
    public static final MiscSet MISC_SET = org.ensembl.database.homo_sapiens_core.tables.MiscSet.MISC_SET;

    /**
     * The table <code>homo_sapiens_core_89_37.object_xref</code>.
     */
    public static final ObjectXref OBJECT_XREF = org.ensembl.database.homo_sapiens_core.tables.ObjectXref.OBJECT_XREF;

    /**
     * The table <code>homo_sapiens_core_89_37.ontology_xref</code>.
     */
    public static final OntologyXref ONTOLOGY_XREF = org.ensembl.database.homo_sapiens_core.tables.OntologyXref.ONTOLOGY_XREF;

    /**
     * The table <code>homo_sapiens_core_89_37.operon</code>.
     */
    public static final Operon OPERON = org.ensembl.database.homo_sapiens_core.tables.Operon.OPERON;

    /**
     * The table <code>homo_sapiens_core_89_37.operon_transcript</code>.
     */
    public static final OperonTranscript OPERON_TRANSCRIPT = org.ensembl.database.homo_sapiens_core.tables.OperonTranscript.OPERON_TRANSCRIPT;

    /**
     * The table <code>homo_sapiens_core_89_37.operon_transcript_gene</code>.
     */
    public static final OperonTranscriptGene OPERON_TRANSCRIPT_GENE = org.ensembl.database.homo_sapiens_core.tables.OperonTranscriptGene.OPERON_TRANSCRIPT_GENE;

    /**
     * The table <code>homo_sapiens_core_89_37.peptide_archive</code>.
     */
    public static final PeptideArchive PEPTIDE_ARCHIVE = org.ensembl.database.homo_sapiens_core.tables.PeptideArchive.PEPTIDE_ARCHIVE;

    /**
     * The table <code>homo_sapiens_core_89_37.prediction_exon</code>.
     */
    public static final PredictionExon PREDICTION_EXON = org.ensembl.database.homo_sapiens_core.tables.PredictionExon.PREDICTION_EXON;

    /**
     * The table <code>homo_sapiens_core_89_37.prediction_transcript</code>.
     */
    public static final PredictionTranscript PREDICTION_TRANSCRIPT = org.ensembl.database.homo_sapiens_core.tables.PredictionTranscript.PREDICTION_TRANSCRIPT;

    /**
     * The table <code>homo_sapiens_core_89_37.protein_align_feature</code>.
     */
    public static final ProteinAlignFeature PROTEIN_ALIGN_FEATURE = org.ensembl.database.homo_sapiens_core.tables.ProteinAlignFeature.PROTEIN_ALIGN_FEATURE;

    /**
     * The table <code>homo_sapiens_core_89_37.protein_feature</code>.
     */
    public static final ProteinFeature PROTEIN_FEATURE = org.ensembl.database.homo_sapiens_core.tables.ProteinFeature.PROTEIN_FEATURE;

    /**
     * The table <code>homo_sapiens_core_89_37.repeat_consensus</code>.
     */
    public static final RepeatConsensus REPEAT_CONSENSUS = org.ensembl.database.homo_sapiens_core.tables.RepeatConsensus.REPEAT_CONSENSUS;

    /**
     * The table <code>homo_sapiens_core_89_37.repeat_feature</code>.
     */
    public static final RepeatFeature REPEAT_FEATURE = org.ensembl.database.homo_sapiens_core.tables.RepeatFeature.REPEAT_FEATURE;

    /**
     * The table <code>homo_sapiens_core_89_37.seq_region</code>.
     */
    public static final SeqRegion SEQ_REGION = org.ensembl.database.homo_sapiens_core.tables.SeqRegion.SEQ_REGION;

    /**
     * The table <code>homo_sapiens_core_89_37.seq_region_attrib</code>.
     */
    public static final SeqRegionAttrib SEQ_REGION_ATTRIB = org.ensembl.database.homo_sapiens_core.tables.SeqRegionAttrib.SEQ_REGION_ATTRIB;

    /**
     * The table <code>homo_sapiens_core_89_37.seq_region_mapping</code>.
     */
    public static final SeqRegionMapping SEQ_REGION_MAPPING = org.ensembl.database.homo_sapiens_core.tables.SeqRegionMapping.SEQ_REGION_MAPPING;

    /**
     * The table <code>homo_sapiens_core_89_37.seq_region_synonym</code>.
     */
    public static final SeqRegionSynonym SEQ_REGION_SYNONYM = org.ensembl.database.homo_sapiens_core.tables.SeqRegionSynonym.SEQ_REGION_SYNONYM;

    /**
     * The table <code>homo_sapiens_core_89_37.simple_feature</code>.
     */
    public static final SimpleFeature SIMPLE_FEATURE = org.ensembl.database.homo_sapiens_core.tables.SimpleFeature.SIMPLE_FEATURE;

    /**
     * The table <code>homo_sapiens_core_89_37.stable_id_event</code>.
     */
    public static final StableIdEvent STABLE_ID_EVENT = org.ensembl.database.homo_sapiens_core.tables.StableIdEvent.STABLE_ID_EVENT;

    /**
     * The table <code>homo_sapiens_core_89_37.supporting_feature</code>.
     */
    public static final SupportingFeature SUPPORTING_FEATURE = org.ensembl.database.homo_sapiens_core.tables.SupportingFeature.SUPPORTING_FEATURE;

    /**
     * The table <code>homo_sapiens_core_89_37.transcript</code>.
     */
    public static final Transcript TRANSCRIPT = org.ensembl.database.homo_sapiens_core.tables.Transcript.TRANSCRIPT;

    /**
     * The table <code>homo_sapiens_core_89_37.transcript_attrib</code>.
     */
    public static final TranscriptAttrib TRANSCRIPT_ATTRIB = org.ensembl.database.homo_sapiens_core.tables.TranscriptAttrib.TRANSCRIPT_ATTRIB;

    /**
     * The table <code>homo_sapiens_core_89_37.transcript_intron_supporting_evidence</code>.
     */
    public static final TranscriptIntronSupportingEvidence TRANSCRIPT_INTRON_SUPPORTING_EVIDENCE = org.ensembl.database.homo_sapiens_core.tables.TranscriptIntronSupportingEvidence.TRANSCRIPT_INTRON_SUPPORTING_EVIDENCE;

    /**
     * The table <code>homo_sapiens_core_89_37.transcript_supporting_feature</code>.
     */
    public static final TranscriptSupportingFeature TRANSCRIPT_SUPPORTING_FEATURE = org.ensembl.database.homo_sapiens_core.tables.TranscriptSupportingFeature.TRANSCRIPT_SUPPORTING_FEATURE;

    /**
     * The table <code>homo_sapiens_core_89_37.translation</code>.
     */
    public static final Translation TRANSLATION = org.ensembl.database.homo_sapiens_core.tables.Translation.TRANSLATION;

    /**
     * The table <code>homo_sapiens_core_89_37.translation_attrib</code>.
     */
    public static final TranslationAttrib TRANSLATION_ATTRIB = org.ensembl.database.homo_sapiens_core.tables.TranslationAttrib.TRANSLATION_ATTRIB;

    /**
     * The table <code>homo_sapiens_core_89_37.unmapped_object</code>.
     */
    public static final UnmappedObject UNMAPPED_OBJECT = org.ensembl.database.homo_sapiens_core.tables.UnmappedObject.UNMAPPED_OBJECT;

    /**
     * The table <code>homo_sapiens_core_89_37.unmapped_reason</code>.
     */
    public static final UnmappedReason UNMAPPED_REASON = org.ensembl.database.homo_sapiens_core.tables.UnmappedReason.UNMAPPED_REASON;

    /**
     * The table <code>homo_sapiens_core_89_37.xref</code>.
     */
    public static final Xref XREF = org.ensembl.database.homo_sapiens_core.tables.Xref.XREF;
}
