package com.hartwig.hmftools.serve.sources.actin;

public enum EligibilityRule {

    PRIMARY_TUMOR_LOCATION_BELONGS_TO_DOID_X,
    MOLECULAR_RESULTS_MUST_BE_AVAILABLE,
    ACTIVATION_OF_GENE_X,
    INACTIVATION_OF_GENE_X,
    ACTIVATING_MUTATION_IN_GENE_X,
    MUTATION_IN_GENE_X_OF_TYPE_Y,
    INACTIVATING_MUTATION_IN_GENE_X,
    AMPLIFICATION_OF_GENE_X,
    DELETION_OF_GENE_X,
    ACTIVATING_FUSION_IN_GENE_X,
    SPECIFIC_FUSION_X,
    OVEREXPRESSION_OF_GENE_X,
    WILDTYPE_OF_GENE_X,
    MSI_SIGNATURE,
    HRD_SIGNATURE,
    TMB_OF_AT_LEAST_X,
    TML_OF_AT_LEAST_X,
    TML_OF_AT_MOST_X,
}
