package com.hartwig.hmftools.healthchecker.runners.checks;

public enum GermlineCheck {
    VARIANTS_GERMLINE_INDELS,
    VARIANTS_GERMLINE_SNP,
    VARIANTS_GERMLINE_HETEROZYGOUS_COUNT,
    VARIANTS_GERMLINE_HETEROZYGOUS_COUNT_ABOVE_50_VAF,
    VARIANTS_GERMLINE_HETEROZYGOUS_COUNT_BELOW_50_VAF
}
