#!/bin/bash

pave_jar=$1 && shift
sample_id=$1 && shift
sage_somatic_dir=$1 && shift
output_dir=$1 && shift
ref_genome_version=$1 && shift
ref_genome=$1 && shift
ensembl_dir=$1 && shift
driver_gene_panel=$1 && shift
pon_file=$1 && shift
mappability_bed=$1 && shift
gnomad_dir=$1 && shift

if [[ ! -d "${output_dir}" ]]; then
  mkdir ${output_dir}
fi

output_vcf=${output_dir}/${sample_id}.sage.somatic.pave.vcf.gz

if [[ -f "${output_vcf}" ]]; then
  echo "Skipping Pave somatic for ${sample_id}, since VCF ${output_vcf} exists"
  exit
fi

sage_vcf=${sage_somatic_dir}/${sample_id}.sage.somatic.vcf.gz

if [[ ! -f "${sage_vcf}" ]]; then
  echo "Missing Sage somatic VCF, not running Pave somatic for ${sample_id}"
  exit
fi

echo "Running Pave somatic for ${sample_id}, output dir ${output_dir}"

pon_filters="HOTSPOT:5:5;PANEL:2:5;UNKNOWN:2:0"

args="-sample ${sample_id} \
  -ensembl_data_dir ${ensembl_dir} \
  -driver_gene_panel ${driver_gene_panel} \
  -ref_genome_version ${ref_genome_version} \
  -ref_genome ${ref_genome} \
  -pon_file ${pon_file} \
  -pon_filters ${pon_filters} \
  -mappability_bed ${mappability_bed} \
  -vcf_file ${sage_vcf} \
  -read_pass_only \
  -output_dir ${output_dir}"

if [ "${ref_genome_version}" == "V38" ]; then
  args="${args} -gnomad_freq_dir ${gnomad_dir} -gnomad_load_chr_on_demand"
fi

java -jar ${pave_jar} ${args}
