#!/bin/bash

sage_jar=$1 && shift
tumor_id=$1 && shift
tumor_bam=$1 && shift
reference_id=$1 && shift
reference_bam=$1 && shift
output_dir=$1 && shift
ref_genome_version=$1 && shift
ref_genome=$1 && shift
ensembl_dir=$1 && shift
hotspots=$1 && shift
panel_bed=$1 && shift
coverage_bed=$1 && shift
high_confidence_bed=$1 && shift
threads=$1 && shift

if [[ ! -d "${output_dir}" ]]; then
  mkdir ${output_dir}
fi

output_vcf=${output_dir}/${tumor_id}.sage.somatic.vcf.gz

if [[ -f "${output_vcf}" ]]; then
  echo "Skipping Sage somatic for ${tumor_id}, since VCF ${output_vcf} exists"
  exit
fi

echo "Running Sage somatic for ${tumor_id}, output dir ${output_dir}"

java -jar ${sage_jar} \
  -tumor ${tumor_id} \
  -tumor_bam ${tumor_bam} \
  -reference ${reference_id} \
  -reference_bam ${reference_bam} \
  -hotspots ${hotspots} \
  -panel_bed ${panel_bed} \
  -coverage_bed ${coverage_bed} \
  -high_confidence_bed ${high_confidence_bed} \
  -ref_genome ${ref_genome} \
  -ref_genome_version ${ref_genome_version} \
  -ensembl_data_dir ${ensembl_dir} \
  -threads ${threads} \
  -write_bqr_data \
  -out ${output_vcf} \

# optional: -write_bqr_plot
