package com.hartwig.hmftools.gripss.filters;

public enum FilterType
{
    PASS,
    HARD_FILTERED,
    MIN_NORMAL_COVERAGE,
    MAX_NORMAL_RELATIVE_SUPPORT,
    MIN_TUMOR_AF,
    SHORT_DEL_INS_ARTIFACT,
    MIN_QUAL,
    IMPRECISE,
    MAX_POLY_G_LENGTH,
    MAX_POLY_A_HOM_LENGTH,
    MAX_HOM_LENGTH_SHORT_INV,
    MAX_INEXACT_HOM_LENGTH_SHORT_DEL,
    SHORT_SR_SUPPORT,
    SHORT_SR_NORMAL,
    SHORT_STRAND_BIAS,
    MIN_LENGTH,
    DISCORDANT_PAIR_SUPPORT;

}
