/*
 * This file is generated by jOOQ.
*/
package com.hartwig.hmftools.vicc.database;


import com.hartwig.hmftools.vicc.database.tables.Viccentry;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in vicc_db
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>vicc_db.viccEntry</code>.
     */
    public static final Viccentry VICCENTRY = com.hartwig.hmftools.vicc.database.tables.Viccentry.VICCENTRY;
}
