/*
 * This file is generated by jOOQ.
*/
package org.ensembl.database.homo_sapiens_core.tables.records;


import javax.annotation.Generated;

import org.ensembl.database.homo_sapiens_core.tables.AltAlleleGroup;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Row1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AltAlleleGroupRecord extends UpdatableRecordImpl<AltAlleleGroupRecord> implements Record1<UInteger> {

    private static final long serialVersionUID = 1514103266;

    /**
     * Setter for <code>homo_sapiens_core_89_37.alt_allele_group.alt_allele_group_id</code>.
     */
    public void setAltAlleleGroupId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>homo_sapiens_core_89_37.alt_allele_group.alt_allele_group_id</code>.
     */
    public UInteger getAltAlleleGroupId() {
        return (UInteger) get(0);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record1 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row1<UInteger> fieldsRow() {
        return (Row1) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row1<UInteger> valuesRow() {
        return (Row1) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return AltAlleleGroup.ALT_ALLELE_GROUP.ALT_ALLELE_GROUP_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getAltAlleleGroupId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AltAlleleGroupRecord value1(UInteger value) {
        setAltAlleleGroupId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AltAlleleGroupRecord values(UInteger value1) {
        value1(value1);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AltAlleleGroupRecord
     */
    public AltAlleleGroupRecord() {
        super(AltAlleleGroup.ALT_ALLELE_GROUP);
    }

    /**
     * Create a detached, initialised AltAlleleGroupRecord
     */
    public AltAlleleGroupRecord(UInteger altAlleleGroupId) {
        super(AltAlleleGroup.ALT_ALLELE_GROUP);

        set(0, altAlleleGroupId);
    }
}
