/*
 * This file is generated by jOOQ.
*/
package org.ensembl.database.homo_sapiens_core.tables.records;


import javax.annotation.Generated;

import org.ensembl.database.homo_sapiens_core.enums.AssemblyExceptionExcType;
import org.ensembl.database.homo_sapiens_core.tables.AssemblyException;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AssemblyExceptionRecord extends UpdatableRecordImpl<AssemblyExceptionRecord> implements Record9<UInteger, UInteger, UInteger, UInteger, AssemblyExceptionExcType, UInteger, UInteger, UInteger, Integer> {

    private static final long serialVersionUID = -398673245;

    /**
     * Setter for <code>homo_sapiens_core_89_37.assembly_exception.assembly_exception_id</code>.
     */
    public void setAssemblyExceptionId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>homo_sapiens_core_89_37.assembly_exception.assembly_exception_id</code>.
     */
    public UInteger getAssemblyExceptionId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>homo_sapiens_core_89_37.assembly_exception.seq_region_id</code>.
     */
    public void setSeqRegionId(UInteger value) {
        set(1, value);
    }

    /**
     * Getter for <code>homo_sapiens_core_89_37.assembly_exception.seq_region_id</code>.
     */
    public UInteger getSeqRegionId() {
        return (UInteger) get(1);
    }

    /**
     * Setter for <code>homo_sapiens_core_89_37.assembly_exception.seq_region_start</code>.
     */
    public void setSeqRegionStart(UInteger value) {
        set(2, value);
    }

    /**
     * Getter for <code>homo_sapiens_core_89_37.assembly_exception.seq_region_start</code>.
     */
    public UInteger getSeqRegionStart() {
        return (UInteger) get(2);
    }

    /**
     * Setter for <code>homo_sapiens_core_89_37.assembly_exception.seq_region_end</code>.
     */
    public void setSeqRegionEnd(UInteger value) {
        set(3, value);
    }

    /**
     * Getter for <code>homo_sapiens_core_89_37.assembly_exception.seq_region_end</code>.
     */
    public UInteger getSeqRegionEnd() {
        return (UInteger) get(3);
    }

    /**
     * Setter for <code>homo_sapiens_core_89_37.assembly_exception.exc_type</code>.
     */
    public void setExcType(AssemblyExceptionExcType value) {
        set(4, value);
    }

    /**
     * Getter for <code>homo_sapiens_core_89_37.assembly_exception.exc_type</code>.
     */
    public AssemblyExceptionExcType getExcType() {
        return (AssemblyExceptionExcType) get(4);
    }

    /**
     * Setter for <code>homo_sapiens_core_89_37.assembly_exception.exc_seq_region_id</code>.
     */
    public void setExcSeqRegionId(UInteger value) {
        set(5, value);
    }

    /**
     * Getter for <code>homo_sapiens_core_89_37.assembly_exception.exc_seq_region_id</code>.
     */
    public UInteger getExcSeqRegionId() {
        return (UInteger) get(5);
    }

    /**
     * Setter for <code>homo_sapiens_core_89_37.assembly_exception.exc_seq_region_start</code>.
     */
    public void setExcSeqRegionStart(UInteger value) {
        set(6, value);
    }

    /**
     * Getter for <code>homo_sapiens_core_89_37.assembly_exception.exc_seq_region_start</code>.
     */
    public UInteger getExcSeqRegionStart() {
        return (UInteger) get(6);
    }

    /**
     * Setter for <code>homo_sapiens_core_89_37.assembly_exception.exc_seq_region_end</code>.
     */
    public void setExcSeqRegionEnd(UInteger value) {
        set(7, value);
    }

    /**
     * Getter for <code>homo_sapiens_core_89_37.assembly_exception.exc_seq_region_end</code>.
     */
    public UInteger getExcSeqRegionEnd() {
        return (UInteger) get(7);
    }

    /**
     * Setter for <code>homo_sapiens_core_89_37.assembly_exception.ori</code>.
     */
    public void setOri(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>homo_sapiens_core_89_37.assembly_exception.ori</code>.
     */
    public Integer getOri() {
        return (Integer) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<UInteger, UInteger, UInteger, UInteger, AssemblyExceptionExcType, UInteger, UInteger, UInteger, Integer> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<UInteger, UInteger, UInteger, UInteger, AssemblyExceptionExcType, UInteger, UInteger, UInteger, Integer> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return AssemblyException.ASSEMBLY_EXCEPTION.ASSEMBLY_EXCEPTION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field2() {
        return AssemblyException.ASSEMBLY_EXCEPTION.SEQ_REGION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field3() {
        return AssemblyException.ASSEMBLY_EXCEPTION.SEQ_REGION_START;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field4() {
        return AssemblyException.ASSEMBLY_EXCEPTION.SEQ_REGION_END;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<AssemblyExceptionExcType> field5() {
        return AssemblyException.ASSEMBLY_EXCEPTION.EXC_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field6() {
        return AssemblyException.ASSEMBLY_EXCEPTION.EXC_SEQ_REGION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field7() {
        return AssemblyException.ASSEMBLY_EXCEPTION.EXC_SEQ_REGION_START;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field8() {
        return AssemblyException.ASSEMBLY_EXCEPTION.EXC_SEQ_REGION_END;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return AssemblyException.ASSEMBLY_EXCEPTION.ORI;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getAssemblyExceptionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value2() {
        return getSeqRegionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value3() {
        return getSeqRegionStart();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value4() {
        return getSeqRegionEnd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AssemblyExceptionExcType value5() {
        return getExcType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value6() {
        return getExcSeqRegionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value7() {
        return getExcSeqRegionStart();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value8() {
        return getExcSeqRegionEnd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getOri();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AssemblyExceptionRecord value1(UInteger value) {
        setAssemblyExceptionId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AssemblyExceptionRecord value2(UInteger value) {
        setSeqRegionId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AssemblyExceptionRecord value3(UInteger value) {
        setSeqRegionStart(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AssemblyExceptionRecord value4(UInteger value) {
        setSeqRegionEnd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AssemblyExceptionRecord value5(AssemblyExceptionExcType value) {
        setExcType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AssemblyExceptionRecord value6(UInteger value) {
        setExcSeqRegionId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AssemblyExceptionRecord value7(UInteger value) {
        setExcSeqRegionStart(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AssemblyExceptionRecord value8(UInteger value) {
        setExcSeqRegionEnd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AssemblyExceptionRecord value9(Integer value) {
        setOri(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AssemblyExceptionRecord values(UInteger value1, UInteger value2, UInteger value3, UInteger value4, AssemblyExceptionExcType value5, UInteger value6, UInteger value7, UInteger value8, Integer value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AssemblyExceptionRecord
     */
    public AssemblyExceptionRecord() {
        super(AssemblyException.ASSEMBLY_EXCEPTION);
    }

    /**
     * Create a detached, initialised AssemblyExceptionRecord
     */
    public AssemblyExceptionRecord(UInteger assemblyExceptionId, UInteger seqRegionId, UInteger seqRegionStart, UInteger seqRegionEnd, AssemblyExceptionExcType excType, UInteger excSeqRegionId, UInteger excSeqRegionStart, UInteger excSeqRegionEnd, Integer ori) {
        super(AssemblyException.ASSEMBLY_EXCEPTION);

        set(0, assemblyExceptionId);
        set(1, seqRegionId);
        set(2, seqRegionStart);
        set(3, seqRegionEnd);
        set(4, excType);
        set(5, excSeqRegionId);
        set(6, excSeqRegionStart);
        set(7, excSeqRegionEnd);
        set(8, ori);
    }
}
