/*
 * This file is generated by jOOQ.
*/
package org.ensembl.database.homo_sapiens_core.tables.records;


import javax.annotation.Generated;

import org.ensembl.database.homo_sapiens_core.tables.CoordSystem;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CoordSystemRecord extends UpdatableRecordImpl<CoordSystemRecord> implements Record6<UInteger, UInteger, String, String, Integer, String> {

    private static final long serialVersionUID = -127119356;

    /**
     * Setter for <code>homo_sapiens_core_89_37.coord_system.coord_system_id</code>.
     */
    public void setCoordSystemId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>homo_sapiens_core_89_37.coord_system.coord_system_id</code>.
     */
    public UInteger getCoordSystemId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>homo_sapiens_core_89_37.coord_system.species_id</code>.
     */
    public void setSpeciesId(UInteger value) {
        set(1, value);
    }

    /**
     * Getter for <code>homo_sapiens_core_89_37.coord_system.species_id</code>.
     */
    public UInteger getSpeciesId() {
        return (UInteger) get(1);
    }

    /**
     * Setter for <code>homo_sapiens_core_89_37.coord_system.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>homo_sapiens_core_89_37.coord_system.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>homo_sapiens_core_89_37.coord_system.version</code>.
     */
    public void setVersion(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>homo_sapiens_core_89_37.coord_system.version</code>.
     */
    public String getVersion() {
        return (String) get(3);
    }

    /**
     * Setter for <code>homo_sapiens_core_89_37.coord_system.rank</code>.
     */
    public void setRank(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>homo_sapiens_core_89_37.coord_system.rank</code>.
     */
    public Integer getRank() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>homo_sapiens_core_89_37.coord_system.attrib</code>.
     */
    public void setAttrib(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>homo_sapiens_core_89_37.coord_system.attrib</code>.
     */
    public String getAttrib() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<UInteger, UInteger, String, String, Integer, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<UInteger, UInteger, String, String, Integer, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return CoordSystem.COORD_SYSTEM.COORD_SYSTEM_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field2() {
        return CoordSystem.COORD_SYSTEM.SPECIES_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return CoordSystem.COORD_SYSTEM.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return CoordSystem.COORD_SYSTEM.VERSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return CoordSystem.COORD_SYSTEM.RANK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return CoordSystem.COORD_SYSTEM.ATTRIB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getCoordSystemId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value2() {
        return getSpeciesId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getRank();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getAttrib();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CoordSystemRecord value1(UInteger value) {
        setCoordSystemId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CoordSystemRecord value2(UInteger value) {
        setSpeciesId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CoordSystemRecord value3(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CoordSystemRecord value4(String value) {
        setVersion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CoordSystemRecord value5(Integer value) {
        setRank(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CoordSystemRecord value6(String value) {
        setAttrib(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CoordSystemRecord values(UInteger value1, UInteger value2, String value3, String value4, Integer value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CoordSystemRecord
     */
    public CoordSystemRecord() {
        super(CoordSystem.COORD_SYSTEM);
    }

    /**
     * Create a detached, initialised CoordSystemRecord
     */
    public CoordSystemRecord(UInteger coordSystemId, UInteger speciesId, String name, String version, Integer rank, String attrib) {
        super(CoordSystem.COORD_SYSTEM);

        set(0, coordSystemId);
        set(1, speciesId);
        set(2, name);
        set(3, version);
        set(4, rank);
        set(5, attrib);
    }
}
