/*
 * This file is generated by jOOQ.
*/
package org.ensembl.database.homo_sapiens_core.tables.records;


import javax.annotation.Generated;

import org.ensembl.database.homo_sapiens_core.enums.DataFileFileType;
import org.ensembl.database.homo_sapiens_core.tables.DataFile;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;
import org.jooq.types.UShort;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DataFileRecord extends UpdatableRecordImpl<DataFileRecord> implements Record8<UInteger, UInteger, UShort, String, Byte, Byte, String, DataFileFileType> {

    private static final long serialVersionUID = -360018966;

    /**
     * Setter for <code>homo_sapiens_core_89_37.data_file.data_file_id</code>.
     */
    public void setDataFileId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>homo_sapiens_core_89_37.data_file.data_file_id</code>.
     */
    public UInteger getDataFileId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>homo_sapiens_core_89_37.data_file.coord_system_id</code>.
     */
    public void setCoordSystemId(UInteger value) {
        set(1, value);
    }

    /**
     * Getter for <code>homo_sapiens_core_89_37.data_file.coord_system_id</code>.
     */
    public UInteger getCoordSystemId() {
        return (UInteger) get(1);
    }

    /**
     * Setter for <code>homo_sapiens_core_89_37.data_file.analysis_id</code>.
     */
    public void setAnalysisId(UShort value) {
        set(2, value);
    }

    /**
     * Getter for <code>homo_sapiens_core_89_37.data_file.analysis_id</code>.
     */
    public UShort getAnalysisId() {
        return (UShort) get(2);
    }

    /**
     * Setter for <code>homo_sapiens_core_89_37.data_file.name</code>.
     */
    public void setName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>homo_sapiens_core_89_37.data_file.name</code>.
     */
    public String getName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>homo_sapiens_core_89_37.data_file.version_lock</code>.
     */
    public void setVersionLock(Byte value) {
        set(4, value);
    }

    /**
     * Getter for <code>homo_sapiens_core_89_37.data_file.version_lock</code>.
     */
    public Byte getVersionLock() {
        return (Byte) get(4);
    }

    /**
     * Setter for <code>homo_sapiens_core_89_37.data_file.absolute</code>.
     */
    public void setAbsolute(Byte value) {
        set(5, value);
    }

    /**
     * Getter for <code>homo_sapiens_core_89_37.data_file.absolute</code>.
     */
    public Byte getAbsolute() {
        return (Byte) get(5);
    }

    /**
     * Setter for <code>homo_sapiens_core_89_37.data_file.url</code>.
     */
    public void setUrl(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>homo_sapiens_core_89_37.data_file.url</code>.
     */
    public String getUrl() {
        return (String) get(6);
    }

    /**
     * Setter for <code>homo_sapiens_core_89_37.data_file.file_type</code>.
     */
    public void setFileType(DataFileFileType value) {
        set(7, value);
    }

    /**
     * Getter for <code>homo_sapiens_core_89_37.data_file.file_type</code>.
     */
    public DataFileFileType getFileType() {
        return (DataFileFileType) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<UInteger, UInteger, UShort, String, Byte, Byte, String, DataFileFileType> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<UInteger, UInteger, UShort, String, Byte, Byte, String, DataFileFileType> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return DataFile.DATA_FILE.DATA_FILE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field2() {
        return DataFile.DATA_FILE.COORD_SYSTEM_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UShort> field3() {
        return DataFile.DATA_FILE.ANALYSIS_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return DataFile.DATA_FILE.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field5() {
        return DataFile.DATA_FILE.VERSION_LOCK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field6() {
        return DataFile.DATA_FILE.ABSOLUTE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return DataFile.DATA_FILE.URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<DataFileFileType> field8() {
        return DataFile.DATA_FILE.FILE_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getDataFileId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value2() {
        return getCoordSystemId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UShort value3() {
        return getAnalysisId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value5() {
        return getVersionLock();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value6() {
        return getAbsolute();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DataFileFileType value8() {
        return getFileType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DataFileRecord value1(UInteger value) {
        setDataFileId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DataFileRecord value2(UInteger value) {
        setCoordSystemId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DataFileRecord value3(UShort value) {
        setAnalysisId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DataFileRecord value4(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DataFileRecord value5(Byte value) {
        setVersionLock(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DataFileRecord value6(Byte value) {
        setAbsolute(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DataFileRecord value7(String value) {
        setUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DataFileRecord value8(DataFileFileType value) {
        setFileType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DataFileRecord values(UInteger value1, UInteger value2, UShort value3, String value4, Byte value5, Byte value6, String value7, DataFileFileType value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DataFileRecord
     */
    public DataFileRecord() {
        super(DataFile.DATA_FILE);
    }

    /**
     * Create a detached, initialised DataFileRecord
     */
    public DataFileRecord(UInteger dataFileId, UInteger coordSystemId, UShort analysisId, String name, Byte versionLock, Byte absolute, String url, DataFileFileType fileType) {
        super(DataFile.DATA_FILE);

        set(0, dataFileId);
        set(1, coordSystemId);
        set(2, analysisId);
        set(3, name);
        set(4, versionLock);
        set(5, absolute);
        set(6, url);
        set(7, fileType);
    }
}
