/*
 * This file is generated by jOOQ.
*/
package org.ensembl.database.homo_sapiens_core.tables.records;


import javax.annotation.Generated;

import org.ensembl.database.homo_sapiens_core.tables.DensityFeature;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DensityFeatureRecord extends UpdatableRecordImpl<DensityFeatureRecord> implements Record6<UInteger, UInteger, UInteger, UInteger, UInteger, Double> {

    private static final long serialVersionUID = 1828391088;

    /**
     * Setter for <code>homo_sapiens_core_89_37.density_feature.density_feature_id</code>.
     */
    public void setDensityFeatureId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>homo_sapiens_core_89_37.density_feature.density_feature_id</code>.
     */
    public UInteger getDensityFeatureId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>homo_sapiens_core_89_37.density_feature.density_type_id</code>.
     */
    public void setDensityTypeId(UInteger value) {
        set(1, value);
    }

    /**
     * Getter for <code>homo_sapiens_core_89_37.density_feature.density_type_id</code>.
     */
    public UInteger getDensityTypeId() {
        return (UInteger) get(1);
    }

    /**
     * Setter for <code>homo_sapiens_core_89_37.density_feature.seq_region_id</code>.
     */
    public void setSeqRegionId(UInteger value) {
        set(2, value);
    }

    /**
     * Getter for <code>homo_sapiens_core_89_37.density_feature.seq_region_id</code>.
     */
    public UInteger getSeqRegionId() {
        return (UInteger) get(2);
    }

    /**
     * Setter for <code>homo_sapiens_core_89_37.density_feature.seq_region_start</code>.
     */
    public void setSeqRegionStart(UInteger value) {
        set(3, value);
    }

    /**
     * Getter for <code>homo_sapiens_core_89_37.density_feature.seq_region_start</code>.
     */
    public UInteger getSeqRegionStart() {
        return (UInteger) get(3);
    }

    /**
     * Setter for <code>homo_sapiens_core_89_37.density_feature.seq_region_end</code>.
     */
    public void setSeqRegionEnd(UInteger value) {
        set(4, value);
    }

    /**
     * Getter for <code>homo_sapiens_core_89_37.density_feature.seq_region_end</code>.
     */
    public UInteger getSeqRegionEnd() {
        return (UInteger) get(4);
    }

    /**
     * Setter for <code>homo_sapiens_core_89_37.density_feature.density_value</code>.
     */
    public void setDensityValue(Double value) {
        set(5, value);
    }

    /**
     * Getter for <code>homo_sapiens_core_89_37.density_feature.density_value</code>.
     */
    public Double getDensityValue() {
        return (Double) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<UInteger, UInteger, UInteger, UInteger, UInteger, Double> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<UInteger, UInteger, UInteger, UInteger, UInteger, Double> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return DensityFeature.DENSITY_FEATURE.DENSITY_FEATURE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field2() {
        return DensityFeature.DENSITY_FEATURE.DENSITY_TYPE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field3() {
        return DensityFeature.DENSITY_FEATURE.SEQ_REGION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field4() {
        return DensityFeature.DENSITY_FEATURE.SEQ_REGION_START;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field5() {
        return DensityFeature.DENSITY_FEATURE.SEQ_REGION_END;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field6() {
        return DensityFeature.DENSITY_FEATURE.DENSITY_VALUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getDensityFeatureId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value2() {
        return getDensityTypeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value3() {
        return getSeqRegionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value4() {
        return getSeqRegionStart();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value5() {
        return getSeqRegionEnd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value6() {
        return getDensityValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DensityFeatureRecord value1(UInteger value) {
        setDensityFeatureId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DensityFeatureRecord value2(UInteger value) {
        setDensityTypeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DensityFeatureRecord value3(UInteger value) {
        setSeqRegionId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DensityFeatureRecord value4(UInteger value) {
        setSeqRegionStart(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DensityFeatureRecord value5(UInteger value) {
        setSeqRegionEnd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DensityFeatureRecord value6(Double value) {
        setDensityValue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DensityFeatureRecord values(UInteger value1, UInteger value2, UInteger value3, UInteger value4, UInteger value5, Double value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DensityFeatureRecord
     */
    public DensityFeatureRecord() {
        super(DensityFeature.DENSITY_FEATURE);
    }

    /**
     * Create a detached, initialised DensityFeatureRecord
     */
    public DensityFeatureRecord(UInteger densityFeatureId, UInteger densityTypeId, UInteger seqRegionId, UInteger seqRegionStart, UInteger seqRegionEnd, Double densityValue) {
        super(DensityFeature.DENSITY_FEATURE);

        set(0, densityFeatureId);
        set(1, densityTypeId);
        set(2, seqRegionId);
        set(3, seqRegionStart);
        set(4, seqRegionEnd);
        set(5, densityValue);
    }
}
