/*
 * This file is generated by jOOQ.
*/
package org.ensembl.database.homo_sapiens_core.tables.records;


import javax.annotation.Generated;

import org.ensembl.database.homo_sapiens_core.tables.DependentXref;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DependentXrefRecord extends UpdatableRecordImpl<DependentXrefRecord> implements Record3<UInteger, UInteger, UInteger> {

    private static final long serialVersionUID = 87049455;

    /**
     * Setter for <code>homo_sapiens_core_89_37.dependent_xref.object_xref_id</code>.
     */
    public void setObjectXrefId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>homo_sapiens_core_89_37.dependent_xref.object_xref_id</code>.
     */
    public UInteger getObjectXrefId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>homo_sapiens_core_89_37.dependent_xref.master_xref_id</code>.
     */
    public void setMasterXrefId(UInteger value) {
        set(1, value);
    }

    /**
     * Getter for <code>homo_sapiens_core_89_37.dependent_xref.master_xref_id</code>.
     */
    public UInteger getMasterXrefId() {
        return (UInteger) get(1);
    }

    /**
     * Setter for <code>homo_sapiens_core_89_37.dependent_xref.dependent_xref_id</code>.
     */
    public void setDependentXrefId(UInteger value) {
        set(2, value);
    }

    /**
     * Getter for <code>homo_sapiens_core_89_37.dependent_xref.dependent_xref_id</code>.
     */
    public UInteger getDependentXrefId() {
        return (UInteger) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<UInteger, UInteger, UInteger> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<UInteger, UInteger, UInteger> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return DependentXref.DEPENDENT_XREF.OBJECT_XREF_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field2() {
        return DependentXref.DEPENDENT_XREF.MASTER_XREF_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field3() {
        return DependentXref.DEPENDENT_XREF.DEPENDENT_XREF_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getObjectXrefId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value2() {
        return getMasterXrefId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value3() {
        return getDependentXrefId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DependentXrefRecord value1(UInteger value) {
        setObjectXrefId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DependentXrefRecord value2(UInteger value) {
        setMasterXrefId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DependentXrefRecord value3(UInteger value) {
        setDependentXrefId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DependentXrefRecord values(UInteger value1, UInteger value2, UInteger value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DependentXrefRecord
     */
    public DependentXrefRecord() {
        super(DependentXref.DEPENDENT_XREF);
    }

    /**
     * Create a detached, initialised DependentXrefRecord
     */
    public DependentXrefRecord(UInteger objectXrefId, UInteger masterXrefId, UInteger dependentXrefId) {
        super(DependentXref.DEPENDENT_XREF);

        set(0, objectXrefId);
        set(1, masterXrefId);
        set(2, dependentXrefId);
    }
}
