/*
 * This file is generated by jOOQ.
*/
package org.ensembl.database.homo_sapiens_core.tables.records;


import javax.annotation.Generated;

import org.ensembl.database.homo_sapiens_core.enums.DitagFeatureDitagSide;
import org.ensembl.database.homo_sapiens_core.tables.DitagFeature;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;
import org.jooq.types.UShort;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DitagFeatureRecord extends UpdatableRecordImpl<DitagFeatureRecord> implements Record13<UInteger, UInteger, UInteger, UInteger, UInteger, UInteger, Byte, UShort, UInteger, UInteger, Byte, String, DitagFeatureDitagSide> {

    private static final long serialVersionUID = 684065212;

    /**
     * Setter for <code>homo_sapiens_core_89_37.ditag_feature.ditag_feature_id</code>.
     */
    public void setDitagFeatureId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>homo_sapiens_core_89_37.ditag_feature.ditag_feature_id</code>.
     */
    public UInteger getDitagFeatureId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>homo_sapiens_core_89_37.ditag_feature.ditag_id</code>.
     */
    public void setDitagId(UInteger value) {
        set(1, value);
    }

    /**
     * Getter for <code>homo_sapiens_core_89_37.ditag_feature.ditag_id</code>.
     */
    public UInteger getDitagId() {
        return (UInteger) get(1);
    }

    /**
     * Setter for <code>homo_sapiens_core_89_37.ditag_feature.ditag_pair_id</code>.
     */
    public void setDitagPairId(UInteger value) {
        set(2, value);
    }

    /**
     * Getter for <code>homo_sapiens_core_89_37.ditag_feature.ditag_pair_id</code>.
     */
    public UInteger getDitagPairId() {
        return (UInteger) get(2);
    }

    /**
     * Setter for <code>homo_sapiens_core_89_37.ditag_feature.seq_region_id</code>.
     */
    public void setSeqRegionId(UInteger value) {
        set(3, value);
    }

    /**
     * Getter for <code>homo_sapiens_core_89_37.ditag_feature.seq_region_id</code>.
     */
    public UInteger getSeqRegionId() {
        return (UInteger) get(3);
    }

    /**
     * Setter for <code>homo_sapiens_core_89_37.ditag_feature.seq_region_start</code>.
     */
    public void setSeqRegionStart(UInteger value) {
        set(4, value);
    }

    /**
     * Getter for <code>homo_sapiens_core_89_37.ditag_feature.seq_region_start</code>.
     */
    public UInteger getSeqRegionStart() {
        return (UInteger) get(4);
    }

    /**
     * Setter for <code>homo_sapiens_core_89_37.ditag_feature.seq_region_end</code>.
     */
    public void setSeqRegionEnd(UInteger value) {
        set(5, value);
    }

    /**
     * Getter for <code>homo_sapiens_core_89_37.ditag_feature.seq_region_end</code>.
     */
    public UInteger getSeqRegionEnd() {
        return (UInteger) get(5);
    }

    /**
     * Setter for <code>homo_sapiens_core_89_37.ditag_feature.seq_region_strand</code>.
     */
    public void setSeqRegionStrand(Byte value) {
        set(6, value);
    }

    /**
     * Getter for <code>homo_sapiens_core_89_37.ditag_feature.seq_region_strand</code>.
     */
    public Byte getSeqRegionStrand() {
        return (Byte) get(6);
    }

    /**
     * Setter for <code>homo_sapiens_core_89_37.ditag_feature.analysis_id</code>.
     */
    public void setAnalysisId(UShort value) {
        set(7, value);
    }

    /**
     * Getter for <code>homo_sapiens_core_89_37.ditag_feature.analysis_id</code>.
     */
    public UShort getAnalysisId() {
        return (UShort) get(7);
    }

    /**
     * Setter for <code>homo_sapiens_core_89_37.ditag_feature.hit_start</code>.
     */
    public void setHitStart(UInteger value) {
        set(8, value);
    }

    /**
     * Getter for <code>homo_sapiens_core_89_37.ditag_feature.hit_start</code>.
     */
    public UInteger getHitStart() {
        return (UInteger) get(8);
    }

    /**
     * Setter for <code>homo_sapiens_core_89_37.ditag_feature.hit_end</code>.
     */
    public void setHitEnd(UInteger value) {
        set(9, value);
    }

    /**
     * Getter for <code>homo_sapiens_core_89_37.ditag_feature.hit_end</code>.
     */
    public UInteger getHitEnd() {
        return (UInteger) get(9);
    }

    /**
     * Setter for <code>homo_sapiens_core_89_37.ditag_feature.hit_strand</code>.
     */
    public void setHitStrand(Byte value) {
        set(10, value);
    }

    /**
     * Getter for <code>homo_sapiens_core_89_37.ditag_feature.hit_strand</code>.
     */
    public Byte getHitStrand() {
        return (Byte) get(10);
    }

    /**
     * Setter for <code>homo_sapiens_core_89_37.ditag_feature.cigar_line</code>.
     */
    public void setCigarLine(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>homo_sapiens_core_89_37.ditag_feature.cigar_line</code>.
     */
    public String getCigarLine() {
        return (String) get(11);
    }

    /**
     * Setter for <code>homo_sapiens_core_89_37.ditag_feature.ditag_side</code>.
     */
    public void setDitagSide(DitagFeatureDitagSide value) {
        set(12, value);
    }

    /**
     * Getter for <code>homo_sapiens_core_89_37.ditag_feature.ditag_side</code>.
     */
    public DitagFeatureDitagSide getDitagSide() {
        return (DitagFeatureDitagSide) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<UInteger, UInteger, UInteger, UInteger, UInteger, UInteger, Byte, UShort, UInteger, UInteger, Byte, String, DitagFeatureDitagSide> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<UInteger, UInteger, UInteger, UInteger, UInteger, UInteger, Byte, UShort, UInteger, UInteger, Byte, String, DitagFeatureDitagSide> valuesRow() {
        return (Row13) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return DitagFeature.DITAG_FEATURE.DITAG_FEATURE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field2() {
        return DitagFeature.DITAG_FEATURE.DITAG_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field3() {
        return DitagFeature.DITAG_FEATURE.DITAG_PAIR_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field4() {
        return DitagFeature.DITAG_FEATURE.SEQ_REGION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field5() {
        return DitagFeature.DITAG_FEATURE.SEQ_REGION_START;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field6() {
        return DitagFeature.DITAG_FEATURE.SEQ_REGION_END;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field7() {
        return DitagFeature.DITAG_FEATURE.SEQ_REGION_STRAND;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UShort> field8() {
        return DitagFeature.DITAG_FEATURE.ANALYSIS_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field9() {
        return DitagFeature.DITAG_FEATURE.HIT_START;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field10() {
        return DitagFeature.DITAG_FEATURE.HIT_END;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field11() {
        return DitagFeature.DITAG_FEATURE.HIT_STRAND;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return DitagFeature.DITAG_FEATURE.CIGAR_LINE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<DitagFeatureDitagSide> field13() {
        return DitagFeature.DITAG_FEATURE.DITAG_SIDE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getDitagFeatureId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value2() {
        return getDitagId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value3() {
        return getDitagPairId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value4() {
        return getSeqRegionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value5() {
        return getSeqRegionStart();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value6() {
        return getSeqRegionEnd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value7() {
        return getSeqRegionStrand();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UShort value8() {
        return getAnalysisId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value9() {
        return getHitStart();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value10() {
        return getHitEnd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value11() {
        return getHitStrand();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getCigarLine();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DitagFeatureDitagSide value13() {
        return getDitagSide();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DitagFeatureRecord value1(UInteger value) {
        setDitagFeatureId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DitagFeatureRecord value2(UInteger value) {
        setDitagId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DitagFeatureRecord value3(UInteger value) {
        setDitagPairId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DitagFeatureRecord value4(UInteger value) {
        setSeqRegionId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DitagFeatureRecord value5(UInteger value) {
        setSeqRegionStart(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DitagFeatureRecord value6(UInteger value) {
        setSeqRegionEnd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DitagFeatureRecord value7(Byte value) {
        setSeqRegionStrand(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DitagFeatureRecord value8(UShort value) {
        setAnalysisId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DitagFeatureRecord value9(UInteger value) {
        setHitStart(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DitagFeatureRecord value10(UInteger value) {
        setHitEnd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DitagFeatureRecord value11(Byte value) {
        setHitStrand(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DitagFeatureRecord value12(String value) {
        setCigarLine(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DitagFeatureRecord value13(DitagFeatureDitagSide value) {
        setDitagSide(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DitagFeatureRecord values(UInteger value1, UInteger value2, UInteger value3, UInteger value4, UInteger value5, UInteger value6, Byte value7, UShort value8, UInteger value9, UInteger value10, Byte value11, String value12, DitagFeatureDitagSide value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DitagFeatureRecord
     */
    public DitagFeatureRecord() {
        super(DitagFeature.DITAG_FEATURE);
    }

    /**
     * Create a detached, initialised DitagFeatureRecord
     */
    public DitagFeatureRecord(UInteger ditagFeatureId, UInteger ditagId, UInteger ditagPairId, UInteger seqRegionId, UInteger seqRegionStart, UInteger seqRegionEnd, Byte seqRegionStrand, UShort analysisId, UInteger hitStart, UInteger hitEnd, Byte hitStrand, String cigarLine, DitagFeatureDitagSide ditagSide) {
        super(DitagFeature.DITAG_FEATURE);

        set(0, ditagFeatureId);
        set(1, ditagId);
        set(2, ditagPairId);
        set(3, seqRegionId);
        set(4, seqRegionStart);
        set(5, seqRegionEnd);
        set(6, seqRegionStrand);
        set(7, analysisId);
        set(8, hitStart);
        set(9, hitEnd);
        set(10, hitStrand);
        set(11, cigarLine);
        set(12, ditagSide);
    }
}
