/*
 * This file is generated by jOOQ.
*/
package org.ensembl.database.homo_sapiens_core.tables.records;


import javax.annotation.Generated;

import org.ensembl.database.homo_sapiens_core.tables.DnaAlignFeature;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record17;
import org.jooq.Row17;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;
import org.jooq.types.UShort;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DnaAlignFeatureRecord extends UpdatableRecordImpl<DnaAlignFeatureRecord> implements Record17<UInteger, UInteger, UInteger, UInteger, Byte, Integer, Integer, Byte, String, UShort, Double, Double, Double, String, UInteger, Double, String> {

    private static final long serialVersionUID = -136146245;

    /**
     * Setter for <code>homo_sapiens_core_89_37.dna_align_feature.dna_align_feature_id</code>.
     */
    public void setDnaAlignFeatureId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>homo_sapiens_core_89_37.dna_align_feature.dna_align_feature_id</code>.
     */
    public UInteger getDnaAlignFeatureId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>homo_sapiens_core_89_37.dna_align_feature.seq_region_id</code>.
     */
    public void setSeqRegionId(UInteger value) {
        set(1, value);
    }

    /**
     * Getter for <code>homo_sapiens_core_89_37.dna_align_feature.seq_region_id</code>.
     */
    public UInteger getSeqRegionId() {
        return (UInteger) get(1);
    }

    /**
     * Setter for <code>homo_sapiens_core_89_37.dna_align_feature.seq_region_start</code>.
     */
    public void setSeqRegionStart(UInteger value) {
        set(2, value);
    }

    /**
     * Getter for <code>homo_sapiens_core_89_37.dna_align_feature.seq_region_start</code>.
     */
    public UInteger getSeqRegionStart() {
        return (UInteger) get(2);
    }

    /**
     * Setter for <code>homo_sapiens_core_89_37.dna_align_feature.seq_region_end</code>.
     */
    public void setSeqRegionEnd(UInteger value) {
        set(3, value);
    }

    /**
     * Getter for <code>homo_sapiens_core_89_37.dna_align_feature.seq_region_end</code>.
     */
    public UInteger getSeqRegionEnd() {
        return (UInteger) get(3);
    }

    /**
     * Setter for <code>homo_sapiens_core_89_37.dna_align_feature.seq_region_strand</code>.
     */
    public void setSeqRegionStrand(Byte value) {
        set(4, value);
    }

    /**
     * Getter for <code>homo_sapiens_core_89_37.dna_align_feature.seq_region_strand</code>.
     */
    public Byte getSeqRegionStrand() {
        return (Byte) get(4);
    }

    /**
     * Setter for <code>homo_sapiens_core_89_37.dna_align_feature.hit_start</code>.
     */
    public void setHitStart(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>homo_sapiens_core_89_37.dna_align_feature.hit_start</code>.
     */
    public Integer getHitStart() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>homo_sapiens_core_89_37.dna_align_feature.hit_end</code>.
     */
    public void setHitEnd(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>homo_sapiens_core_89_37.dna_align_feature.hit_end</code>.
     */
    public Integer getHitEnd() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>homo_sapiens_core_89_37.dna_align_feature.hit_strand</code>.
     */
    public void setHitStrand(Byte value) {
        set(7, value);
    }

    /**
     * Getter for <code>homo_sapiens_core_89_37.dna_align_feature.hit_strand</code>.
     */
    public Byte getHitStrand() {
        return (Byte) get(7);
    }

    /**
     * Setter for <code>homo_sapiens_core_89_37.dna_align_feature.hit_name</code>.
     */
    public void setHitName(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>homo_sapiens_core_89_37.dna_align_feature.hit_name</code>.
     */
    public String getHitName() {
        return (String) get(8);
    }

    /**
     * Setter for <code>homo_sapiens_core_89_37.dna_align_feature.analysis_id</code>.
     */
    public void setAnalysisId(UShort value) {
        set(9, value);
    }

    /**
     * Getter for <code>homo_sapiens_core_89_37.dna_align_feature.analysis_id</code>.
     */
    public UShort getAnalysisId() {
        return (UShort) get(9);
    }

    /**
     * Setter for <code>homo_sapiens_core_89_37.dna_align_feature.score</code>.
     */
    public void setScore(Double value) {
        set(10, value);
    }

    /**
     * Getter for <code>homo_sapiens_core_89_37.dna_align_feature.score</code>.
     */
    public Double getScore() {
        return (Double) get(10);
    }

    /**
     * Setter for <code>homo_sapiens_core_89_37.dna_align_feature.evalue</code>.
     */
    public void setEvalue(Double value) {
        set(11, value);
    }

    /**
     * Getter for <code>homo_sapiens_core_89_37.dna_align_feature.evalue</code>.
     */
    public Double getEvalue() {
        return (Double) get(11);
    }

    /**
     * Setter for <code>homo_sapiens_core_89_37.dna_align_feature.perc_ident</code>.
     */
    public void setPercIdent(Double value) {
        set(12, value);
    }

    /**
     * Getter for <code>homo_sapiens_core_89_37.dna_align_feature.perc_ident</code>.
     */
    public Double getPercIdent() {
        return (Double) get(12);
    }

    /**
     * Setter for <code>homo_sapiens_core_89_37.dna_align_feature.cigar_line</code>.
     */
    public void setCigarLine(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>homo_sapiens_core_89_37.dna_align_feature.cigar_line</code>.
     */
    public String getCigarLine() {
        return (String) get(13);
    }

    /**
     * Setter for <code>homo_sapiens_core_89_37.dna_align_feature.external_db_id</code>.
     */
    public void setExternalDbId(UInteger value) {
        set(14, value);
    }

    /**
     * Getter for <code>homo_sapiens_core_89_37.dna_align_feature.external_db_id</code>.
     */
    public UInteger getExternalDbId() {
        return (UInteger) get(14);
    }

    /**
     * Setter for <code>homo_sapiens_core_89_37.dna_align_feature.hcoverage</code>.
     */
    public void setHcoverage(Double value) {
        set(15, value);
    }

    /**
     * Getter for <code>homo_sapiens_core_89_37.dna_align_feature.hcoverage</code>.
     */
    public Double getHcoverage() {
        return (Double) get(15);
    }

    /**
     * Setter for <code>homo_sapiens_core_89_37.dna_align_feature.external_data</code>.
     */
    public void setExternalData(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>homo_sapiens_core_89_37.dna_align_feature.external_data</code>.
     */
    public String getExternalData() {
        return (String) get(16);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record17 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row17<UInteger, UInteger, UInteger, UInteger, Byte, Integer, Integer, Byte, String, UShort, Double, Double, Double, String, UInteger, Double, String> fieldsRow() {
        return (Row17) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row17<UInteger, UInteger, UInteger, UInteger, Byte, Integer, Integer, Byte, String, UShort, Double, Double, Double, String, UInteger, Double, String> valuesRow() {
        return (Row17) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return DnaAlignFeature.DNA_ALIGN_FEATURE.DNA_ALIGN_FEATURE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field2() {
        return DnaAlignFeature.DNA_ALIGN_FEATURE.SEQ_REGION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field3() {
        return DnaAlignFeature.DNA_ALIGN_FEATURE.SEQ_REGION_START;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field4() {
        return DnaAlignFeature.DNA_ALIGN_FEATURE.SEQ_REGION_END;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field5() {
        return DnaAlignFeature.DNA_ALIGN_FEATURE.SEQ_REGION_STRAND;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return DnaAlignFeature.DNA_ALIGN_FEATURE.HIT_START;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return DnaAlignFeature.DNA_ALIGN_FEATURE.HIT_END;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field8() {
        return DnaAlignFeature.DNA_ALIGN_FEATURE.HIT_STRAND;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return DnaAlignFeature.DNA_ALIGN_FEATURE.HIT_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UShort> field10() {
        return DnaAlignFeature.DNA_ALIGN_FEATURE.ANALYSIS_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field11() {
        return DnaAlignFeature.DNA_ALIGN_FEATURE.SCORE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field12() {
        return DnaAlignFeature.DNA_ALIGN_FEATURE.EVALUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field13() {
        return DnaAlignFeature.DNA_ALIGN_FEATURE.PERC_IDENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field14() {
        return DnaAlignFeature.DNA_ALIGN_FEATURE.CIGAR_LINE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field15() {
        return DnaAlignFeature.DNA_ALIGN_FEATURE.EXTERNAL_DB_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field16() {
        return DnaAlignFeature.DNA_ALIGN_FEATURE.HCOVERAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field17() {
        return DnaAlignFeature.DNA_ALIGN_FEATURE.EXTERNAL_DATA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getDnaAlignFeatureId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value2() {
        return getSeqRegionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value3() {
        return getSeqRegionStart();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value4() {
        return getSeqRegionEnd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value5() {
        return getSeqRegionStrand();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getHitStart();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getHitEnd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value8() {
        return getHitStrand();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getHitName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UShort value10() {
        return getAnalysisId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value11() {
        return getScore();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value12() {
        return getEvalue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value13() {
        return getPercIdent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value14() {
        return getCigarLine();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value15() {
        return getExternalDbId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value16() {
        return getHcoverage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value17() {
        return getExternalData();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DnaAlignFeatureRecord value1(UInteger value) {
        setDnaAlignFeatureId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DnaAlignFeatureRecord value2(UInteger value) {
        setSeqRegionId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DnaAlignFeatureRecord value3(UInteger value) {
        setSeqRegionStart(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DnaAlignFeatureRecord value4(UInteger value) {
        setSeqRegionEnd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DnaAlignFeatureRecord value5(Byte value) {
        setSeqRegionStrand(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DnaAlignFeatureRecord value6(Integer value) {
        setHitStart(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DnaAlignFeatureRecord value7(Integer value) {
        setHitEnd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DnaAlignFeatureRecord value8(Byte value) {
        setHitStrand(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DnaAlignFeatureRecord value9(String value) {
        setHitName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DnaAlignFeatureRecord value10(UShort value) {
        setAnalysisId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DnaAlignFeatureRecord value11(Double value) {
        setScore(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DnaAlignFeatureRecord value12(Double value) {
        setEvalue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DnaAlignFeatureRecord value13(Double value) {
        setPercIdent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DnaAlignFeatureRecord value14(String value) {
        setCigarLine(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DnaAlignFeatureRecord value15(UInteger value) {
        setExternalDbId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DnaAlignFeatureRecord value16(Double value) {
        setHcoverage(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DnaAlignFeatureRecord value17(String value) {
        setExternalData(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DnaAlignFeatureRecord values(UInteger value1, UInteger value2, UInteger value3, UInteger value4, Byte value5, Integer value6, Integer value7, Byte value8, String value9, UShort value10, Double value11, Double value12, Double value13, String value14, UInteger value15, Double value16, String value17) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DnaAlignFeatureRecord
     */
    public DnaAlignFeatureRecord() {
        super(DnaAlignFeature.DNA_ALIGN_FEATURE);
    }

    /**
     * Create a detached, initialised DnaAlignFeatureRecord
     */
    public DnaAlignFeatureRecord(UInteger dnaAlignFeatureId, UInteger seqRegionId, UInteger seqRegionStart, UInteger seqRegionEnd, Byte seqRegionStrand, Integer hitStart, Integer hitEnd, Byte hitStrand, String hitName, UShort analysisId, Double score, Double evalue, Double percIdent, String cigarLine, UInteger externalDbId, Double hcoverage, String externalData) {
        super(DnaAlignFeature.DNA_ALIGN_FEATURE);

        set(0, dnaAlignFeatureId);
        set(1, seqRegionId);
        set(2, seqRegionStart);
        set(3, seqRegionEnd);
        set(4, seqRegionStrand);
        set(5, hitStart);
        set(6, hitEnd);
        set(7, hitStrand);
        set(8, hitName);
        set(9, analysisId);
        set(10, score);
        set(11, evalue);
        set(12, percIdent);
        set(13, cigarLine);
        set(14, externalDbId);
        set(15, hcoverage);
        set(16, externalData);
    }
}
