/*
 * This file is generated by jOOQ.
*/
package org.ensembl.database.homo_sapiens_core.tables.records;


import javax.annotation.Generated;

import org.ensembl.database.homo_sapiens_core.tables.ExonTranscript;
import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ExonTranscriptRecord extends UpdatableRecordImpl<ExonTranscriptRecord> implements Record3<UInteger, UInteger, Integer> {

    private static final long serialVersionUID = 1820346636;

    /**
     * Setter for <code>homo_sapiens_core_89_37.exon_transcript.exon_id</code>.
     */
    public void setExonId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>homo_sapiens_core_89_37.exon_transcript.exon_id</code>.
     */
    public UInteger getExonId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>homo_sapiens_core_89_37.exon_transcript.transcript_id</code>.
     */
    public void setTranscriptId(UInteger value) {
        set(1, value);
    }

    /**
     * Getter for <code>homo_sapiens_core_89_37.exon_transcript.transcript_id</code>.
     */
    public UInteger getTranscriptId() {
        return (UInteger) get(1);
    }

    /**
     * Setter for <code>homo_sapiens_core_89_37.exon_transcript.rank</code>.
     */
    public void setRank(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>homo_sapiens_core_89_37.exon_transcript.rank</code>.
     */
    public Integer getRank() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record3<UInteger, UInteger, Integer> key() {
        return (Record3) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<UInteger, UInteger, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<UInteger, UInteger, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return ExonTranscript.EXON_TRANSCRIPT.EXON_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field2() {
        return ExonTranscript.EXON_TRANSCRIPT.TRANSCRIPT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return ExonTranscript.EXON_TRANSCRIPT.RANK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getExonId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value2() {
        return getTranscriptId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getRank();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExonTranscriptRecord value1(UInteger value) {
        setExonId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExonTranscriptRecord value2(UInteger value) {
        setTranscriptId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExonTranscriptRecord value3(Integer value) {
        setRank(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExonTranscriptRecord values(UInteger value1, UInteger value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ExonTranscriptRecord
     */
    public ExonTranscriptRecord() {
        super(ExonTranscript.EXON_TRANSCRIPT);
    }

    /**
     * Create a detached, initialised ExonTranscriptRecord
     */
    public ExonTranscriptRecord(UInteger exonId, UInteger transcriptId, Integer rank) {
        super(ExonTranscript.EXON_TRANSCRIPT);

        set(0, exonId);
        set(1, transcriptId);
        set(2, rank);
    }
}
