/*
 * This file is generated by jOOQ.
*/
package org.ensembl.database.homo_sapiens_core.tables.records;


import javax.annotation.Generated;

import org.ensembl.database.homo_sapiens_core.tables.ExternalSynonym;
import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ExternalSynonymRecord extends UpdatableRecordImpl<ExternalSynonymRecord> implements Record2<UInteger, String> {

    private static final long serialVersionUID = 1635527105;

    /**
     * Setter for <code>homo_sapiens_core_89_37.external_synonym.xref_id</code>.
     */
    public void setXrefId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>homo_sapiens_core_89_37.external_synonym.xref_id</code>.
     */
    public UInteger getXrefId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>homo_sapiens_core_89_37.external_synonym.synonym</code>.
     */
    public void setSynonym(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>homo_sapiens_core_89_37.external_synonym.synonym</code>.
     */
    public String getSynonym() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<UInteger, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<UInteger, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<UInteger, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return ExternalSynonym.EXTERNAL_SYNONYM.XREF_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return ExternalSynonym.EXTERNAL_SYNONYM.SYNONYM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getXrefId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getSynonym();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExternalSynonymRecord value1(UInteger value) {
        setXrefId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExternalSynonymRecord value2(String value) {
        setSynonym(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExternalSynonymRecord values(UInteger value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ExternalSynonymRecord
     */
    public ExternalSynonymRecord() {
        super(ExternalSynonym.EXTERNAL_SYNONYM);
    }

    /**
     * Create a detached, initialised ExternalSynonymRecord
     */
    public ExternalSynonymRecord(UInteger xrefId, String synonym) {
        super(ExternalSynonym.EXTERNAL_SYNONYM);

        set(0, xrefId);
        set(1, synonym);
    }
}
