/*
 * This file is generated by jOOQ.
*/
package org.ensembl.database.homo_sapiens_core.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.ensembl.database.homo_sapiens_core.tables.GenomeStatistics;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GenomeStatisticsRecord extends UpdatableRecordImpl<GenomeStatisticsRecord> implements Record6<UInteger, String, ULong, UInteger, UInteger, Timestamp> {

    private static final long serialVersionUID = -436885264;

    /**
     * Setter for <code>homo_sapiens_core_89_37.genome_statistics.genome_statistics_id</code>.
     */
    public void setGenomeStatisticsId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>homo_sapiens_core_89_37.genome_statistics.genome_statistics_id</code>.
     */
    public UInteger getGenomeStatisticsId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>homo_sapiens_core_89_37.genome_statistics.statistic</code>.
     */
    public void setStatistic(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>homo_sapiens_core_89_37.genome_statistics.statistic</code>.
     */
    public String getStatistic() {
        return (String) get(1);
    }

    /**
     * Setter for <code>homo_sapiens_core_89_37.genome_statistics.value</code>.
     */
    public void setValue(ULong value) {
        set(2, value);
    }

    /**
     * Getter for <code>homo_sapiens_core_89_37.genome_statistics.value</code>.
     */
    public ULong getValue() {
        return (ULong) get(2);
    }

    /**
     * Setter for <code>homo_sapiens_core_89_37.genome_statistics.species_id</code>.
     */
    public void setSpeciesId(UInteger value) {
        set(3, value);
    }

    /**
     * Getter for <code>homo_sapiens_core_89_37.genome_statistics.species_id</code>.
     */
    public UInteger getSpeciesId() {
        return (UInteger) get(3);
    }

    /**
     * Setter for <code>homo_sapiens_core_89_37.genome_statistics.attrib_type_id</code>.
     */
    public void setAttribTypeId(UInteger value) {
        set(4, value);
    }

    /**
     * Getter for <code>homo_sapiens_core_89_37.genome_statistics.attrib_type_id</code>.
     */
    public UInteger getAttribTypeId() {
        return (UInteger) get(4);
    }

    /**
     * Setter for <code>homo_sapiens_core_89_37.genome_statistics.timestamp</code>.
     */
    public void setTimestamp(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>homo_sapiens_core_89_37.genome_statistics.timestamp</code>.
     */
    public Timestamp getTimestamp() {
        return (Timestamp) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<UInteger, String, ULong, UInteger, UInteger, Timestamp> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<UInteger, String, ULong, UInteger, UInteger, Timestamp> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return GenomeStatistics.GENOME_STATISTICS.GENOME_STATISTICS_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return GenomeStatistics.GENOME_STATISTICS.STATISTIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field3() {
        return GenomeStatistics.GENOME_STATISTICS.VALUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field4() {
        return GenomeStatistics.GENOME_STATISTICS.SPECIES_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field5() {
        return GenomeStatistics.GENOME_STATISTICS.ATTRIB_TYPE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return GenomeStatistics.GENOME_STATISTICS.TIMESTAMP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getGenomeStatisticsId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getStatistic();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value3() {
        return getValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value4() {
        return getSpeciesId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value5() {
        return getAttribTypeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getTimestamp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GenomeStatisticsRecord value1(UInteger value) {
        setGenomeStatisticsId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GenomeStatisticsRecord value2(String value) {
        setStatistic(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GenomeStatisticsRecord value3(ULong value) {
        setValue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GenomeStatisticsRecord value4(UInteger value) {
        setSpeciesId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GenomeStatisticsRecord value5(UInteger value) {
        setAttribTypeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GenomeStatisticsRecord value6(Timestamp value) {
        setTimestamp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GenomeStatisticsRecord values(UInteger value1, String value2, ULong value3, UInteger value4, UInteger value5, Timestamp value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GenomeStatisticsRecord
     */
    public GenomeStatisticsRecord() {
        super(GenomeStatistics.GENOME_STATISTICS);
    }

    /**
     * Create a detached, initialised GenomeStatisticsRecord
     */
    public GenomeStatisticsRecord(UInteger genomeStatisticsId, String statistic, ULong value, UInteger speciesId, UInteger attribTypeId, Timestamp timestamp) {
        super(GenomeStatistics.GENOME_STATISTICS);

        set(0, genomeStatisticsId);
        set(1, statistic);
        set(2, value);
        set(3, speciesId);
        set(4, attribTypeId);
        set(5, timestamp);
    }
}
