/*
 * This file is generated by jOOQ.
*/
package org.ensembl.database.homo_sapiens_core.tables.records;


import javax.annotation.Generated;

import org.ensembl.database.homo_sapiens_core.tables.IdentityXref;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IdentityXrefRecord extends UpdatableRecordImpl<IdentityXrefRecord> implements Record10<UInteger, Integer, Integer, Integer, Integer, Integer, Integer, String, Double, Double> {

    private static final long serialVersionUID = -1668031808;

    /**
     * Setter for <code>homo_sapiens_core_89_37.identity_xref.object_xref_id</code>.
     */
    public void setObjectXrefId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>homo_sapiens_core_89_37.identity_xref.object_xref_id</code>.
     */
    public UInteger getObjectXrefId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>homo_sapiens_core_89_37.identity_xref.xref_identity</code>.
     */
    public void setXrefIdentity(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>homo_sapiens_core_89_37.identity_xref.xref_identity</code>.
     */
    public Integer getXrefIdentity() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>homo_sapiens_core_89_37.identity_xref.ensembl_identity</code>.
     */
    public void setEnsemblIdentity(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>homo_sapiens_core_89_37.identity_xref.ensembl_identity</code>.
     */
    public Integer getEnsemblIdentity() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>homo_sapiens_core_89_37.identity_xref.xref_start</code>.
     */
    public void setXrefStart(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>homo_sapiens_core_89_37.identity_xref.xref_start</code>.
     */
    public Integer getXrefStart() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>homo_sapiens_core_89_37.identity_xref.xref_end</code>.
     */
    public void setXrefEnd(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>homo_sapiens_core_89_37.identity_xref.xref_end</code>.
     */
    public Integer getXrefEnd() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>homo_sapiens_core_89_37.identity_xref.ensembl_start</code>.
     */
    public void setEnsemblStart(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>homo_sapiens_core_89_37.identity_xref.ensembl_start</code>.
     */
    public Integer getEnsemblStart() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>homo_sapiens_core_89_37.identity_xref.ensembl_end</code>.
     */
    public void setEnsemblEnd(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>homo_sapiens_core_89_37.identity_xref.ensembl_end</code>.
     */
    public Integer getEnsemblEnd() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>homo_sapiens_core_89_37.identity_xref.cigar_line</code>.
     */
    public void setCigarLine(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>homo_sapiens_core_89_37.identity_xref.cigar_line</code>.
     */
    public String getCigarLine() {
        return (String) get(7);
    }

    /**
     * Setter for <code>homo_sapiens_core_89_37.identity_xref.score</code>.
     */
    public void setScore(Double value) {
        set(8, value);
    }

    /**
     * Getter for <code>homo_sapiens_core_89_37.identity_xref.score</code>.
     */
    public Double getScore() {
        return (Double) get(8);
    }

    /**
     * Setter for <code>homo_sapiens_core_89_37.identity_xref.evalue</code>.
     */
    public void setEvalue(Double value) {
        set(9, value);
    }

    /**
     * Getter for <code>homo_sapiens_core_89_37.identity_xref.evalue</code>.
     */
    public Double getEvalue() {
        return (Double) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<UInteger, Integer, Integer, Integer, Integer, Integer, Integer, String, Double, Double> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<UInteger, Integer, Integer, Integer, Integer, Integer, Integer, String, Double, Double> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return IdentityXref.IDENTITY_XREF.OBJECT_XREF_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return IdentityXref.IDENTITY_XREF.XREF_IDENTITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return IdentityXref.IDENTITY_XREF.ENSEMBL_IDENTITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return IdentityXref.IDENTITY_XREF.XREF_START;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return IdentityXref.IDENTITY_XREF.XREF_END;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return IdentityXref.IDENTITY_XREF.ENSEMBL_START;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return IdentityXref.IDENTITY_XREF.ENSEMBL_END;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return IdentityXref.IDENTITY_XREF.CIGAR_LINE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field9() {
        return IdentityXref.IDENTITY_XREF.SCORE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field10() {
        return IdentityXref.IDENTITY_XREF.EVALUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getObjectXrefId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getXrefIdentity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getEnsemblIdentity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getXrefStart();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getXrefEnd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getEnsemblStart();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getEnsemblEnd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getCigarLine();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value9() {
        return getScore();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value10() {
        return getEvalue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IdentityXrefRecord value1(UInteger value) {
        setObjectXrefId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IdentityXrefRecord value2(Integer value) {
        setXrefIdentity(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IdentityXrefRecord value3(Integer value) {
        setEnsemblIdentity(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IdentityXrefRecord value4(Integer value) {
        setXrefStart(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IdentityXrefRecord value5(Integer value) {
        setXrefEnd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IdentityXrefRecord value6(Integer value) {
        setEnsemblStart(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IdentityXrefRecord value7(Integer value) {
        setEnsemblEnd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IdentityXrefRecord value8(String value) {
        setCigarLine(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IdentityXrefRecord value9(Double value) {
        setScore(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IdentityXrefRecord value10(Double value) {
        setEvalue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IdentityXrefRecord values(UInteger value1, Integer value2, Integer value3, Integer value4, Integer value5, Integer value6, Integer value7, String value8, Double value9, Double value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached IdentityXrefRecord
     */
    public IdentityXrefRecord() {
        super(IdentityXref.IDENTITY_XREF);
    }

    /**
     * Create a detached, initialised IdentityXrefRecord
     */
    public IdentityXrefRecord(UInteger objectXrefId, Integer xrefIdentity, Integer ensemblIdentity, Integer xrefStart, Integer xrefEnd, Integer ensemblStart, Integer ensemblEnd, String cigarLine, Double score, Double evalue) {
        super(IdentityXref.IDENTITY_XREF);

        set(0, objectXrefId);
        set(1, xrefIdentity);
        set(2, ensemblIdentity);
        set(3, xrefStart);
        set(4, xrefEnd);
        set(5, ensemblStart);
        set(6, ensemblEnd);
        set(7, cigarLine);
        set(8, score);
        set(9, evalue);
    }
}
