/*
 * This file is generated by jOOQ.
*/
package org.ensembl.database.homo_sapiens_core.tables.records;


import javax.annotation.Generated;

import org.ensembl.database.homo_sapiens_core.tables.TranscriptAttrib;
import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.TableRecordImpl;
import org.jooq.types.UInteger;
import org.jooq.types.UShort;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TranscriptAttribRecord extends TableRecordImpl<TranscriptAttribRecord> implements Record3<UInteger, UShort, String> {

    private static final long serialVersionUID = 1308644490;

    /**
     * Setter for <code>homo_sapiens_core_89_37.transcript_attrib.transcript_id</code>.
     */
    public void setTranscriptId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>homo_sapiens_core_89_37.transcript_attrib.transcript_id</code>.
     */
    public UInteger getTranscriptId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>homo_sapiens_core_89_37.transcript_attrib.attrib_type_id</code>.
     */
    public void setAttribTypeId(UShort value) {
        set(1, value);
    }

    /**
     * Getter for <code>homo_sapiens_core_89_37.transcript_attrib.attrib_type_id</code>.
     */
    public UShort getAttribTypeId() {
        return (UShort) get(1);
    }

    /**
     * Setter for <code>homo_sapiens_core_89_37.transcript_attrib.value</code>.
     */
    public void setValue(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>homo_sapiens_core_89_37.transcript_attrib.value</code>.
     */
    public String getValue() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<UInteger, UShort, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<UInteger, UShort, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return TranscriptAttrib.TRANSCRIPT_ATTRIB.TRANSCRIPT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UShort> field2() {
        return TranscriptAttrib.TRANSCRIPT_ATTRIB.ATTRIB_TYPE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TranscriptAttrib.TRANSCRIPT_ATTRIB.VALUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getTranscriptId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UShort value2() {
        return getAttribTypeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TranscriptAttribRecord value1(UInteger value) {
        setTranscriptId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TranscriptAttribRecord value2(UShort value) {
        setAttribTypeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TranscriptAttribRecord value3(String value) {
        setValue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TranscriptAttribRecord values(UInteger value1, UShort value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TranscriptAttribRecord
     */
    public TranscriptAttribRecord() {
        super(TranscriptAttrib.TRANSCRIPT_ATTRIB);
    }

    /**
     * Create a detached, initialised TranscriptAttribRecord
     */
    public TranscriptAttribRecord(UInteger transcriptId, UShort attribTypeId, String value) {
        super(TranscriptAttrib.TRANSCRIPT_ATTRIB);

        set(0, transcriptId);
        set(1, attribTypeId);
        set(2, value);
    }
}
