package com.hartwig.hmftools.healthchecker;

public enum QCValueType
{
    REF_COVERAGE_10X,
    REF_COVERAGE_20X,
    TUM_COVERAGE_30X,
    TUM_COVERAGE_60X,
    REF_PROPORTION_MAPPED,
    TUM_PROPORTION_MAPPED,
    REF_PROPORTION_DUPLICATE,
    TUM_PROPORTION_DUPLICATE,
    PURPLE_QC_STATUS,
    PURPLE_CONTAMINATION
}
