package com.hartwig.hmftools.peach;

public enum PeachQCStatus
{
    PASS,
    FAIL_NO_COMBINATION_FOUND,
    FAIL_NO_UNIQUE_BEST_COMBINATION_FOUND,
    FAIL_EVENT_WITH_UNKNOWN_COUNT,
    WARN_TOO_MANY_ALLELES_FOUND
}
