#!/bin/bash

purple_jar=$1 && shift
tumor_id=$1 && shift
reference_id=$1 && shift
sv_vcf=$1 && shift
sv_unfiltered_vcf=$1 && shift
somatic_vcf=$1 && shift
germline_vcf=$1 && shift
amber_dir=$1 && shift
cobalt_dir=$1 && shift
output_dir=$1 && shift
ref_genome_version=$1 && shift
ref_genome=$1 && shift
gc_profile=$1 && shift
somatic_hotspots=$1 && shift
germline_hotspots=$1 && shift
driver_gene_panel=$1 && shift
ensembl_data_dir=$1 && shift
germline_del_freq_file=$1 && shift
threads=$1 && shift
circos=$1 && shift

if [[ ! -d "${output_dir}" ]]; then
  mkdir ${output_dir}
fi

purity_tsv=${output_dir}/${tumor_id}.purple.purity.tsv

if [[ -f "${purity_tsv}" ]]; then
  echo "Skipping Purple for ${tumor_id}, since purity file ${purity_tsv} exists"
  exit
fi

echo "Running Purple for ${tumor_id}, output dir ${output_dir}"

java -jar ${purple_jar} \
  -tumor ${tumor_id} \
  -reference ${reference_id} \
  -ref_genome ${ref_genome} \
  -ref_genome_version ${ref_genome_version} \
  -gc_profile ${gc_profile} \
  -somatic_hotspots ${somatic_hotspots} \
  -germline_hotspots ${germline_hotspots} \
  -driver_gene_panel ${driver_gene_panel} \
  -ensembl_data_dir ${ensembl_data_dir} \
  -germline_del_freq_file ${germline_del_freq_file} \
  -amber ${amber_dir} \
  -cobalt ${cobalt_dir} \
  -structural_vcf ${sv_vcf} \
  -sv_recovery_vcf ${sv_unfiltered_vcf} \
  -somatic_vcf ${somatic_vcf} \
  -germline_vcf ${germline_vcf} \
  -run_drivers \
  -circos {circos} \
  -threads ${threads} \
  -output_dir ${output_dir} \
  
