#!/bin/bash

gripss_jar=$1 && shift
tumor_id=$1 && shift
reference_id=$1 && shift
output_dir=$1 && shift
gridss_vcf=$1 && shift
run_mode=$1 && shift
ref_genome_version=$1 && shift
ref_genome=$1 && shift
known_hotspot_file=$1 && shift
pon_sv_file=$1 && shift
pon_sgl_file=$1 && shift
repeat_mask_file=$1 && shift

if [[ ! -d "${output_dir}" ]]; then
  mkdir ${output_dir}
fi

output_vcf=${output_dir}/${tumor_id}.gripss.filtered.somatic.vcf.gz

if [[ -f "${output_vcf}" ]]; then
  echo "Skipping Gripss somatic for ${tumor_id}, since VCF ${output_vcf} exists"
  exit
fi

if [[ ! -f "${gridss_vcf}" ]]; then
  echo "Missing Gridss VCF, not running Gripss somatic for ${tumor_id}"
  exit
fi

args="-sample ${tumor_id}"

if [ "${reference_id}" != "none" ]; then
  args="${args} -reference ${reference_id}"
fi  

args="${args} -ref_genome ${ref_genome} \
  -ref_genome_version ${ref_genome_version} \
  -known_hotspot_file ${known_hotspot_file} \
  -pon_sv_file ${pon_sv_file} \
  -pon_sgl_file ${pon_sgl_file} \
  -repeat_mask_file ${repeat_mask_file} \
  -vcf ${gridss_vcf} \
  -output_dir ${output_dir}"

if [ "${run_mode}" == "PANEL" ]; then
  args="${args} -filter_sgls
    -hard_min_tumor_qual 200 -min_qual_break_point 1000 -min_qual_break_end 1000"
fi

if [ ! "${reference_id}" == "" ]; then
  args="${args} -output_id somatic"
fi  

echo "Running Gripss with args: ${args}"

java -jar ${gripss_jar} ${args}
