#!/bin/bash

# example command:
# ./pipeline/scripts/run_pipeline ./pipeline/scripts /sample_data_dir/ /ref_data_dir/ /tools_dir/ "COLO829T,COLO829R" V37 5

# required arguments
scripts_dir=$1 && shift
samples_dir=$1 && shift
resources_dir=$1 && shift
tools_dir=$1 && shift
sample_data=$1 && shift
ref_genome_version=$1 && shift
threads=$1 && shift

sample_array=($(echo $sample_data | tr "," " "))
tumor_id=${sample_array[0]}
reference_id=${sample_array[1]}

echo "Environment:"
echo "  scripts dir: ${scripts_dir}"
echo "  samples dir: ${samples_dir}"
echo "  resources dir: ${resources_dir}"
echo "  tools dir: ${tools_dir}"
echo "  tumorId: ${tumor_id}"
echo "  referenceId: ${reference_id}"
echo "  ref genome version: ${ref_genome_version}"
echo "  threads: ${threads}"

sample_dir=${samples_dir}/${tumor_id}

# assume BAM names match tumor and reference names
tumor_bam=${sample_dir}/${tumor_id}.bam
reference_bam=${sample_dir}/${reference_id}.bam

echo "Sample output dir: ${sample_dir}"

if [[ ! -d "${sample_dir}" ]]; then
  mkdir ${sample_dir}
fi

# set resource files
#  | [ "${ref_genome_version}" == "37" ]
if [ "${ref_genome_version}" == "V37" ]; then
  echo "Reference genome version GRCh37"

  ref_genome_dir='37'

  # Common
  ref_genome=${resources_dir}/ref_genome/${ref_genome_dir}/Homo_sapiens.GRCh37.GATK.illumina.fasta
  ensembl_dir=${resources_dir}/ensembl_data_cache/${ref_genome_dir}/
  driver_gene_panel=${resources_dir}/gene_panel/${ref_genome_dir}/DriverGenePanel.37.tsv

  # Sage
  sage_somatic_hotspots=${resources_dir}/sage/${ref_genome_dir}/KnownHotspots.somatic.37.vcf.gz
  sage_germline_hotspots=${resources_dir}/sage/${ref_genome_dir}/KnownHotspots.germline.37.vcf.gz
  sage_somatic_panel_bed=${resources_dir}/sage/${ref_genome_dir}/ActionableCodingPanel.somatic.37.bed.gz
  sage_germline_panel_bed=${resources_dir}/sage/${ref_genome_dir}/ActionableCodingPanel.germline.37.bed.gz
  high_confidence_bed=${resources_dir}/giab_high_conf/${ref_genome_dir}/NA12878_GIAB_highconf_IllFB-IllGATKHC-CG-Ion-Solid_ALLCHROM_v3.2.2_highconf.bed.gz

  # Pave
  somatic_pon_file=${resources_dir}/sage/${ref_genome_dir}/SageGermlinePon.1000x.37.tsv.gz
  mappability_bed=${resources_dir}/mappability/${ref_genome_dir}/mappability_150.37.bed.gz
  clinvar_vcf=${resources_dir}/sage/${ref_genome_dir}/clinvar.37.vcf.gz
  germline_blacklist_bed=${resources_dir}/sage/${ref_genome_dir}/KnownBlacklist.germline.37.bed
  germline_blacklist_vcf=${resources_dir}/sage/${ref_genome_dir}/KnownBlacklist.germline.37.vcf.gz

  # Gripss
  sv_hotspot_file=${resources_dir}/fusions/${ref_genome_dir}/known_fusions.37.bedpe
  sv_pon_file=${resources_dir}/gridss_pon/${ref_genome_dir}/gridss_pon_breakpoint.37.bedpe.gz
  sgl_pon_file=${resources_dir}/gridss_pon/${ref_genome_dir}/gridss_pon_single_breakend.37.bed.gz

  # Amber
  amber_loci_vcf=${resources_dir}/amber/${ref_genome_dir}/GermlineHetPon.37.vcf.gz

  # Cobalt
  gc_profile=${resources_dir}/gc_profiles/${ref_genome_dir}/GC_profile.1000bp.37.cnp

  # Purple
  germline_del_freq_file=${resources_dir}/purple/${ref_genome_dir}/cohort_germline_del_freq.37.csv

  # Linx
  fragile_site_file=${resources_dir}/linx/${ref_genome_dir}/fragile_sites_hmf.37.csv
  line_element_file=${resources_dir}/linx/${ref_genome_dir}/line_elements.37.csv
  known_fusion_file=${resources_dir}/fusions/${ref_genome_dir}/known_fusion_data.37.csv

fi

# set tool links
sage_jar=${tools_dir}/sage.jar
pave_jar=${tools_dir}/pave.jar
amber_jar=${tools_dir}/amber.jar
gripss_jar=${tools_dir}/gripss.jar
cobalt_jar=${tools_dir}/cobalt.jar
purple_jar=${tools_dir}/purple.jar
linx_jar=${tools_dir}/linx.jar


# Sage somatic
sage_somatic_dir=${sample_dir}/sage_somatic

${scripts_dir}/run_sage_somatic ${sage_jar} \
  ${tumor_id} ${tumor_bam} ${reference_id} ${reference_bam} \
  ${sage_somatic_dir} \
  ${ref_genome_version} ${ref_genome} \
  ${ensembl_dir} ${sage_somatic_hotspots} ${sage_somatic_panel_bed} ${high_confidence_bed} \
  ${threads} \


# Sage germline
sage_germline_dir=${sample_dir}/sage_germline

${scripts_dir}/run_sage_germline ${sage_jar} \
  ${tumor_id} ${tumor_bam} ${reference_id} ${reference_bam} \
  ${sage_germline_dir} \
  ${ref_genome_version} ${ref_genome} \
  ${ensembl_dir} ${sage_germline_hotspots} ${sage_germline_panel_bed} ${high_confidence_bed} \
  ${threads} \


# Pave somatic
pave_somatic_dir=${sample_dir}/pave_somatic

${scripts_dir}/run_pave_somatic ${pave_jar} \
  ${tumor_id}  \
  ${sage_somatic_dir} ${pave_somatic_dir} \
  ${ref_genome_version} ${ref_genome} \
  ${ensembl_dir} ${driver_gene_panel} ${somatic_pon_file} ${mappability_bed} \
  

# Pave germline
pave_germline_dir=${sample_dir}/pave_germline

${scripts_dir}/run_pave_germline ${pave_jar} \
  ${tumor_id}  \
  ${sage_germline_dir} ${pave_germline_dir} \
  ${ref_genome_version} ${ref_genome} \
  ${ensembl_dir} ${driver_gene_panel} ${mappability_bed} ${clinvar_vcf} ${germline_blacklist_bed} ${germline_blacklist_vcf} \


# Assume GRIDSS has been run separately
gridss_vcf=${sample_dir}/gridss/${tumor_id}.gridss.unfiltered.vcf.gz

# Gripss somatic
gripss_somatic_dir=${sample_dir}/gripss_somatic

${scripts_dir}/run_gripss_somatic ${gripss_jar} \
  ${tumor_id}  ${reference_id} \
  ${gripss_somatic_dir} ${gridss_vcf} \
  ${ref_genome_version} ${ref_genome} \
  ${sv_hotspot_file} ${sv_pon_file} ${sgl_pon_file} \


# Gripss germline
gripss_germline_dir=${sample_dir}/gripss_germline

${scripts_dir}/run_gripss_germline ${gripss_jar} \
  ${reference_id} \
  ${gripss_germline_dir} ${gridss_vcf} \
  ${ref_genome_version} ${ref_genome} \
  ${sv_hotspot_file} ${sv_pon_file} ${sgl_pon_file} \


# Amber
amber_dir=${sample_dir}/amber

${scripts_dir}/run_amber ${amber_jar} \
  ${tumor_id} ${tumor_bam} ${reference_id} ${reference_bam} \
  ${amber_dir} \
  ${ref_genome_version} ${ref_genome} \
  ${amber_loci_vcf} ${threads} \


# Cobalt
cobalt_dir=${sample_dir}/cobalt

${scripts_dir}/run_cobalt ${cobalt_jar} \
  ${tumor_id} ${tumor_bam} ${reference_id} ${reference_bam} \
  ${cobalt_dir} \
  ${ref_genome} ${gc_profile} \
  ${threads} \


# Purple
purple_dir=${sample_dir}/purple

sv_vcf=${gripss_somatic_dir}/${tumor_id}.gripss.filtered.somatic.vcf.gz
sv_unfiltered_vcf=${gripss_somatic_dir}/${tumor_id}.gripss.somatic.vcf.gz
somatic_vcf=${pave_somatic_dir}/${tumor_id}.sage.somatic.pave.vcf.gz
germline_vcf=${pave_germline_dir}/${tumor_id}.sage.germline.pave.vcf.gz

${scripts_dir}/run_purple ${purple_jar} \
  ${tumor_id} ${reference_id} \
  ${sv_vcf} ${sv_unfiltered_vcf} ${somatic_vcf} ${germline_vcf} ${amber_dir} ${cobalt_dir}  ${purple_dir} \
  ${ref_genome_version} ${ref_genome} ${gc_profile} ${sage_somatic_hotspots} ${sage_germline_hotspots} \
  ${driver_gene_panel} ${ensembl_dir} ${germline_del_freq_file} \
  ${threads} \


# Linx somatic
linx_somatic_dir=${sample_dir}/linx_somatic

sv_vcf=${purple_dir}/${tumor_id}.purple.sv.vcf.gz

${scripts_dir}/run_linx_somatic ${linx_jar} \
  ${tumor_id} \
  ${sv_vcf} ${purple_dir} ${linx_somatic_dir} \
  ${ref_genome_version} ${fragile_site_file} ${line_element_file} ${ensembl_dir} ${driver_gene_panel} ${known_fusion_file} \


# Linx germline
linx_germline_dir=${sample_dir}/linx_germline

sv_germline_vcf=${gripss_germline_dir}/${reference_id}.gripss.filtered.germline.vcf.gz

${scripts_dir}/run_linx_germline ${linx_jar} \
  ${reference_id} \
  ${sv_germline_vcf} ${linx_germline_dir} \
  ${ref_genome_version} ${line_element_file} ${ensembl_dir} ${driver_gene_panel} \




