#!/bin/bash

linx_jar=$1 && shift
tumor_id=$1 && shift
sv_vcf=$1 && shift
output_dir=$1 && shift
ref_genome_version=$1 && shift
line_element_file=$1 && shift
ensembl_dir=$1 && shift
driver_gene_panel=$1 && shift

if [[ ! -d "${output_dir}" ]]; then
  mkdir ${output_dir}
fi

svs_tsv=${output_dir}/${tumor_id}.linx.svs.tsv

if [[ -f "${svs_tsv}" ]]; then
  echo "Skipping Linx germline for ${tumor_id}, since SV annotations file ${svs_tsv} exists"
  exit
fi

echo "Running Linx germline for ${tumor_id}, output dir ${output_dir}"


java -jar ${linx_jar} \
  -sample ${tumor_id} \
  -germline \
  -sv_vcf ${sv_vcf} \
  -ref_genome_version ${ref_genome_version} \
  -line_element_file ${line_element_file} \
  -ensembl_data_dir ${ensembl_dir} \
  -driver_gene_panel ${driver_gene_panel} \
  -output_dir ${output_dir} \
