#!/bin/bash

lilac_jar=$1 && shift
tumor_id=$1 && shift
tumor_bam=$1 && shift
reference_id=$1 && shift
reference_bam=$1 && shift
gene_copy_number_file=$1 && shift
somatic_vcf=$1 && shift
output_dir=$1 && shift
ref_genome_version=$1 && shift
ref_genome=$1 && shift
resource_dir=$1 && shift
threads=$1 && shift

if [[ ! -d "${output_dir}" ]]; then
  mkdir ${output_dir}
fi

lilac_tsv=${output_dir}/${tumor_id}.lilac.csv

if [[ -f "${lilac_tsv}" ]]; then
  echo "Skipping Lilac for ${tumor_id}, since results file ${lilac_tsv} exists"
  exit
fi

echo "Running Lilac for ${reference_id} and ${tumor_id}, output dir ${output_dir}"

java -jar ${lilac_jar} \
  -sample ${tumor_id} \
  -reference_bam ${reference_bam} \
  -tumor_bam ${tumor_bam} \
  -ref_genome_version ${ref_genome_version} \
  -ref_genome ${ref_genome} \
  -resource_dir ${resource_dir} \
  -gene_copy_number ${gene_copy_number_file} \
  -somatic_vcf ${somatic_vcf} \
  -threads ${threads} \
  -output_dir ${output_dir} \
