#!/bin/bash

sage_jar=$1 && shift
tumor_id=$1 && shift
tumor_bam=$1 && shift
reference_id=$1 && shift
reference_bam=$1 && shift
output_dir=$1 && shift
sage_vcf=$1 && shift
run_mode=$1 && shift
ref_genome_version=$1 && shift
ref_genome=$1 && shift
ensembl_dir=$1 && shift
hotspots=$1 && shift
panel_bed=$1 && shift
coverage_bed=$1 && shift
high_confidence_bed=$1 && shift
threads=$1 && shift
max_memory=$1 && shift

if [[ ! -d "${output_dir}" ]]; then
  mkdir ${output_dir}
fi

if [[ -f "${sage_vcf}" ]]; then
  echo "Skipping Sage somatic for ${tumor_id}, since VCF ${sage_vcf} exists"
  exit
fi

args="-tumor ${tumor_id} -tumor_bam ${tumor_bam}"

if [ "${reference_id}" != "none" ]; then
  args="${args} -reference ${reference_id} -reference_bam ${reference_bam}"
fi  

args="${args} -hotspots ${hotspots} \
  -panel_bed ${panel_bed} \
  -coverage_bed ${coverage_bed} \
  -high_confidence_bed ${high_confidence_bed} \
  -ref_genome ${ref_genome} \
  -ref_genome_version ${ref_genome_version} \
  -ensembl_data_dir ${ensembl_dir} \
  -bqr_write_plot \
  -output_vcf ${sage_vcf} \
  -threads ${threads}"

if [ "${run_mode}" == "PANEL" ]; then
  args="${args} -high_depth_mode"
fi  

# optional: -write_bqr_plot

echo "Running Sage somatic with args: ${args}"

java -Xmx${max_memory}G -jar ${sage_jar} ${args}

