#!/bin/bash

amber_jar=$1 && shift
tumor_id=$1 && shift
tumor_bam=$1 && shift
reference_id=$1 && shift
reference_bam=$1 && shift
output_dir=$1 && shift
ref_genome_version=$1 && shift
ref_genome=$1 && shift
loci_vcf=$1 && shift
threads=$1 && shift

output_tsv=${output_dir}/${tumor_id}.amber.baf.tsv.gz

if [[ -f "${output_tsv}" ]]; then
  echo "Skipping Amber for ${tumor_id}, since output ${output_tsv} exists"
  exit
fi

echo "Running Amber for ${tumor_id}, output dir ${output_dir}"

if [[ ! -d "${output_dir}" ]]; then
  mkdir ${output_dir}
fi

java -jar ${amber_jar} \
  -tumor ${tumor_id} \
  -tumor_bam ${tumor_bam} \
  -reference ${reference_id} \
  -reference_bam ${reference_bam} \
  -ref_genome ${ref_genome} \
  -ref_genome_version ${ref_genome_version} \
  -loci ${loci_vcf} \
  -threads ${threads} \
  -output_dir ${output_dir} \

