#!/bin/bash

linx_jar=$1 && shift
tumor_id=$1 && shift
sv_vcf=$1 && shift
purple_dir=$1 && shift
output_dir=$1 && shift
ref_genome_version=$1 && shift
ensembl_dir=$1 && shift
driver_gene_panel=$1 && shift
known_fusion_file=$1 && shift
circos=$1 && shift

if [[ ! -d "${output_dir}" ]]; then
  mkdir ${output_dir}
fi

svs_tsv=${output_dir}/${tumor_id}.linx.svs.tsv

if [[ -f "${svs_tsv}" ]]; then
  echo "Skipping Linx somatic for ${tumor_id}, since SV annotations file ${svs_tsv} exists"
  exit
fi

if [[ ! -f "${sv_vcf}" ]]; then
  echo "Missing Purple SV VCF, not running Linx somatic for ${tumor_id}"
  exit
fi

echo "Running Linx somatic for ${tumor_id}, output dir ${output_dir}"

args="-sample ${tumor_id} \
  -sv_vcf ${sv_vcf} \
  -purple_dir ${purple_dir} \
  -ref_genome_version ${ref_genome_version} \
  -ensembl_data_dir ${ensembl_dir} \
  -known_fusion_file ${known_fusion_file} \
  -driver_gene_panel ${driver_gene_panel} \
  -output_dir ${output_dir}"

echo "Running Linx somatic with args: ${args}"


java -jar ${linx_jar} ${args}


# run the visualiser to create Circos plots for each chromosome and non-trivial cluster
java -cp ${linx_jar} com.hartwig.hmftools.linx.visualiser.SvVisualiser \
    -sample ${tumor_id} \
    -vis_file_dir ${output_dir} \
    -ensembl_data_dir ${ensembl_dir} \
    -circos ${circos} \
    -plot_reportable \
    -debug \
