#!/bin/bash

pave_jar=$1 && shift
sample_id=$1 && shift
sage_vcf=$1 && shift
output_dir=$1 && shift
pave_germline_vcf=$1 && shift
ref_genome_version=$1 && shift
ref_genome=$1 && shift
ensembl_dir=$1 && shift
driver_gene_panel=$1 && shift
mappability_bed=$1 && shift
clinvar_vcf=$1 && shift
blacklist_bed=$1 && shift
blacklist_vcf=$1 && shift

if [[ ! -d "${output_dir}" ]]; then
  mkdir ${output_dir}
fi

output_vcf=${output_dir}/${sample_id}.sage.germline.pave.vcf.gz

if [[ -f "${output_vcf}" ]]; then
  echo "Skipping Pave germline for ${sample_id}, since VCF ${output_vcf} exists"
  exit
fi

if [[ ! -f "${sage_vcf}" ]]; then
  echo "Missing Sage germline VCF, not running Pave germline for ${sample_id}"
  exit
fi

args="-sample ${sample_id} \
  -ensembl_data_dir ${ensembl_dir} \
  -driver_gene_panel ${driver_gene_panel} \
  -ref_genome_version ${ref_genome_version} \
  -ref_genome ${ref_genome} \
  -mappability_bed ${mappability_bed} \
  -clinvar_vcf ${clinvar_vcf} \
  -blacklist_bed ${blacklist_bed} \
  -blacklist_vcf ${blacklist_vcf} \
  -vcf_file ${sage_vcf} \
  -read_pass_only \
  -output_vcf_file ${pave_germline_vcf}"

echo "Running Pave germline with args: ${args}"

java -jar ${pave_jar} ${args}
