#!/bin/bash

# example command:
# ./pipeline/scripts/run_tso500_pipeline ./pipeline/scripts /sample_data_dir/ /ref_data_dir/ /tools_dir/ COLO829T V37 10 16

# required arguments
scripts_dir=$1 && shift
samples_dir=$1 && shift
resources_dir=$1 && shift
tools_dir=$1 && shift
tumor_id=$1 && shift
ref_genome_version=$1 && shift
threads=$1 && shift
max_memory=$1 && shift

# input argument checks
if [[ ! -d "${scripts_dir}" ]]; then
  echo "Missing scripts directory: ${scripts_dir}"
  exit 1
fi

if [[ ! -d "${samples_dir}" ]]; then
  echo "Missing samples directory: ${samples_dir}"
  exit 1
fi

if [[ ! -d "${resources_dir}" ]]; then
  echo "Missing resources directory: ${resources_dir}"
  exit 1
fi

if [[ ! -d "${tools_dir}" ]]; then
  echo "Missing tools directory: ${tools_dir}"
  exit 1
fi


sample_dir=${samples_dir}/${tumor_id}

# assume BAM names match tumor and reference names
tumor_bam=${sample_dir}/${tumor_id}.bam

if [ "${max_memory}" == "" ]; then
  max_memory=16
fi

echo "Running HMF pipeline in ${run_mode} mode"

echo "Environment:"
echo "  scripts dir: ${scripts_dir}"
echo "  samples dir: ${samples_dir}"
echo "  resources dir: ${resources_dir}"
echo "  tools dir: ${tools_dir}"
echo "  tumorId: ${tumor_id}"
echo "  ref genome version: ${ref_genome_version}"
echo "  threads: ${threads}"
echo "  memory: ${max_memory}"

echo "Sample output dir: ${sample_dir}"

# set resource files
if [ "${ref_genome_version}" == "V37" ]; then
  echo "Reference genome version GRCh37"

  # Reference genome
  ref_genome=${resources_dir}/ref_genome/Homo_sapiens.GRCh37.GATK.illumina.fasta

  # Common
  ensembl_dir=${resources_dir}/common/ensembl_data/
  driver_gene_panel=${resources_dir}/common/DriverGenePanel.tso500.37.tsv

  # Point mutations (for Sage, Pave)
  sage_somatic_hotspots=${resources_dir}/variants/KnownHotspots.somatic.37.vcf.gz
  sage_panel_bed=${resources_dir}/variants/ActionableCodingPanel.tso500.37.bed.gz
  sage_coverage_bed=${resources_dir}/variants/CoverageCodingPanel.tso500.37.bed.gz
  high_confidence_bed=${resources_dir}/variants/NA12878_GIAB_highconf_IllFB-IllGATKHC-CG-Ion-Solid_ALLCHROM_v3.2.2_highconf.bed.gz
  somatic_pon_file=${resources_dir}/variants/SageGermlinePon.1000x.37.tsv.gz
  mappability_bed=${resources_dir}/variants/mappability_150.37.bed.gz
  gnomad_path=${resources_dir}/variants/gnomad_variants_v37.csv.gz
  pon_artefact_file=${resources_dir}/variants/pon_artefacts.tso500.37.tsv.gz

  # SVs (for Gripss, Linx)
  sv_hotspot_file=${resources_dir}/sv/known_fusions.37.bedpe
  sv_blacklist_bed=${resources_dir}/sv/sv_prep_blacklist.37.bed
  gridss_blacklist_bed=${resources_dir}/sv/gridss_blacklist.37.bed.gz
  gridss_config=${resources_dir}/sv/gridss.properties
  sv_pon_file=${resources_dir}/sv/sv_pon.37.bedpe.gz
  sgl_pon_file=${resources_dir}/sv/sgl_pon.37.bed.gz
  repeat_mask_file=${resources_dir}/sv/repeat_mask_data.37.fa.gz
  known_fusion_file=${resources_dir}/sv/known_fusion_data.37.csv
  
  # Copy number (for Amber, Cobalt, Purple)
  amber_loci_vcf=${resources_dir}/copy_number/GermlineHetPon.37.vcf.gz
  gc_profile=${resources_dir}/copy_number/GC_profile.1000bp.37.cnp
  tumor_only_diploid_bed=${resources_dir}/copy_number/DiploidRegions.37.bed.gz

  target_region_normalisation=${resources_dir}/copy_number/cobalt_normalisation.tso500.37.tsv
  target_regions_definition=${resources_dir}/copy_number/target_regions_definition.tso500.37.bed.gz
  target_regions_ratios=${resources_dir}/copy_number/target_regions_ratios.tso500.37.tsv
  target_regions_msi_indels=${resources_dir}/copy_number/target_regions_msi_indels.tso500.37.tsv

  # Immune (for Lilac)
  lilac_resource_dir=${resources_dir}/immune/

else
  echo "Reference genome version GRCh38"

  ref_genome=${resources_dir}/ref_genome/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna
  ensembl_dir=${resources_dir}/common/ensembl_data/
  driver_gene_panel=${resources_dir}/common/DriverGenePanel.tso500.38.tsv

  # Point mutations (for Sage, Pave)
  sage_somatic_hotspots=${resources_dir}/variants/KnownHotspots.somatic.38.vcf.gz
  sage_panel_bed=${resources_dir}/variants/ActionableCodingPanel.tso500.38.bed.gz
  sage_coverage_bed=${resources_dir}/variants/CoverageCodingPanel.tso500.38.bed.gz
  high_confidence_bed=${resources_dir}/variants/HG001_GRCh38_GIAB_highconf_CG-IllFB-IllGATKHC-Ion-10X-SOLID_CHROM1-X_v.3.3.2_highconf_nosomaticdel_noCENorHET7.bed.gz
  somatic_pon_file=${resources_dir}/variants/SageGermlinePon.98x.38.tsv.gz
  mappability_bed=${resources_dir}/variants/mappability_150.38.bed.gz
  gnomad_path=${resources_dir}/variants/gnomad/
  pon_artefact_file=${resources_dir}/variants/pon_artefacts.tso500.38.tsv.gz

  # SVs (for Gripss, Linx)
  sv_hotspot_file=${resources_dir}/sv/known_fusions.38.bedpe
  sv_blacklist_bed=${resources_dir}/sv/sv_prep_blacklist.38.bed
  gridss_blacklist_bed=${resources_dir}/sv/gridss_blacklist.38.bed.gz
  gridss_config=${resources_dir}/sv/gridss.properties
  sv_pon_file=${resources_dir}/sv/sv_pon.38.bedpe.gz
  sgl_pon_file=${resources_dir}/sv/sgl_pon.38.bed.gz
  repeat_mask_file=${resources_dir}/sv/repeat_mask_data.38.fa.gz
  known_fusion_file=${resources_dir}/sv/known_fusion_data.38.csv

  # Copy number (for Amber, Cobalt, Purple)
  amber_loci_vcf=${resources_dir}/copy_number/GermlineHetPon.38.vcf.gz
  gc_profile=${resources_dir}/copy_number/GC_profile.1000bp.38.cnp
  tumor_only_diploid_bed=${resources_dir}/copy_number/DiploidRegions.38.bed.gz
  
  target_region_normalisation=${resources_dir}/copy_number/cobalt_normalisation.tso500.38.tsv
  target_regions_definition=${resources_dir}/copy_number/target_regions_definition.tso500.38.bed.gz
  target_regions_ratios=${resources_dir}/copy_number/target_regions_ratios.tso500.38.tsv
  target_regions_msi_indels=${resources_dir}/copy_number/target_regions_msi_indels.tso500.38.tsv

  # Immune (for Lilac)
  lilac_resource_dir=${resources_dir}/immune/
fi

# place holders
emp_ref_file=ref_file
run_mode=PANEL
ref_none="none"
ref_bam_none="none"


# set tool links
sage_jar=${tools_dir}/sage.jar
pave_jar=${tools_dir}/pave.jar
amber_jar=${tools_dir}/amber.jar
gripss_jar=${tools_dir}/gripss.jar
cobalt_jar=${tools_dir}/cobalt.jar
purple_jar=${tools_dir}/purple.jar
linx_jar=${tools_dir}/linx.jar
lilac_jar=${tools_dir}/lilac.jar

circos=${tools_dir}/circos


# Amber
amber_dir=${sample_dir}/amber

${scripts_dir}/run_amber ${amber_jar} \
  ${tumor_id} ${tumor_bam} ${ref_none} ${ref_bam_none} \
  ${amber_dir} \
  ${run_mode} ${ref_genome_version} ${ref_genome} \
  ${amber_loci_vcf} ${threads} ${max_memory} \


# Cobalt
cobalt_dir=${sample_dir}/cobalt

${scripts_dir}/run_cobalt ${cobalt_jar} \
  ${tumor_id} ${tumor_bam} ${ref_none} ${ref_bam_none} \
  ${cobalt_dir} \
  ${run_mode} ${ref_genome} \
  ${gc_profile} ${tumor_only_diploid_bed} ${target_region_normalisation} \
  ${threads} ${max_memory} \


# Sage somatic

sage_somatic_dir=${sample_dir}/sage
sage_vcf=${sage_somatic_dir}/${tumor_id}.sage.vcf.gz

${scripts_dir}/run_sage_somatic ${sage_jar} \
  ${tumor_id} ${tumor_bam} ${ref_none} ${ref_bam_none} \
  ${sage_somatic_dir} ${sage_vcf} \
  ${run_mode} ${ref_genome_version} ${ref_genome} \
  ${ensembl_dir} ${sage_somatic_hotspots} ${sage_panel_bed} ${sage_coverage_bed} ${high_confidence_bed} \
  ${threads} ${max_memory} \


# Pave somatic
pave_somatic_dir=${sample_dir}/pave
pave_vcf=${pave_somatic_dir}/${tumor_id}.pave.vcf.gz

${scripts_dir}/run_pave_somatic ${pave_jar} \
  ${tumor_id}  \
  ${sage_vcf} ${pave_somatic_dir} ${pave_vcf} \
  ${run_mode} ${ref_genome_version} ${ref_genome} \
  ${ensembl_dir} ${driver_gene_panel} ${somatic_pon_file} ${pon_artefact_file} ${mappability_bed} ${gnomad_path} \



# Gridss 
gridss_dir=${sample_dir}/gridss
gridss_vcf=${gridss_dir}/${tumor_id}.gridss.unfiltered.vcf.gz

${scripts_dir}/run_sv_calling ${tools_dir} \
  ${tumor_id} ${tumor_bam} ${ref_none} ${ref_bam_none} \
  ${gridss_dir} ${gridss_vcf} \
  ${ref_genome_version} ${ref_genome} \
  ${sv_blacklist_bed} ${sv_hotspot_file} \
  ${gridss_blacklist_bed} ${gridss_config} \
  ${threads} ${max_memory} \


# Gripss somatic
gripss_somatic_dir=${sample_dir}/gripss

${scripts_dir}/run_gripss_somatic ${gripss_jar} \
  ${tumor_id} ${ref_none} \
  ${gripss_somatic_dir} ${gridss_vcf} \
  ${run_mode} ${ref_genome_version} ${ref_genome} \
  ${sv_hotspot_file} ${sv_pon_file} ${sgl_pon_file} ${repeat_mask_file} ${target_regions_definition}



# Purple
purple_dir=${sample_dir}/purple

somatic_sv_vcf=${gripss_somatic_dir}/${tumor_id}.gripss.filtered.somatic.vcf.gz
sv_unfiltered_vcf=${gripss_somatic_dir}/${tumor_id}.gripss.somatic.vcf.gz

${scripts_dir}/run_purple ${purple_jar} \
  ${tumor_id} ${ref_none} \
  ${pave_vcf} ${somatic_sv_vcf} ${sv_unfiltered_vcf} \
  ${emp_ref_file} ${emp_ref_file} \
  ${amber_dir} ${cobalt_dir} ${purple_dir} \
  ${run_mode} ${ref_genome_version} ${ref_genome} \
  ${gc_profile} ${sage_somatic_hotspots} ${emp_ref_file} \
  ${driver_gene_panel} ${ensembl_dir} ${emp_ref_file} \
  ${target_regions_definition} ${target_regions_ratios} ${target_regions_msi_indels} \
  ${threads} ${circos} ${max_memory} \


# Linx somatic
if [ "${ref_none}" != "none" ]; then
  linx_somatic_dir=${sample_dir}/linx_somatic
else
  linx_somatic_dir=${sample_dir}/linx
fi

purple_somatic_sv_vcf=${purple_dir}/${tumor_id}.purple.sv.vcf.gz

${scripts_dir}/run_linx_somatic ${linx_jar} \
  ${tumor_id} \
  ${purple_somatic_sv_vcf} ${purple_dir} ${linx_somatic_dir} \
  ${ref_genome_version} \
  ${ensembl_dir} ${driver_gene_panel} ${known_fusion_file} \
  ${circos} \


# Lilac
lilac_dir=${sample_dir}/lilac

${scripts_dir}/run_lilac ${lilac_jar} \
  ${tumor_id} ${tumor_bam} ${ref_none} ${ref_bam_none} \
  ${purple_dir} ${lilac_dir} \
  ${ref_genome_version} ${ref_genome} ${lilac_resource_dir} \
  ${threads} \


echo "Pipeline complete"
