package com.hartwig.hmftools.datamodel.linx;

public enum LinxUnreportableReason
{
    NONE,
    NOT_KNOWN,
    UNPHASED_NOT_KNOWN,
    UNPHASED_5P_UTR,
    UNPHASED_SHORT,
    SGL_NOT_KNOWN,
    PRE_GENE_DISTANCE,
    NONSENSE_MEDIATED_DECAY,
    NEG_SPLICE_ACC_DISTANCE,
    EXON_SKIPPING,
    CHAIN_TERMINATED,
    NON_DISRUPTIVE_CHAIN,
    INVALID_TRAVERSAL,
    CHAIN_LINKS,
    DISRUPTED_PROTEIN_DOMAINS
}
