package com.hartwig.hmftools.summon.actionability;

public enum Type {
    ACTIVATION_MUTATION,
    AMPLIFICATION,
    EXTRACELLULAR_DOMAIN_MUTATION,
    FUSION,
    INACTIVATION,
    INTERNAL_DELETION,
    KINASE_DOMAIN_DUPLICATION,
    LOSS,
    POSITIVE,
    RESISTENCE_MUTATION;
    ;
}