package com.hartwig.hmftools.summon.actionability;

public enum Type {
    ACTIVATING_MUTATION,
    AMPLIFICATION,
    EXTRACELLULAR_DOMAIN_MUTATION,
    FUSION,
    INACTIVATION,
    INTERNAL_DELETION,
    KINASE_DOMAIN_DUPLICATION,
    LOSS,
    POSITIVE,
    RESISTANCE_MUTATION;
}