package com.hartwig.hmftools.portal.converter.ids

const val CPCT_STUDY_PATTERN = "CPCT02"
const val DRUP_STUDY_PATTERN = "DRUP01"
const val PATIENT_AND_CENTER_NUMBER_PATTERN = "[0-9]{6}"
const val SAMPLE_NUMBER_PATTERN = "(R|T[XVI]*)"
const val PATIENT_ID_PATTERN = "($CPCT_STUDY_PATTERN|$DRUP_STUDY_PATTERN)$PATIENT_AND_CENTER_NUMBER_PATTERN"
const val SAMPLE_ID_PATTERN = "$PATIENT_ID_PATTERN$SAMPLE_NUMBER_PATTERN"
