#!/usr/bin/env bash

prefix=$(dirname $(readlink $0 || echo $0))
sql=${prefix}/generate_serve_db.sql

echo "[INFO] Regenerating knwledgebase database using ${sql}"
mysql --defaults-file=~/mysql.login -u build -pbuild serve_test < ${sql}