package com.hartwig.hmftools.serve.sources.actin.reader;

public enum ActinRule {
    ACTIVATION_OF_GENE_X,
    INACTIVATION_OF_GENE_X,
    ACTIVATING_MUTATION_IN_GENE_X,
    MUTATION_IN_GENE_X_OF_TYPE_Y,
    INACTIVATING_MUTATION_IN_GENE_X,
    AMPLIFICATION_OF_GENE_X,
    DELETION_OF_GENE_X,
    ACTIVATING_FUSION_IN_GENE_X,
    SPECIFIC_FUSION_X,
}
