package com.hartwig.hmftools.serve.sources.actin.reader;

public enum ActinRule {
    ACTIVATION_OR_AMPLIFICATION_OF_GENE_X,
    ACTIVATING_MUTATION_IN_GENE_X,
    FUSION_IN_GENE_X,
    SPECIFIC_FUSION_OF_X_TO_Y,
    INACTIVATION_OF_GENE_X,
    MUTATION_IN_GENE_X_OF_TYPE_Y,
    AMPLIFICATION_OF_GENE_X,
    DELETION_OF_GENE_X,
    WILDTYPE_OF_GENE_X,
    MSI_SIGNATURE,
    HRD_SIGNATURE,
    TMB_OF_AT_LEAST_X,
    TML_OF_AT_LEAST_X,
    TML_OF_AT_MOST_X,
    HAS_HLA_A_TYPE_X
}