package com.hartwig.hmftools.knowledgebaseimporter.cgi

internal const val BCR_ABL_INHIBITOR = "BCR-ABL inhibitor"
internal const val EGFR_INHIBITOR = "EGFR inhibitor"
internal const val EGFR_MAB_INHIBITOR = "EGFR mAb inhibitor"
internal const val ERBB2_INHIBITOR = "ERBB2 inhibitor"
internal const val ALK_INHIBITOR = "ALK inhibitor"
internal const val ROS1_INHIBITOR = "ROS1 inhibitor"
internal const val CHECKPOINT_INHIBITOR = "Checkpoint inhibitor"
internal const val AKT_INHIBITOR = "AKT inhibitor"
internal const val CHEMOTHERAPY = "Chemotherapy"
internal const val CDK4_6_INHIBITOR = "CDK4/6 inhibitor"
internal const val PI3K_INHIBITOR = "PI3K inhibitor"
internal const val JAK_INHIBITOR = "JAK inhibitor"
internal const val MEK_INHIBITOR = "MEK inhibitor"
internal const val FLT3_INHIBITOR = "FLT3 inhibitor"
internal const val AR_INHIBITOR = "AR inhibitor"
internal const val TRK_INHIBITOR = "TRK inhibitor"
