package com.hartwig.hmftools.finding.datamodel;

public enum FindingsStatus
{
    NOT_AVAILABLE_REF_REQUIRED,
    NOT_AVAILABLE_RESULT_MISSING,
    NOT_AVAILABLE_WGS_REQUIRED,
    NOT_AVAILABLE_NO_TUMOR_CELLS,
    NOT_AVAILABLE_CONTAMINATION,
    NOT_AVAILABLE_TUMOR_IN_NORMAL_CONTAMINATION,
    NOT_RELIABLE_LOW_PURITY,
    NOT_RELIABLE,
    OK
}
