package com.hartwig.hmftools.serve.sources.ckb.filter;

public enum CkbFilterType {
    FILTER_ANY_VARIANT_WITH_KEYWORD,
    FILTER_ALL_EVIDENCE_ON_GENE,
    FILTER_EVIDENCE_FOR_EXONS_ON_GENE,
    ALLOW_GENE_IN_FUSIONS_EXCLUSIVELY,
    FILTER_SECONDARY_GENE_WHEN_FUSION_LEG
}
