package com.hartwig.healthchecker.checkers.checks;

public enum MappingCheck {
    MAPPING_PROPORTION_READ_VS_TOTAL_SEQUENCES,
    MAPPING_PERCENTAGE_MAPPED,
    MAPPING_PROPERLY_PAIRED_PROPORTION_OF_MAPPED,
    MAPPING_PROPORTION_SINGLETON,
    MAPPING_PROPORTION_MAPPED_DIFFERENT_CHR,
    MAPPING_MARKDUP_PROPORTION_DUPLICATES
}
