#!/bin/bash

cobalt_jar=$1 && shift
tumor_id=$1 && shift
tumor_bam=$1 && shift
output_dir=$1 && shift
ref_genome=$1 && shift
gc_profile=$1 && shift
tumor_only_diploid_bed=$1 && shift
target_region_normalisation=$1 && shift
threads=$1 && shift

output_tsv=${output_dir}/${tumor_id}.cobalt.ratio.tsv.gz

if [[ -f "${output_tsv}" ]]; then
  echo "Skipping Cobalt for ${tumor_id}, since output ${output_tsv} exists"
  exit
fi

echo "Running Cobalt for ${tumor_id}, output dir ${output_dir}"

if [[ ! -d "${output_dir}" ]]; then
  mkdir ${output_dir}
fi

java -jar ${cobalt_jar} \
  -tumor ${tumor_id} \
  -tumor_bam ${tumor_bam} \
  -ref_genome ${ref_genome} \
  -gc_profile ${gc_profile} \
  -tumor_only_diploid_bed ${tumor_only_diploid_bed} \
  -target_region ${target_region_normalisation} \
  -pcf_gamma 15 \
  -threads ${threads} \
  -output_dir ${output_dir} \
