package com.hartwig.hmftools.common.purple;

public enum HrdStatus
{
    HRD_DEFICIENT_LOW_CONFIDENCE,
    HRD_DEFICIENT_HIGH_CONFIDENCE,
    HRD_PROFICIENT_LOW_CONFIDENCE,
    HRD_PROFICIENT_HIGH_CONFIDENCE,
    UNKNOWN;
}
