#!/usr/bin/env bash

prefix=$(dirname $(readlink $0 || echo $0))
sql=${prefix}/create_vicc_database.sql

echo "[INFO] Regenerating VICC database using ${sql}"
mysql --defaults-file=~/mysql.login -u build -pbuild vicc_test < ${sql}