package com.hartwig.hmftools.linx.fusion;

public enum ReportableReason
{
    UNSET,
    OK,
    KNOWN_TYPE,
    UNPHASED_NOT_KNOWN,
    UNPHASED_5P_UTR,
    UNPHASED_SHORT,
    SGL_NOT_KNOWN,
    PRE_GENE_DISTANCE,
    NMD,
    NEG_SPLICE_ACC_DISTANCE,
    EXON_SKIPPING,
    CHAIN_TERMINATED,
    NON_DISRUPTIVE_CHAIN,
    INVALID_TRAVERSAL,
    CHAIN_LINKS,
    PROTEIN_DOMAINS
}
