/*
 * This file is generated by jOOQ.
*/
package org.ensembl.database.homo_sapiens_core.enums;


import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum ExternalDbStatus implements EnumType {

    KNOWNXREF("KNOWNXREF"),

    KNOWN("KNOWN"),

    XREF("XREF"),

    PRED("PRED"),

    ORTH("ORTH"),

    PSEUDO("PSEUDO");

    private final String literal;

    private ExternalDbStatus(String literal) {
        this.literal = literal;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return null;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return null;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String getName() {
        return "external_db_status";
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String getLiteral() {
        return literal;
    }
}
