package prep;

public enum FeatureType
{
    BAM_METRICS_COVERAGE,
    BAM_METRICS_FRAG_LENGTH,
    BAM_METRICS_GENE_COVERAGE_SUMMARY,
    COBALT_GC_MEDIAN,
    REDUX_DUPLICATE_FREQ,
    REDUX_MS_TABLE,
    SAGE_BQR_PER_SNV96_CONTEXT,
    SAGE_BQR_PER_ORIG_QUAL,
    ESVEE_PREP_DISC_STATS,

    AMBER_QC,
    PURPLE_QC,
    PURPLE_PURITY,
    BAM_METRICS_SUMMARY,
    BAM_METRICS_COVERAGE_BINNED;
}
