#!/usr/bin/env bash

prefix=$(dirname $(readlink $0 || echo $0))
sql=${prefix}/generate_iclusion_db.sql

echo "[INFO] Regenerating iclusion database using ${sql}"
mysql --defaults-file=~/mysql.login -u build -pbuild iclusion_test < ${sql}